### ISSUE TITLE
DoTween Pro Visual Manager Component Autoplay bug

### ISSUE THREAD

**Issue by SeyeonSoft** [Demigiant/dotween#100]
Hi, i am using the dotween pro usefully in the Unity 5.x.xx

But recently i have found the bug related to DoTween Visual Manager component.

After i add the DoTween Animation and DoTween Visual Manger ( OnEnable : Restart ) component in the UGUI images, when scene is started, It always call "OnComplete" automatically even i turned off the "AutoPlay" option in the DoTween Animation component.

But If i remove the DoTween Visual Manager, it does not call "OnComplete" automatically.

This bug occurs in the Unity 5.3.5f1 and Unity 5.4.1f1. I did not check other unity version.

PS.
It works well at first time even i add the DoTween Visual Manager. but as time goes by, if i add or edit the DoTween Visual Manager component in other images, this bug occurs.

Also, after removing the DoTween Visual Manager component and then if i add the DoTween Visual Manager component, it works well for a while. As time goes by, this bug occurs again.

Thanks

**Comment by Demigiant** [comment]
Working on this via mails (as of now can't reproduce the issue).

**Comment by SeyeonSoft** [comment]
Hi, Daniele

Thank you for quick response.

And I found the solution. :)

After I change the OnEnable option in the dotween manager component from "Restart" to "Restart From Spawn Point", it works well.

It does not call the "OnComplete" any more when scene is started.

I don't know why but it works well anyway.

Have a nice day~
ByeongCheol
