### ISSUE TITLE
DOVirtual.Float (10, 0, 10, onTimeCountdown); don't give real second count down.

### ISSUE THREAD

**Issue by zszen** [Demigiant/dotween#101]
Thank your DoTween component. My work fast. Now I have a question. twTimeCountdown = DOVirtual.Float (10, 0, 10, onTimeCountdown); this display text don't count down in real second. It is so fast. I can't slow down it. SetUpdate(true) don't work.

**Comment by zszen** [comment]
fixed it with .SetEase(Ease.Linear)

**Comment by Demigiant** [comment]
Hi Zsen,

DOVirtual.Float will use the default ease, which unless you changed it will
be OutQuad. Use SetEase to set it to Linear and it will do ;)

Cheers,
Daniele
