### ISSUE TITLE
Possible to do play a sound when ball hit floor with Easing Elastic Out Bounce?

### ISSUE THREAD

**Issue by kenglou** [Demigiant/dotween#102]
as titled. 

Recently I want to play a sound when there is a ball dropping to the floor. The ball uses Easing Type Elastic Out Bounce and I'm thinking to add a sound when the ball hit the floor. Is there any example of doing so?

Thank you very much if this problem can be solved.

**Comment by Demigiant** [comment]
Hi,

You would need to use regular collision detection for that, there's nothing implemented in DOTween that allows to determine if a bounce is hitting something :P

Cheers,
Daniele
