### ISSUE TITLE
Obfuscated API design - Kill() and Tween reuse causing Tweens to not play

### ISSUE THREAD

**Issue by thefuntastic** [Demigiant/dotween#107]
There is a problem I routinely run into and can't seem to get my head around. It's a common pattern for me to want to stop a tween, particular if a routine needs to exit early. The only way I've found to stop a tween is Kill(), however this seems to limit your ability to cache and reuse the tween as resuming after a kill seems to not work? 

```
var tween = DOVirtual.DelayedCall(1f, OnComplete); //Create Tween instance, autoplays as per DoTween config

//On early exit
tween.Kill()  //Only way I've found to stop a tween

//On next time enter routine
tween.Restart() //Tween doesn't play or throw error
tween.Play() //Tween doesn't play or throw error
```

In this case the only solution I've found is to create a new tween instance every time, but that generates garbage. Is there something about the structure of the tween libs i haven't understood, or a way we could make the API more intuitive (ie other tween libs would have Stop() method and a Kill() method, where it's easy to understand Kill as causing the disposal side-effect that makes a tween invalid).

**Comment by Demigiant** [comment]
Hi,

You can `Pause` a tween (which stops it but doesn't rewind it) or `Rewind` it (which stops and rewinds it).

Cheers,
Daniele
