### ISSUE TITLE
DOTWeen Examples project: Multiple errors 

### ISSUE THREAD

**Issue by rgarrett7** [Demigiant/dotween#110]
When Importing the package: DOTweenExamples_Unity5.unitypackage, I get 4 errors and 22 warnings.  

Errors are: 
System.InvalidOperationException: Operation is not valid due to the current state of the object. [Repeated twice]

Assets/Demigiant/DOTweenPro/DOTweenAnimation.cs(450,21): error CS1501: No overload for method `PlayBackwards' takes `2' arguments

Assets/Demigiant/DOTweenPro/DOTweenAnimation.cs(459,21): error CS1501: No overload for method `PlayForward' takes `2' arguments

I just installed for the first time and ran Setup from the DOTween Utility panel : 
DOTween v.1.1.315
DOTween Pro v.0.9.550

Unity Version: 5.5.0f3 Personal

MacOS Sierra 10.12.2
Macbook Pro laptop

**Comment by Demigiant** [comment]
Hi,

Are you talking about the examples you downloaded from [here](http://dotween.demigiant.com/examples.php)?

Let me know, that seems very weird, and I will be able to check it tomorrow.

**Comment by rgarrett7** [comment]
Yes, that is right.  Let me know if I can send you any additional
information to help.

Thanks, Randy

**Comment by rgarrett7** [comment]
Danielle,

I tried to do some troubleshooting on this.  I am running Unity 5.50F on a
MacBook Pro with MacOS Sierra 10.12.2 (latest version).

I downloaded the latest version of DOTween (v1.1.340).  I created a new
project with Unity, then exited Unity.  I moved the DOTween directory into
the newly created Assets directory and reopened Unity.  I opened the
Utility panel and setup DOTWeen.  It shows the correct version, but just
for good measure, I hit the Check Updates button, and it says I have the
latest version. DOTween shows as a folder in the Assets folder within
Unity.

Next, I went to Assets, Import Package, Custom Package, and loaded
"DOTweenExamples_Unity5.unitypackage" .  The Unity Import Package panel
appears.  I imported everything shown in the panel.

In the Console window, I see four messages (which is 1 less then yesterday
for some reason).

There is one warning message: "erriding existing asset with new GUID from
package, this may break links within your project to package assets
(Assets/Resources/DOTweenSettings.asset)"

Then 3 errors:

1.  "System.InvalidOperationException: Operation is not valid due to the
current state of the object.
  at Mono.Cecil.ModuleDefinition.ProcessDebugHeader () <0x10b6df1a0 +
0x000ca> in <filename unknown>:0
  at Mono.Cecil.ModuleDefinition.ReadSymbols (ISymbolReader reader)
<0x10b6df0d0 + 0x0005b> in <filename unknown>:0 ... this continues at some
length"

2. "System.InvalidOperationException: Operation is not valid due to the
current state of the object.
  at Mono.Cecil.ModuleDefinition.ProcessDebugHeader () <0x10d9a71a0 +
0x000ca> in <filename unknown>:0
  at Mono.Cecil.ModuleDefinition.ReadSymbols (ISymbolReader reader)
<0x10d9a70d0 + 0x0005b> in <filename unknown>:0 ... and so on"

3. "Error CS1704: An assembly with the same name `DOTween50' has already
been imported. Consider removing one of the references or sign the assembly
Assets/DOTween/DOTween50.dll (Location of the symbol related to previous
error)
Assets/Demigiant/DOTween/DOTween50.dll (Location of the symbol related to
previous error)
error CS1704: An assembly with the same name `DOTween' has already been
imported. Consider removing one of the references or sign the assembly
Assets/DOTween/DOTween.dll (Location of the symbol related to previous
error)
Assets/Demigiant/DOTween/DOTween.dll (Location of the symbol related to
previous error)
error CS1704: An assembly with the same name `DOTween43' has already been
imported. Consider removing one of the references or sign the assembly
Assets/DOTween/DOTween43.dll (Location of the symbol related to previous
error)
Assets/Demigiant/DOTween/DOTween43.dll (Location of the symbol related to
previous error) ... and so on"

Within the Assets folder in Unity, I see:

Basics scene + C# script
Custom Plugin Example folder
Demigiant folder
DOTween folder
Example Assets
Follow scene + C# script
Materials scene + script
Paths scene + script
Resources folder
Sequences scene + script
UGUI scene + script

When I clicked on the Basics script to look at it in Inspector, the systems
says "Loading" and hangs.  While hung, the system shows only 4% CPU for
Unity ( and minimal for the rest of the system).  No disk or network
activity.

Hope this helps!

Randy

**Comment by rgarrett7** [comment]
Danielle,

Based on the error messages, I realized the Example package might already
have DOTween bundled in.  So, I create a new project and just import the
Example package without loading DOTWeen beforehand.  DOTween did appear to
load as part of importing the package.  No doubt you knew that already.
The version this time shows v. 1.1.35.

Unfortunately, I still get 2 error and 2 warnings.  The errors are:

" System.InvalidOperationException: Operation is not valid due to the
current state of the object.
  at Mono.Cecil.ModuleDefinition.ProcessDebugHeader () <0x10b5871a0 +
0x000ca> in <filename unknown>:0 "

"System.InvalidOperationException: Operation is not valid due to the
current state of the object.
  at Mono.Cecil.ModuleDefinition.ProcessDebugHeader () <0x1024c41a0 +
0x000ca> in <filename unknown>:0
  at Mono.Cecil.ModuleDefinition.ReadSymbols (ISymbolReader reader)
<0x1024c40d0 + 0x0005b> in <filename unknown>:0 "

Warnings are:

"Assets/CustomPlugin Example/CustomRangePlugin.cs(56,21): warning CS0219:
The variable `res' is assigned but its value is never used"

"OnLevelWasLoaded was found on DOTweenComponent
This message has been deprecated and will be removed in a later version of
Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications
after scene loading has completed"

On the plus side, I can now read all the scripts in the Inspector.

Randy

**Comment by Demigiant** [comment]
Thanks a lot for the additional feedback. I was trying to replicate the issue but couldn't. What you said is helping me, even if those ProcessDebugHeader errors are very weird.
Tomorrow I'll remake the packages without DOTween, so there won't be more double imports. In the meantime, you should delete the DOTween version you kept, and reimport it. One of the warnings is inside the examples, and I'll fix it, but the other means you deleted the most recent DOTween and kept the examples' one, which is pretty older. In theory that should fix also the errors.

**Comment by rgarrett7** [comment]
Okay, I will do that.  Thanks for checking into this.

Randy

**Comment by Demigiant** [comment]
Ooops sorry forgot to update the issue, but this should be solved now.

**Comment by rgarrett7** [comment]
Thanks!  I look forward to going through the examples. I was able to use
your product in several areas already.  This should give me new ideas.

Randy

**Comment by rgarrett7** [comment]
Danielle,

Just to let you know, your update fixed all the errors, and the examples
run great now.

Thanks!

Randy

**Comment by Demigiant** [comment]
Thanks to you for the feedback :)
