### ISSUE TITLE
Run In Background

### ISSUE THREAD

**Issue by paveldk** [Demigiant/dotween#112]
Hi, 

I would like to make my game be able to run in background. The problem is that some of the objects that I'm animating using dotween (animating position, rotation) are left in mid animation if I blur and then re-focus my game. This happens both in the editor player and with build package. I've enabled the run in background option for the project both from the Unity menu and from code. But this does not seem to solve the problem.

Is this a problem that can be solved?

Regards

**Comment by Demigiant** [comment]
Hi,

Do you mean they stop and never continue? That is very weird, DOTween's logic shouldn't have any problem with running in background. Does the rest of your game continue as usual, or just the tweens stop? I'm thinking that somehow your timeScale is set to 0 when losing focus and never goes back.

**Comment by Demigiant** [comment]
P.S. I tested in the editor player and my tweens continue as normal when I refocus on Unity.

**Comment by paveldk** [comment]
Please ignore, tried to reproduce it multiple times, and could not, except in one particular project, so it should be some other problem with the project. However, thank you for the fast response.
