### ISSUE TITLE
IndexOutOfRangeException when deactivating from Tweener.OnKill and killing from MonoBehaviour.OnDisable

### ISSUE THREAD

**Issue by Trisibo** [Demigiant/dotween#117]
The following script (attached to a scene object) will launch an `IndexOutOfRangeException` exception after 5 seconds:

```
using UnityEngine;
using DG.Tweening;
using System.Collections;

public class Test : MonoBehaviour
{
    private IEnumerator Start()
    {
        transform.DOScale(Vector3.zero, 1000).OnKill(() => gameObject.SetActive(false));
        yield return new WaitForSeconds(5);
        transform.DOKill();
    }


    private void OnDisable()
    {
        transform.DOKill();
    }
}
```

**Comment by Demigiant** [comment]
Fixed in [this new update](http://dotween.demigiant.com/tmp/DOTween_1_1_575.zip). Can you grab it and let me know if everything's alright on your side (I'm gonna close the issue now, but please reply anyway)?

**Comment by Trisibo** [comment]
Yes, the update is working fine.

**Comment by Demigiant** [comment]
Great, thanks.
