### ISSUE TITLE
examples won't load in Unity 5.6

### ISSUE THREAD

**Issue by KavanBahrami** [Demigiant/dotween#128]
There are a ton of namespace errors after loading the example files from the website (http://dotween.demigiant.com/examples.php)

What's the fix for this?

example:
Assets/DOTween Examples/Basics.cs(3,7): error CS0246: The type or namespace name `DG' could not be found. Are you missing an assembly reference?

**Comment by Demigiant** [comment]
Hi,

It seems like you downloaded the examples but don't have DOTween installed? Gonna make a quick check to be on the safe side, but the problem seems to be that. You can download DOTween from the website of from the Asset Store.

**Comment by Demigiant** [comment]
Verified the problem is that one. I modified the website text that says "examples don't contain DOTween" so it's more evident :P
