### ISSUE TITLE
After using DOTween.KillAll(false); and then can not get DoTweenPath.GetDrawPoints();

### ISSUE THREAD

**Issue by natsupy** [Demigiant/dotween#134]
Like title, after using KillAll, the waypoints in DoTweenPath was null, so what am i mistake, can you help to fix it ? Thank you so much !

**Comment by Demigiant** [comment]
Why are you using a KillAll? KillAll kills all tweens and releases them from memory, clearing all their data. If you want to just pause all tweens use PauseAll.

**Comment by natsupy** [comment]
uhm, thank you,  because i want to kill all tween have running in time, so i'll try your pause
