### ISSUE TITLE
DOTween Pro 0.9.680 is not finding TextMesh Pro 1.0.55.0b9

### ISSUE THREAD

**Issue by akurani** [Demigiant/dotween#136]
Versions:

- DOTween Pro 0.9.680
- TextMesh Pro 1.0.55.0b9
- Unity 5.6.1f1
- MacOS Sierra 10.12.4

Repro Steps:

1. Create new project.
2. Import TextMesh Pro 1.0.55.0b9 (the free version published by Unity; not the older, paid version).
3. Import DOTween Pro 0.9.680.
4. Run Setup DOTween.
5. In code, try to use a DOTween shortcut with a TMP object, and notice it's missing (e.g., tmpObject.DOText(...)).
6. In editor, try to use DOTween Tween Animation with a TMP object, and notice there's no option for TMP.

Noticed two things:

1. Setup deleted: DOTweenTextMeshPro.cs.addon
2. The DOTWEEN_TMP #define is not enabled.

Thanks,
Amar

**Comment by Demigiant** [comment]
Agh! Version b9 of TextMesh Pro has changed the name of its DLL again, so DOTween doesn't find it :( Gonna push an update asap. If you have access to the private [DOTween Pro download area](http://forum.demigiant.com/index.php?topic=2.0), I'll place an updated version there in a couple hours, while waiting for the Asset Store to approve the new release.

**Comment by akurani** [comment]
Thanks. FYI, I just registered for access to the download area. Same user name: akurani.

**Comment by Demigiant** [comment]
Just approved you and put v0.9.685 there :)
