### ISSUE TITLE
NaN Input Error. 

### ISSUE THREAD

**Issue by sinhadanish** [Demigiant/dotween#137]
DoTween: v1.1.315
DoTweenPro: v0.9.550
Unity 5.5.2.1f
Windows 10 64 Bit 

Hey, 

I am creating a Pop effect for my EnergyBar every time the number increments. I have included all the functions involved which might be causing an error (Error Message in the Bottom).

Please help I am stuck in my development. 
Also, I am using Doozy, TMP and EnergyBar Assets which might be of concern.  

Regards 
Danish Sinha

Calling Function:  

1. if (1 / (float)eventReward.rewardItemList[currentRewardIndex].amount >= 0.1f)
                    {
                        if(eventReward.rewardItemList[currentRewardIndex].rewardType == RewardItem.currentRewardType.car)
                            PopTransform(rewardKeyBarHolder.transform, 1 / (float)eventReward.rewardItemList[currentRewardIndex].amount);
                        else
                            PopTransform(rewardCurrencyBarHolder.transform, 1 / (float)eventReward.rewardItemList[currentRewardIndex].amount);       
                    }

2. if (1 / (float)eventReward.rewardItemList[currentRewardIndex].amount < 0.1f)
            {
                if (eventReward.rewardItemList[currentRewardIndex].rewardType == RewardItem.currentRewardType.car)
                    StartCoroutine(ShakeCoroutine(rewardKeyBarHolder, 0.1f));
                else
                    StartCoroutine(ShakeCoroutine(rewardCurrencyBarHolder, 0.1f));                                                     
            }

IEnumerator ShakeCoroutine(Transform transform2Shake, float duration)
        {
            int currentReward = currentRewardIndex;
            while (firstBarInProgress)
            {
                PopTransform(transform2Shake, duration);
                yield return new WaitForSeconds(duration);
            }

        }

Popping Function: 
 void PopTransform(Transform transform2Pop, float duration)
        {              
            transform2Pop.GetComponent<RectTransform>().DOShakeScale(duration, 0.15f, 10, 90f, true)
                        .OnComplete(() => {transform2Pop.transform.localScale = transform.localScale; })              
                        .SetEase(Ease.InOutBack)
                        .Play();
        }

Error Message: 
`transform.localScale assign attempt for 'KeyBarPanelInternal' is not valid. Input localScale is { NaN, NaN, NaN }.
UnityEngine.Transform:set_localScale(Vector3)
DG.Tweening.<>c__DisplayClass62_0:<DOShakeScale>b__1(Vector3) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/ShortcutExtensions.cs:813)
DG.Tweening.Plugins.Vector3ArrayPlugin:EvaluateAndApply(Vector3ArrayOptions, Tween, Boolean, DOGetter`1, DOSetter`1, Single, Vector3[], Vector3[], Single, Boolean, UpdateNotice) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Plugins/Vector3ArrayPlugin.cs:136)
DG.Tweening.Core.TweenerCore`3:ApplyTween(Single, Int32, Int32, Boolean, UpdateMode, UpdateNotice) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenerCore.cs:175)
DG.Tweening.Tween:DoGoto(Tween, Single, Int32, UpdateMode) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:238)
DG.Tweening.Core.TweenManager:Update(UpdateType, Single, Single) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:404)
DG.Tweening.Core.DOTweenComponent:Update() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:50)
`

**Comment by Demigiant** [comment]
Replied to your mail, so we'll keep communications there since it's easier in this case.
