### ISSUE TITLE
Tween callback params

### ISSUE THREAD

**Issue by alryazanov** [Demigiant/dotween#14]
Hi!

I saw in the documentation that the transfer parameters in the callback goes through lambda/closures.
But why not add a transfer custom parameters (eg params[])? Sometimes closures are not desirable. In addition, it would be helpful to have in the callback information about Tween who raised him.

Thanks!

**Comment by Demigiant** [comment]
Hi!

I preferred to avoid params and/or specific parameter in order to have a cleaner and more usable method signature for callbacks. You can still pass the tween itself via lambda/closures, as long as you assign the callback after assigning the tween.

Cheers!

**Comment by alryazanov** [comment]
I'm just worried about the overhead of closures, for example if you add callbacks with element closure in the loop for move a array of elements.

**Comment by Demigiant** [comment]
I totally understand your worries, but it's better to have closures than to have to worry about having tweens that are too heavy, since every callback adds around 4B to the tween itself, even if unused. So closures seem to me like the best necessary evil. I'll ponder about this more though: let me know if you have more thoughts.

**Comment by wyyayy** [comment]
Closures doesn't work if use OnComplete in a for loop.

**Comment by optimisez** [comment]
Hi @Demigiant, is there any solution to make it gc free without using lambda/closures or params[]?

**Comment by Demigiant** [comment]
Ahoy!
If you pass a direct reference to a method without generating an anonymous one via a lambda, GC is avoided there.
`myTween.OnComplete(SomeOtherMethod)`
