### ISSUE TITLE
Floating Point Precison Issues

### ISSUE THREAD

**Issue by justinwasilenko** [Demigiant/dotween#143]
I was in contact with the developer of Simple Waypoint System for Unity. I am running into a issue where using very large paths and starting a object on that path results in very random behavior.

Here is a video showing the problem:
https://youtu.be/sLOBGyl7O9M

And here is the response from Baroni

> Thanks for the confirmation. I've brought this up with Daniele (developer of DOTween) some time ago, but we couldn't figure out a way to solve this, since Unity just adds some very minor offset to the desired Vector3 position due to the floating point issue mentioned. This results in DOTween adding a new waypoint at the current position (which it shouldn't), because it thinks the difference of 0.000x makes it a new starting point. Maybe a solution would be to let DOTween ignore more than 3 decimals for creating waypoint positions... Simple Waypoint Systems only uses these generated positions for its path movement, so technically I cannot implement a fix on my side.

**Comment by Demigiant** [comment]
Hi Justin,

Sorry for the late answer. Taxes period here, and I'm losing tons of time with that. I will check this today and get back to you!

Cheers,
Daniele

**Comment by Demigiant** [comment]
Ok so... I don't remember the conversation Baroni mentioned (but my memory is legendarily bad), but I already let Unity take into account floating point imprecision when calculating if an additional starting point is required or not, so I think something else is happening in your case. Also, your path doesn't seem touched by any floating point imprecision problem, unless that cube is smaller than 0.00001 units. Why do you think it's that?

Anyway, to be on the safe side, what I could do is add an option to force DOTween NOT to add any additional point even if it deems it necessary. I'm gonna check with Baroni and see.

**Comment by Demigiant** [comment]
Hi Justin,

Took us a while, and in the end it was a surprising Unity bug (when assigning a Vector3 to a transform.position, Unity doesn't assign it well enough in some cases, so much that they're not even approximately equal). I pushed a workaround though, so if you replace your current DOTween version with [this one](http://dotween.demigiant.com/download.php) it's fixed.

**Comment by Powerchamp** [comment]
Hi Daniele,

Are you still open to adding an option to force DOTween to not add any additional waypoints?

It would be very helpful.

Tom
