### ISSUE TITLE
DoLocalMove do not reach destination

### ISSUE THREAD

**Issue by eduardhasanaj** [Demigiant/dotween#150]
Hi,
I am having a strange issue with dotween, DoLocalMove seems like it add end to current position; This tween is in a sequence.
I tried also DoLocalMoveY, but the same problem.
Here are the detail
Current y: -156.5
Destination: 306.9
after animation finish: 150.4

**Comment by eduardhasanaj** [comment]
Oh my bad, I was using Transform instead of Rect Transform

**Comment by Demigiant** [comment]
:)

**Comment by styrbo2** [comment]
i have same problem but it reformed when im use Transform instead of Rect Transform -_-

**Comment by Demigiant** [comment]
You sure you're using the correct coordinates? There should really be no bugs with DOLocalMove. Tell me more.
