### ISSUE TITLE
Incorrect data from tweener()

### ISSUE THREAD

**Issue by eduardhasanaj** [Demigiant/dotween#153]
Hi,
I am using DoTween for a path animation. The object that is following the path is a RecTransform.
Here is Path 
![150604016799480](https://user-images.githubusercontent.com/23219826/30724635-8b1671c0-9f3f-11e7-957c-f64e3a76aa0c.png)

WhenI call ElapsedPercentage at the position in picture it is 0.5. 

I am using DoLocalPath (path, joiningAnimationDuration, PathType.CatmullRom, PathMode.Full3D, 5)

But it has passed the half of path. Is this correct?

**Comment by Demigiant** [comment]
Hi,

It all comes down to the ease you're using. For example, the default ease,
OutQuad, starts faster and ends slower, thus 0.5 will be beyond a path's
mid-point, yes. If you set the ease to Ease.Linear, then you'll have no
acceleration and 0.5 will be in the middle.

Cheers,
Daniele

**Comment by eduardhasanaj** [comment]
Oh sorry. I didn't know what ease do. Thank you for your help
May I ask if a function like play to position exist.
Currently my approach is to use an Coroutine and inside
yield return WaitForPosition(to);
pause

**Comment by Demigiant** [comment]
No "play up to position" method exists,, so I'd recommend using WaitForPosition as you're doing.

**Comment by eduardhasanaj** [comment]
Ok thank you very much. I will donate ASAP to DoTween. Putting such a great package free is wonderful gesture that only a small people can do.

**Comment by Demigiant** [comment]
That's very kind of you :)

**Comment by eduardhasanaj** [comment]
Sorry for firing up this. I didnt want to create a new Issue
I know that we cannot get 100% accurate results but the error I am seeing is not tolerable in my scenario.
I am using dotween to animate balls along a symmetric curve. all ball are centered in curve. when a ball is added, others are pushed right to keep balls centered. but each time animations are played I think we have error so these things are not pushed by amount i want but more.
I calculate distance by converting in corresponding animation time.
for example:
timeToTravel = (distanceBetweenBalls / pathlengths)*animationDuration;
then i yield waitforposition (tweener.Elapse() + timeToTravel)
What can be the problem

**Comment by Demigiant** [comment]
Hi,

`WaitForPosition` waits for the first frame where the tween has reached the given position. Due to the time that elapses between frames, it will never be the exact position (except very rare and unaccountable occasions), but the nearest one in excess.

Consider that `WaitForPosition` is not a "wait and stop at this position", but just a callback that fires as soon as that position is detected, frame-wise. If you want to stop at the exact position you requested, as soon as `WaitForPosition` is passed, you could call a `tween.Goto(waitedPosition)`.

**Comment by eduardhasanaj** [comment]
I got what you mean. Thank you for your support.
