### ISSUE TITLE
DOFade not working on CanvasGroup

### ISSUE THREAD

**Issue by netlander** [Demigiant/dotween#154]
When I try using 

`GetComponent<CanvasGroup>().DOFade(1.0, 1.0);`

I get the following error:

`UnityEngine.CanvasGroup' does not contain a member `DOFade`

Using DOTween 0.9.690

**Comment by Demigiant** [comment]
Hi,

It seems you didn't run DOTween's setup, because you're missing the DOTween46.dll. You can find it under "Tools > Demigiant > DOTween Utility Panel".

Cheers,
Daniele

**Comment by netlander** [comment]
Have seen your answer somewhere else and redone the setup multiple times (force setup) without getting rid of the problem.

Now I've tried a brand new project with just DOTween and still the same problem.

The full error message:

`
Assets/dotweenManager.cs(11,34): error CS1929: Type UnityEngine.CanvasGroup does not contain a member DOFade and the best extension method overload DG.Tweening.ShortcutExtensions43.DOFade(this UnityEngine.SpriteRenderer, float, float) requires an instance of type UnityEngine.SpriteRenderer`

First time setup shows this weird message:

`DOTween is now setup, two extra files were removed`

Unity 5.6.3f1
DOTween 0.9.690

**Comment by Demigiant** [comment]
The setup message is correct, if as I assume you're using the Pro and don't have 2D Toolkit and TextMesh Pro installed (in which case the relative files for those are removed).

That said, this is very weird. Can you check your DOTween folder and see if you have 2 files named DOTween46? Also, can you confirm you're using the Pro?

**Comment by netlander** [comment]
Managed to solve the problem suddenly after a Unity restart.
Thanks for your support.

**Comment by Demigiant** [comment]
Crazy Unity :O But glad you solved it!

**Comment by oismaelash** [comment]
It seems you didn't run DOTween's setup, because you're missing the DOTween46.dll. You can find it under "Tools > Demigiant > DOTween Utility Panel".

Regards,

**Comment by leeprobert** [comment]
I am seeing this issue. Restart didn't help.

**Comment by mberthaud** [comment]
[https://issuetracker.unity3d.com/issues/image-color-cannot-be-changed-via-script-when-image-type-is-set-to-simple](url) it might be this issue that unity has right now i recently also ran into an issue like this but im positive not it is not dotween but this unity bug that is causing the issue

**Comment by fax1ty** [comment]
@Demigiant 
I'm not sure, but the UI-related functionality doesn't work on 2020.1
`DoTween.To(Color, Color, float, float)`, `DoTween.ToAlpha()`, `image.DoFade(float, float)`, `image.DoColor(...)`, `text.DoFade` and `text.DoColor`. There are no errors. The alpha value just doesn't change.
Is this a known problem, or is it just for me?

For now, I use the built-in [`.CrossFadeAlpha()`](https://docs.unity3d.com/2018.1/Documentation/ScriptReference/UI.Graphic.CrossFadeAlpha.html) function. Works as it should.

**Comment by Demigiant** [comment]
Ahoy,

I just installed 2020.1.0a and DOFade works correctly both on Image and CanvasGroup. Are you sure there's not something else happening?

**Comment by matthewhxq** [comment]
@fax1ty 
I just got the same problem on Unity 2020.1. I manage to fix it by adding asmdef files to DoTween and then referencing them in my own asmdef.

**Comment by 4bitanimationstudio** [comment]
I had the same problem on Unity 2019.4.5f1, I solved by updating Visual Studio Code Editor Package to version 1.2.3

**Comment by alex-gareau** [comment]
Got the same error on my side with Unity 2020.2.7f1. Everything else work fine, but just cannot add a DOFade to a canvas group.

**Comment by szantner** [comment]
Got the same error with Unity 2021.1.3f1

**Comment by Algerator** [comment]
Got the same error, in our case was due to using Assembly Definitions in our project and not referencing DOTween's Assemblies as dependencies. The discussion on this issue gave me the answer: #264 

We missed them because they are not generated by default; to generate DOTween's Assembly Definitions, open the DOTween Control Panel (_Tools/Demigiant/DOTween Utility Panel_) and in the _Setup_ tab, press the _Create ASMDEF_ button.
![image](https://user-images.githubusercontent.com/3844236/115539427-42402f80-a29d-11eb-8e0b-c1b4da7a91b1.png)

Now you can reference both _DOTweenPro.Scripts.asmdef_ and _DOTween.Modules.asmdef_ to your Assembly Definitions :)
![image](https://user-images.githubusercontent.com/3844236/115539461-4b310100-a29d-11eb-9e96-20a91bbaea93.png)

**Comment by KasperGameDev** [comment]
2020.3.14f1 cant get it to work :(

**Comment by Demigiant** [comment]
For whom it's not working yet, did you check the solutions above? Probably it's one of these:

1. Your code is inside a custom DLL and you haven't created and referenced the DOTween ASMDEFs from within your DLL
2. You're using a scale of 0-100 instead of 0-1 for alpha
3. You haven't run DOTween's setup and enabled the UI modules

Let me know

**Comment by KasperGameDev** [comment]
Hey Demigiant/dotween it was working and out of the blue it stopped, don't
know why it no longer work :/ all the other DOMove works fine.

**Comment by Demigiant** [comment]
But what changed, you installed the new update that I released yesterday? If so maybe you didn't recreate the ASMDEFs, or didn't enable the UI modules from the setup? Here it's working so I'm thinking of those possible problems, but if something else changed let me know

**Comment by KasperGameDev** [comment]
all i did was i delete the DOFade as i want to move it, and after it didn't
work, it say it don't have DOFade but I can get a lot of the other
functions as DOFlip and so on.
but i will try the ASMDEFsto day.

**Comment by KasperGameDev** [comment]
did not do the ASMDEFsto but now out of the blue it works donno how.
BTW I want to save Thanks and Good job DOtween have saved me so much time
so Thank you!

**Comment by Demigiant** [comment]
Oh, magic (and thanks for the nice words) \o/ Are you by any chance using Visual Studio Code? I heard that sometimes that can go crazy

**Comment by KasperGameDev** [comment]
no i use visual studio community, but i have visual studio code installed.
if i get the bug one more time i try to uninstall visual studio code and
see if it helps if it does i email you.

**Comment by KasperGameDev** [comment]
ok Error is back the fun.
[image: image.png]

1. as you can see it can find another DG.Tweening fine.
2. it says it doesn't have it out of the blue now.

**Comment by burkard** [comment]
was having this error too...

just add "f" (float) after the numbers, and the error is gone. :)

BEFORE: 
`mensagemToqueParaIniciar.GetComponent<CanvasGroup>().DOFade(1.0, 2.0);`

AFTER (working):
`mensagemToqueParaIniciar.GetComponent<CanvasGroup>().DOFade(1.0f, 2.0f);`

**Comment by Nyankoo** [comment]
> was having this error too...
> 
> just add "f" (float) after the numbers, and the error is gone. :)
> 
> BEFORE: `mensagemToqueParaIniciar.GetComponent<CanvasGroup>().DOFade(1.0, 2.0);`
> 
> AFTER (working): `mensagemToqueParaIniciar.GetComponent<CanvasGroup>().DOFade(1.0f, 2.0f);`

This sadly doesn't work for me.

Error came out of nowhere. The day before, everything worked but suddenly, the error shows up. Project compiles in Unity successful, only VS has issues.

**Comment by KasperGameDev** [comment]
Thanks for the info m8

**Comment by claudito1991** [comment]
Hi there i'm on 2020.3.28f1 and my DOTween version is v1.2.632 i have this code 
correctImage.DOFade(1, 0.5f); 
that was working, when i reload scripts it now says that the method can't be applied to the image object. I don't know what happened. I tried reloading, re doing the setup and creating the ASMDEF but it didn't work

**Comment by fred-rock** [comment]
Hi, Just to add another instance of the bug, I'm using Unity 2020.3.20f1 with DOTween version v.1.2.632 and this error just surfaced for me, also out of the blue. I've tried the above methods to fix it and have not been able to remove the errors in VS. However, Unity compiles and the function works just fine in play mode.

**Comment by KasperGameDev** [comment]
somehow I fixed it by reimportin all on the Assets folder

**Comment by Chai-Li** [comment]
you can try to delete you Visual Studio hidden folder ".vs" in you project , the reason why is Visual Studio cant Identify macro ,such as (UNITY_4_6 || UNITY_5 || UNITY_2017_1_OR_NEWER)  in DOTweenModuleUI.cs

**Comment by m-dastagir** [comment]
For me the issue was different. I was receiving the same error, however it was this that was not working:
```
canvasGroup.DOFade(0.0f, 0.25f);
```
and because of the decimal in the first place, I changed it to this and it worked:
```
canvasGroup.DOFade(0f, 0.25f);
```

**Comment by SeungHuLee** [comment]
@Chai-Li 's answer is the real solution to this problem. Try deleting .vs hidden folder and re open visual studio.

**Comment by Volorf** [comment]
Had the same issue. Autocompletion didn't show the DOFade option (I use Rider). 

Context: The call of the method was in a script with a namespace and an assembly definition. 

@Algerator's piece of advice helped to fix this issue for me https://github.com/Demigiant/dotween/issues/154#issuecomment-823958565

**Comment by 9Hamza** [comment]
Didn't work for me -> `canvasGroup.DOFade(0f, 0.2f);`
Worked for me -> `canvasGroup.DOFade(0f, 0.2f).Play();`
