### ISSUE TITLE
Feature Request: VideoPlayer Alpha

### ISSUE THREAD

**Issue by vicenterusso** [Demigiant/dotween#156]
Something like `.DOFade` to tween the `VideoPlayer.targetCameraAlpha` property.

**Comment by Demigiant** [comment]
Hi,
When there's a missing shortcut, you can always use the generic method:

`DOTween.To(()=> vid.targetCameraAlpha, x=> vid.targetCameraAlpha = x, 0.5f, 1);`

Cheers,
Daniele
