### ISSUE TITLE
Cannot build iOS 64bit with DOTween pro and Unity 2017.1.1f1

### ISSUE THREAD

**Issue by Culzean** [Demigiant/dotween#158]
I'm trying to make a build to iOS with IL2CPP compiler but am encountering this error.

IL2CPP error for method 'System.Void DG.Tweening.DOTweenPath::DORestart(System.Boolean)' in D:\DG\_Develop\__UNITY3_CLASSES\_Holoville\__DOTween\_DOTween.Assembly\DOTweenPro\DOTweenPath.cs:221
Additional information: Object reference not set to an instance of an object.

I cannot complete the build. I have DOTween v1.1.640 and DOTween Pro v0.9.470

I got these errors on setting up the latest version of DOTween, they might be related.

PlayerSettings Validation: Requested build target group (15) doesn't exist; #define symbols for scripting won't be added.
PlayerSettings Validation: Requested build target group (16) doesn't exist; #define symbols for scripting won't be added.

I also have TextMeshPro 1.0.55.xx.0b12 installed that way be causing a conflict.

**Comment by Demigiant** [comment]
Hi,

Can you update to the latest DOTween Pro version (0.9.690) and let me know if this still happens?

Cheers,
Daniele

**Comment by Culzean** [comment]
That sorted the build thanks. Sorry, I thought I had updated to the latest version.

**Comment by Demigiant** [comment]
Glad it's fixed :)
