### ISSUE TITLE
DOColor infinite yoyo loop?

### ISSUE THREAD

**Issue by andrelevi** [Demigiant/dotween#161]
Hi,

I'm trying to infinite loop a color change from white to red to white, etc.

Here is my code:

```
            _renderer.material.color = Color.white;
            _renderer.material.DOColor(Color.red, 0.5f)
                .SetLoops(-1, LoopType.Yoyo);
```

Am I doing something wrong? From what I understand, yoyo loops rewind the tween to its original value after tweening to the target value. Am I misundertanding what yoyo loops do?

Thanks!

**Comment by Demigiant** [comment]
Hi Andre,

That is totally right, but what is happening in your case instead? If the
animation never happens, then that should mean that your material's shader
doesn't have a color property. But if instead it animates to red and then
doesn't go back I would be very puzzled (unless you killed the tween
somewhere else). Let me know :)

Cheers,
Daniele

**Comment by andrelevi** [comment]
Hi Daniele,

Sorry, you're totally right. I was killing the tween somewhere else.

Thanks for your help!

**Comment by Demigiant** [comment]
Glad it's solved :)
