### ISSUE TITLE
Sequences generate GC allocations (introduced recently)

### ISSUE THREAD

**Issue by Demigiant** [Demigiant/dotween#17]
As the title says. I'm on it.

**Comment by alryazanov** [comment]
Hi! There is progress on this issue?

**Comment by Demigiant** [comment]
Update (since someone made me notice that this is still marked as an issue, since I forgot to unmark it, apologies for that).

This has been solved a while ago. Creating a new Sequence obviously will generate GC, but if you activate recycling no more GC will be allocated when an unused Sequence can be re-used.
