### ISSUE TITLE
ChangeEndValue failing silently

### ISSUE THREAD

**Issue by matthias-t** [Demigiant/dotween#171]
It looks like Tweener.ChangeEndValue is failing silently<sup>1</sup> when an unsupported value is passed.

How to reproduce:

    Tweener tweener = transform.DOScale(5f, duration: 5f);
    yield return new WaitForSeconds(2.5f);
    tweener.ChangeEndValue(0f, true);

This is especially confusing with scale tweens because of the single-value shortcut.
I took a look at TweenerCore.cs and understood [why you can't use generics](https://docs.unity3d.com/Manual/ScriptingRestrictions.html#AOT), but shouldn't it at least throw an Exception [(here)](https://github.com/Demigiant/dotween/blob/5f28d4bba85fe6b985687c1ac07ead00c7f5c070/_DOTween.Assembly/DOTween/Core/TweenerCore.cs#L84)?

For future reference: `tweener.ChangeEndValue(new Vector3(0f, 0f, 0f), true);` is the way to go.

<sup>1</sup>: Changing the _Log Behaviour_ from the default (_Errors Only_) to _Verbose_ will make it show a warning.

**Comment by Demigiant** [comment]
I changed the default LogBehaviour of DOTween to Default (so it will show both errors and warnings). Coming in the next update :P
