### ISSUE TITLE
Twice OnComplete() called when calling Complete() in OnUpdate()

### ISSUE THREAD

**Issue by zjm249926195** [Demigiant/dotween#172]
Version: DOTween v1.1.640
Here's my testing code:
```
int x = 0;
Tween t = DOTween.To(() => { return x; }, val => { x = val; }, 1, 2);
t.OnUpdate(() =>
{
    t.Complete();
}).OnComplete(()=>
{
    Debug.Log("Complete");
});
```
I viewed the source code and found out the problem probably in DG.Tweening.Tween.DOGoto() method.
There's a declaration `"bool flag2 = t.isComplete;"` to mark whether the tween is completed, and after a few lines it calls 
```
if (t.onUpdate != null && updateMode != UpdateMode.IgnoreOnUpdate)
{
    Tween.OnTweenCallback(t.onUpdate);
}
```
which would call `t.Complete();`  and invoke `Tween.OnTweenCallback(t.onComplete);`in my testing code.
So here's the problem, the "onComplete" callback is called in "onUpdate" by calling "t.Complete();", but the "flag2" is still false, which means it's still satisfied the condition and would call "onComplete" once more.
```
if (t.isComplete && !flag2 && t.onComplete != null)
{
    Tween.OnTweenCallback(t.onComplete);
}
```
Due to my limited expression, I'd like to give you a picture with instructions.
![oncomplete_called_twice](https://user-images.githubusercontent.com/20531994/33226526-e5d0b2de-d1ca-11e7-86bc-6681e1090cd7.png)

Looking forward to your reply!
PS: DOTween is really a nice plugin! :)
@Demigiant

**Comment by zjm249926195** [comment]
Come on! Anybody has a clue?

**Comment by Demigiant** [comment]
Ahoy!

I know this is taking a while, but please give me another couple days at least. I tried to investigate this but it's a rather edge case which requires delicate changes in order to avoid breaking stuff. I tried last week, but realized I need to invest quite some time on it, and I planned tomorrow/Tuesday.
P.S. thanks for the references and the code check! That did help me a lot, but it's still very delicate :P

**Comment by zjm249926195** [comment]
Hah, I'm not in a hurry, so take your time! It's my first time to open an issue for a well-known plugin and I'm  a little bit excited. Sorry for that! :P

**Comment by Demigiant** [comment]
Ah, I understand :P I'm working on this since a while today, but it's rather messy. I could solve it easily by adding a variable to the Tween object, but I don't want to, because I try not to add variables (to keep things as lightweight as possible) unless it's reeeeally necessary. Gonna insist a little more.

**Comment by Demigiant** [comment]
Ok I had a good idea finally, which seems to have worked. Grab this new [version 1.1.685](http://dotween.demigiant.com/tmp/DOTween_1_1_685.zip) and please let me know if everything works on your side.

**Comment by zjm249926195** [comment]
It does work as expected! But there's one more "Update()" call in my testing code, does it matter?
Testing code:
```int num = 0;
Tween t = DOTween.To(() => { return num; }, x => { num = x; }, 1, int.MaxValue);
t.OnUpdate(() =>
{
    Debug.Log("Update");
    if (Input.GetMouseButtonDown(1))
    {
        t.Complete();
    }
}).OnComplete(() =>
{
    Debug.Log("Complete");
});
```
![tim 20171205132945](https://user-images.githubusercontent.com/20531994/33591445-967c1aa4-d9c0-11e7-8a35-b6f4bd619dac.png)

**Comment by Demigiant** [comment]
That is correct and by design. OnUpdate is called every time the tween position (and thus your target's value) changes. Since you called Complete from within an incomplete tween, OnUpdate should be called again before OnComplete.

**Comment by zjm249926195** [comment]
Well, I get it! Thank you so much for your patient help :)

**Comment by Demigiant** [comment]
A pleasure! :)
