### ISSUE TITLE
DOTween DOPath behave weird after 5-10mins running on Android devices

### ISSUE THREAD

**Issue by NguyenVietPhu2207** [Demigiant/dotween#177]
Hello, I'm Phu - an Unity game developer. I'm very interested in with your DOTween lib, which help me so much. But today I notice that there's something very weird ruined my project :( Normally, I move my game objects (fishes) by using DOPath, pass in my path array and it works well. But when I build to Android and play about 5-10 minutes, the fishes start to behave weird while all others part of my game still work normally (please take a look to the short video I recorded in this link because I can't describe this problem by words : https://drive.google.com/open?id=1i1HgdqAXAtWYndbPHz58cx46-k5DU9Zq ). Have you ever seen this problem before, or do you have any limit in free version of DOTween. Note that I'm using DOTween v1.1.640 with Unity 5.5.5f1 (64bit).
Many thanks for your help.

Thanks and regards,
Phu.

**Comment by Demigiant** [comment]
Hi,
I answered your mail, let's continue there. Cheers.
