### ISSUE TITLE
How to rotate 360 degrees

### ISSUE THREAD

**Issue by mrtenda** [Demigiant/dotween#179]
I'd like to rotate a Transform by 360 degrees using DOTween to make it spin, but I can't figure out the proper way to do this according to the documentation. What would be the best way to do this? Thanks!

**Comment by Demigiant** [comment]
Ahoy!
You would need to set RotateMode.FastBeyond360 as DORotate parameter (so the tween doesn't use the shortest route) and then chain a SetRelative() to tell it to rotate "by" instead of "to" :)

**Comment by shanukp** [comment]
how to make it uniform rotation?

**Comment by shanukp** [comment]
i meant the speed

**Comment by Demigiant** [comment]
If you want a uniform speed you should set a Linear ease via:
`myTween.SetEase(Ease.Linear);`

**Comment by fguillen** [comment]
So, for the blockhead as me: 

```
transform.DOLocalRotate(new Vector3(0, 0, 360), time, RotateMode.FastBeyond360).SetRelative(true).SetEase(Ease.Linear)
```

**Comment by Qwertyboyjulian** [comment]
need continuous rotation, no time limit. How to achieve it ?

**Comment by BernardMasika** [comment]
> need continuous rotation, no time limit. How to achieve it ?

chain a SetLoops(-1), -1 for infinity. like this;

`transform.DORotate(new Vector3(360, 0, 0), 1f, RotateMode.FastBeyond360).SetRelative(true)
           .SetEase(Ease.Linear).SetLoops(-1);`
