### ISSUE TITLE
Kill Tween if object is null (Destroyed)

### ISSUE THREAD

**Issue by MinhajJaved** [Demigiant/dotween#181]
DOTween should kill the tweener if the object it is running on is null (Destroyed before tween ends), because in many scenarios the object has no script on it but it has reference in other script and that script plays the tween. If you want more description let me know. Thanks

**Comment by Demigiant** [comment]
That is what safe mode does :P Without it though it's up to you to manage correctly when objects are destroyed (thus killing tweens and removing any other dependencies to it).
