### ISSUE TITLE
OnComplete run on creation

### ISSUE THREAD

**Issue by addie-lombardo** [Demigiant/dotween#191]
Hey! I've encountered an issue using DoTween v1.1.695 (Pro  0.9.690) in Unity 2017.3.1f1 where OnComplete is run after the code is run and will not wait for the tween to be completed. I do have other tweens which I don't believe have this issue however so perhaps it is only for DoTween.To?

![](https://i.imgur.com/MkGOOU0.png)

The code is part of a demo for GDC which is a week away so any help is greatly appreciated solving the issue.

**Comment by Demigiant** [comment]
Agh, saw this only now. Gonna test it immediately, it sounds very weird.

**Comment by Demigiant** [comment]
I can't reproduce it. Emulating your code works perfectly here. The only case in which OnComplete is called in the same frame as the tween creation is if you pass a duration of 0. Is it possible that's what's happening?

**Comment by addie-lombardo** [comment]
I believe I found the issue! One of our scripters reversed the commands calling the tween and so it was called immediately. Apologies!

**Comment by Demigiant** [comment]
Glad it's solved :)
