### ISSUE TITLE
Text.DOFade() doesn't work with <color> rich text tag

### ISSUE THREAD

**Issue by leoncvlt** [Demigiant/dotween#192]
I have got a Text object with the text:
```
<b><color=#559AFEFF>Start position</color></b>: 
This item can be observed throughout the test and can be observed in any position.  An initial period of observation in supine should be completed with the child in an alert awake state.  
```

When I call `DOFade()` on it to make it fully transparent, the first line doesn't fade. If I remove the `<color>` tag from it, it works fine. I tried removing the transparency bits from the tag, making it `<color=#559AFE>`, but it still doesn't work.

**Comment by Demigiant** [comment]
Hi,

Fade acts on the text's color property and doesn't deal with tags at all, so as long as you can change the alpha property of the main color manually, it will work also when tweened. Consider that I use it often with colored text tags and I can confirm that the generale DOFade color property works correctly, except if you set the alpha directly in the tag as you did in the first case. I'd recommend checking that you don't have a leftover alpha in the tag.

**Comment by breban1** [comment]
I'm having this problem using the DOTweenAnimation script in the inspector with COLOR set as the component on a Text object with the <color> tags.  Is there a way to do this?  Basically I have yellow text ,then white text after it, and want to fade to alpha 0.  "<color=#FFFF00>yellow</color> <color=#FFFFFF>white</color>"

**Comment by Demigiant** [comment]
Ahoy!

I just realized my previous answer was related to TextMeshPro texts, not normal UI Texts, sorry. I would recommend to use TextMeshPro (much more powerful, and color alpha also influences tags), but otherwise you could place your Text inside a parent that contains a CanvasGroup and use the Fade on the CanvasGroup itself (which will work also on colored tags of normal Text components in that case).

**Comment by breban1** [comment]
Thanks so much for the info!  I am using TextMeshPro, purchased from the
Unity Asset store.

I will try the Canvas group and see how it goes!

Brian

**Comment by breban1** [comment]
Oh, sorry, I thought you said DOTween PRO, not TextMeshPro!

I am using normal text objects, along with DOTween PRO.  And guess what?
The Canvas Group worked like a charm!!!  Thanks SO much for helping me out,
I didn't even know Canvas Groups existed!

DOTween for the win!

Brian

**Comment by Demigiant** [comment]
Ah cool! I was getting confused and was planning a TextMesh Pro test in a short while :D Glad it works and that you discovered CanvasGroups, they're awesome! Very convenient also in case you want to disable all buttons inside a group, other than for fading tons of elements together :)

**Comment by breban1** [comment]
SO sorry about the confusion, totally my fault!

While I have you (no rush), another question - unrelated.

Is there a way to have a looping DOTween (scale in this case), that
includes the Delay every time it loops?

Here is what I have:
Duration 1
Delay 1
Loops -1
Loop Type Restart

I want: Delay(1), Play(1), Delay(1), Play(1)... rinse, repeat.

With this setup, it delays 1 second (Delay), then plays the animation for 1
second (Duration), but then when it loops, it doesn't do the delay again,
just the Duration.  Am I missing something, or is this something I must do
in an OnComplete() or something?

Thanks again for your help!

Brian

**Comment by breban1** [comment]
I figured it out, it is OnStep, that wasn't obvious that it's at the end of
ever loop.

Nothing to see here!

Thanks again,
Brian
