### ISSUE TITLE
OnComplete does not work for Sequence which setLoops(-1)...

### ISSUE THREAD

**Issue by leorocku** [Demigiant/dotween#199]
public class TestKillSequenceOnCompleted : MonoBehaviour {

    public GameObject Cube;

    private void Start()
    {
        Sequence cubSeq = DOTween.Sequence();
        cubSeq.Append(Cube.transform.DOMoveZ(5, 2.0f));
        cubSeq.Append(Cube.transform.DOMoveZ(0, 2.0f));
        //cubSeq.SetLoops(-1); //if SetLoops(-1) ,OnComplete() will not be triggered. 
        cubSeq.OnComplete( () => {Debug.Log("Cub Complete");});

        StartCoroutine(KillDelay(cubSeq, 3.0f));

    }

    IEnumerator KillDelay(Sequence seq, float delay)
    {
        yield return new WaitForSeconds(delay);

        Debug.Log("Kill");
        seq.Kill(true);
    }

}

**Comment by Decavoid** [comment]
https://github.com/Demigiant/dotween/issues/64

**Comment by leorocku** [comment]
Thanks
