### ISSUE TITLE
IndexOutOfRangeException: Array index is out of range

### ISSUE THREAD

**Issue by Demigiant** [Demigiant/dotween#2]
Original from pavel.oliferovskiy on Google Code ([Issue 32](https://code.google.com/p/dotween/issues/detail?id=32&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary)):
> Hello! I have this exception 
in 1.0.030 DOTween 
in Unity 5 Version 5.0.0f4 (5b98b70ebeb9)
This happens in my method MyMethod in this order 

> ```c#
MyMethod () // workds
// one gazillion other tweens
// some time
DOTween.Clear(true)
MyMethod () // crashes

> IndexOutOfRangeException: Array index is out of range.
(wrapper stelemref) object:stelemref (object,intptr,object)
DG.Tweening.Core.TweenManager.AddActiveTween (DG.Tweening.Tween t) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween.Assembly/DOTween/Core/TweenManager.cs:661)
DG.Tweening.Core.TweenManager.GetTweener[Single,Single,FloatOptions] () (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween.Assembly/DOTween/Core/TweenManager.cs:95)
DG.Tweening.DOTween.ApplyTo[Single,Single,FloatOptions] (DG.Tweening.Core.DOGetter`1 getter, DG.Tweening.Core.DOSetter`1 setter, Single endValue, Single duration, DG.Tweening.Plugins.Core.ABSTweenPlugin`3 plugin) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween.Assembly/DOTween/DOTween.cs:785)
DG.Tweening.DOTween.To (DG.Tweening.Core.DOGetter`1 getter, DG.Tweening.Core.DOSetter`1 setter, Single endValue, Single duration) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween.Assembly/DOTween/DOTween.cs:228)
GameInsight.uGui.PreloaderLogo..ctor (UnityEngine.UI.Image image) (at Assets/_Develop/code/GameInsight/uGui/PreloaderLogo.cs:17)
```

**Comment by Demigiant** [comment]
# Fixed in v1.0.336

I finally managed to reproduce this issue, after a lot of tries. Then it took me 5 minutes to fix it, whew :)

**Comment by sandygk** [comment]
I am having a similar issue. I am using DOTween all over my project and I am getting this error with the last version (V 1.0.720) this is the error I am getting

IndexOutOfRangeException: Array index is out of range.
DG.Tweening.Core.TweenManager.RemoveActiveTween (DG.Tweening.Tween t) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:790)
DG.Tweening.Core.TweenManager.Update (UpdateType updateType, Single deltaTime, Single independentTime) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:401)
DG.Tweening.Core.DOTweenComponent.Update () (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:50)

the error pointe me to this line of code:

private void Disappear()
{  
     _spriteRenderer.DOFade(0, _fadeTime).OnComplete(Deactivate);  // <-----
}

I am also getting this error which points me to the DOTween object in the scene

IndexOutOfRangeException: Array index is out of range.
(wrapper stelemref) object:stelemref (object,intptr,object)
DG.Tweening.Core.TweenManager.ReorganizeActiveTweens () (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:768)
DG.Tweening.Core.TweenManager.Update (UpdateType updateType, Single deltaTime, Single independentTime) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:325)
DG.Tweening.Core.DOTweenComponent.Update () (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:50)

**Comment by Demigiant** [comment]
This really shouldn't be happening anymore, damn. Can you paste me the Deactivate method body? There is probably something there.

P.S. note that you can fix this error by using [SetTweensCapacity](http://dotween.demigiant.com/documentation.php?api=SetTweensCapacity) to set the capacity already high enough that it won't need to be changed automatically. But if you can help me identity this issue it would be great.

**Comment by jmp909** [comment]
I'm still getting this.

happened when I reloaded my scene

```C#
private void ShowLogos()
{
    logos.SetActive(true);
    logosSpriteRenderer.DOFade(1, 1);
}
```

```C#
IndexOutOfRangeException: Array index is out of range.

at DG.Tweening.Core.TweenManager.GetTweener[Color,Color,ColorOptions] () [0x00037]  in D:\DG\_Develop\__UNITY3_CLASSES\_Holoville\__DOTween\_DOTween.Assembly\DOTween\Core\TweenManager.cs:65 

at DG.Tweening.DOTween.ApplyTo[Color,Color,ColorOptions] (DG.Tweening.Core.DOGetter`1 getter, DG.Tweening.Core.DOSetter`1 setter, Color endValue, Single duration, DG.Tweening.Plugins.Core.ABSTweenPlugin`3 plugin) [0x00005] 
in D:\DG\_Develop\__UNITY3_CLASSES\_Holoville\__DOTween\_DOTween.Assembly\DOTween\DOTween.cs:995 

at DG.Tweening.DOTween.ToAlpha (DG.Tweening.Core.DOGetter`1 getter, DG.Tweening.Core.DOSetter`1 setter, Single endValue, Single duration) [0x00000] in D:\DG\_Develop\__UNITY3_CLASSES\_Holoville\__DOTween\_DOTween.Assembly\DOTween\DOTween.cs:445 
  at DG.Tweening.ShortcutExtensions43.DOFade (UnityEngine.SpriteRenderer target, Single endValue, Single duration) [0x0000d] in D:\DG\_Develop\__UNITY3_CLASSES\_Holoville\__DOTween\_DOTween.Assembly\DOTween43\ShortcutExtensions43.cs:84 
  at MainController.ShowLogos (Boolean immediate) [0x0002f] in C:\dev\test\Assets\_Project\Scripts\Singletons\MainController.cs:375 
```
