### ISSUE TITLE
New version update?

### ISSUE THREAD

**Issue by optimisez** [Demigiant/dotween#204]
Hi @Demigiant.  I see there is no DOTween Pro new version update at Asset Store since Aug 29, 2017. Any plan to update it? Or is there any other way to get new version?

**Comment by Demigiant** [comment]
Ahoy,

I did many updates to the core of DOTween, and that also updates the Pro. You can download [from here](http://dotween.demigiant.com/download.php) :) That said, I have a new Pro update in the works, but I have no release date yet.
