### ISSUE TITLE
sometimes Sequence function cause cpu spike

### ISSUE THREAD

**Issue by nick-yangzj** [Demigiant/dotween#205]
unity version:2017.4.3
Dotween's version is the 1.1.710

Sometimes DOTween.Sequence() will cause cpu spike:
![2018-05-17 6 15 14](https://user-images.githubusercontent.com/6884541/40171728-b86b5dbe-59fe-11e8-97ff-4bf82055c9e9.png)

Most time is Ok, like the following pic:
![2018-05-17 6 16 07](https://user-images.githubusercontent.com/6884541/40172184-336ed3e6-5a00-11e8-83e9-57b4c444e229.png)

my code is like that:
`DOTween.Sequence().Append(isMoveX ? _transParent.DOLocalMoveX(next, duration).SetEase(Ease.Linear) : _transParent.DOLocalMoveZ(next, duration).SetEase(Ease.Linear))
                .Insert(0, isMoveX ? _transParent.DOLocalMoveZ(nextPos.z, duration) : _transParent.DOLocalMoveX(nextPos.x, duration))
                .Insert(0, _transParent.DOLocalMoveY(1.2f, halfDuration).SetEase(Ease.OutQuad))
                .Insert(halfDuration, _transParent.DOLocalMoveY(0.66f, halfDuration).SetEase(Ease.InQuad))
                .Insert(0, isMoveX ? _transParent.DOLocalRotate(new Vector3(0, 0, -180), halfDuration, RotateMode.LocalAxisAdd).SetEase(Ease.Linear) : _transParent.DOLocalRotate(new Vector3(180, 0, 0), halfDuration, RotateMode.LocalAxisAdd).SetEase(Ease.Linear))
                .Insert(halfDuration, isMoveX ? _transParent.DOLocalRotate(new Vector3(0, 0, -180), halfDuration, RotateMode.LocalAxisAdd).SetEase(Ease.Linear) : _transParent.DOLocalRotate(new Vector3(180, 0, 0), halfDuration, RotateMode.LocalAxisAdd).SetEase(Ease.Linear));`
`DOTween.Sequence().Append(transform.DOScale(new Vector3(0.8f,0.8f,1.2f),quartDuration))
                .Append(transform.DOScale(new Vector3(1.3f,1.3f,0.85f),quartDuration))
                .Append(transform.DOScale(Vector3.one,halfDuration)).OnComplete(CheckStatus);`

**Comment by jmp909** [comment]
hi @nick-yangzj,

not sure if that's the original layout of your code, but I would write it something like this to make it easier for people to debug.

just a suggestion anyway... 

those 200,000 calls look like a problem clearly, but i'll have to leave that to @Demigiant to advise on that one

```C#
// -----------------------------------------------------------------------------

DOTween

    .Sequence()

    .Append
    (
        isMoveX ? _transParent.DOLocalMoveX(next, duration).SetEase(Ease.Linear)
                : _transParent.DOLocalMoveZ(next, duration).SetEase(Ease.Linear)
    ) 

    .Insert 
    (
        0, 
        isMoveX ? _transParent.DOLocalMoveZ(nextPos.z, duration) 
                : _transParent.DOLocalMoveX(nextPos.x, duration)
    ) 

    .Insert 
    (
        0, 
        _transParent.DOLocalMoveY(1.2f, halfDuration).SetEase(Ease.OutQuad)
    ) 

    .Insert 
    (
        halfDuration, 
        _transParent.DOLocalMoveY(0.66f, halfDuration).SetEase(Ease.InQuad)
    )

    .Insert 
    (
        0, 
        isMoveX ?

                _transParent.DOLocalRotate 
                (
                    new Vector3(0, 0, -180), 
                    halfDuration, 
                    RotateMode.LocalAxisAdd
                )
                .SetEase(Ease.Linear) 

                :   

                _transParent.DOLocalRotate
                (
                    new Vector3(180, 0, 0),
                    halfDuration, 
                    RotateMode.LocalAxisAdd
                )
                .SetEase(Ease.Linear)
    )

    .Insert
    (
        halfDuration, 
        isMoveX ?   

                _transParent.DOLocalRotate
                (
                    new Vector3(0, 0, -180), 
                    halfDuration, 
                    RotateMode.LocalAxisAdd
                )
                .SetEase(Ease.Linear) 

                :   

                _transParent.DOLocalRotate
                (
                    new Vector3(180, 0, 0), 
                    halfDuration, 
                    RotateMode.LocalAxisAdd
                )
                .SetEase(Ease.Linear)
    );

// -----------------------------------------------------------------------------

DOTween

    .Sequence ()
    
    .Append 
    (
        transform.DOScale
        (
            new Vector3(0.8f,0.8f,1.2f), 
            quartDuration
        )
    ) 

    .Append 
    (
        transform.DOScale
        (
            new Vector3(1.3f,1.3f,0.85f),
            quartDuration
        )
    ) 

    .Append 
    (
        transform.DOScale
        (
            Vector3.one,
            halfDuration
        )
    )

    .OnComplete(CheckStatus);

// -----------------------------------------------------------------------------
```

**Comment by Demigiant** [comment]
Thanks @jmp909 for making the code readable :)

@nick-yangzj Sequences shouldn't generate spikes, unless it's the very first time you run a tween (or type of) and thus the tween plugins have to be created and initiated for the very first time. Is that the case? I assume so, because I see 217k GC allocations, and tweens don't generate allocations per-frame, so it seems that's the frame where you're creating 217K tweens for the first time. Let me know.
