### ISSUE TITLE
Why is the Dotween animation (pro) still working when an object is disabled ?

### ISSUE THREAD

**Issue by alaslipknot** [Demigiant/dotween#206]
Hello,

I just bought Dotween pro today and noticed this behavior [Gif](https://imgur.com/a/hQ5Twv7), 
i know this can be useful in some cases but in mine its a bit scary, i have an essential concern about this, since am making a mobile game, will all the object that contain a Dotween be running their animation once its disabled ? will this force me to Destroy inactive object.

I really hope this is just an Editor thing because if not it's gonna be a huge problem, but even if it is, is there a way to disable it ? when i disable an object in Play mode (specially when testing) it means that i don't wanna see it nor its Gizmos, currently if a Dotween path played once, the object path will ALWAYS be drawn on the screen even when its disabled.

Thanks

**Comment by Demigiant** [comment]
Ahoy,

Indeed, even if you disable an object, the animations continue playing because they're not tied to their target's visibility, but you can add a DOTweenManager (using the topmost button in the animation Inspector) and choose the type of behaviour when a target is enabled/disabled.

Cheers

**Comment by alaslipknot** [comment]
> using the topmost button in the animation Inspector

Sorry but am lost there :p can you post a screenshot please ?

nevermind... 
i found it (didn't sleep for 20 hours lol)

Thanks!

**Comment by Demigiant** [comment]
Ah, too late, I did the screenshot :D

![pro_manager](https://user-images.githubusercontent.com/8322877/40231689-5b15dcea-5a9c-11e8-94f1-a998d68e5b79.png)

**Comment by alaslipknot** [comment]
haha no worries, thanks a lot for the great support :D 

offtopic thing please (i can create a new topic if you want) 

I want to know if there is a "pre-made" way to make an object follow path on demand ?
say i create an empty object and add a DoTween Path script, i setup that script like i want it to behave, and then when a total different object collide with the "path object", then the different object will follow the path.

The easiest way i can think of is make the new object a child of the path object and just start the path animation, but am wondering if you have a "better" method for that already ?

Thanks again!

**Comment by Demigiant** [comment]
Ah, in that case you could indeed set the object as a child, or you could grab the path waypoints from your DOTweenPath component (myDOTweenPath.wps), and use them to create a new tween via code (with [myTransform.DOPath](http://dotween.demigiant.com/documentation.php?api=DOPath__1)).

In your case, since you don't need to modify the path, I'd recommend using the child approach you thought of (unless you prefer not to change parents), because that way you're always reusing the same tween instead of creating a new one every time :)

**Comment by alaslipknot** [comment]
Awesome! thank you :D

**Comment by wedgiebee** [comment]
> Ahoy,
> 
> Indeed, even if you disable an object, the animations continue playing because they're not tied to their target's visibility, but you can add a DOTweenManager (using the topmost button in the animation Inspector) and choose the type of behaviour when a target is enabled/disabled.
> 
> Cheers

@Demigiant Is there a way to set this enabled/disabled behavior as a default for all tweens, including the ones that don't come from a DOTweenAnimation component?

**Comment by Demigiant** [comment]
For DOTweenAnimations you need to add a manager to each, but for code-based tweens you can use [SetLink](http://dotween.demigiant.com/documentation.php?api=SetLink), though that will still need to be applied on a one-on-one basis.
