### ISSUE TITLE
How to know tween complete when play tween with code DOTween.Play

### ISSUE THREAD

**Issue by havudk** [Demigiant/dotween#211]
Dear,

I usually play tween with code DOTween.Play(object)
Is there any way to know this tween is completed without set OnComplete in Inspector?

Thank you very much.

**Comment by Demigiant** [comment]
Ahoy!

You can ask a tween if it's complete by calling the [IsComplete](http://dotween.demigiant.com/documentation.php?api=IsComplete) info-method :)

Cheers

**Comment by Demigiant** [comment]
Ah, though that requires a reference to the tween. Otherwise you really need the OnComplete method callback.
