### ISSUE TITLE
DOTween Pro 0.9.690 caused errors in setup after importing TextMesh Pro.

### ISSUE THREAD

**Issue by ohbado** [Demigiant/dotween#212]
Versions:
DOTween Pro 0.9.690
TextMesh Pro 1.2.2
Unity 2017.4.3f1
Windows 8.1 64bit

Repro Steps:
Create new project.
Import TextMesh Pro.
Import DOTween Pro.
Run Setup DOTween.

Error Messages:
------
PlayerSettings Validation: Requested build target group (2) doesn't exist; #define symbols for scripting won't be added.
UnityEditor.PlayerSettings:SetScriptingDefineSymbolsForGroup(BuildTargetGroup, String)
DG.DOTweenEditor.Core.ProEditorUtils:AddGlobalDefine(String) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenProEditor/Core/ProEditorUtils.cs:23)
System.Reflection.MethodBase:Invoke(Object, Object[])
DG.DOTweenEditor.DOTweenSetupMenuItem:ProEditor_AddGlobalDefine(String) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenSetupMenuItem.cs:92)
DG.DOTweenEditor.DOTweenSetupMenuItem:Setup(Boolean) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenSetupMenuItem.cs:79)
DG.DOTweenEditor.DOTweenUtilityWindow:DrawSetupGUI() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenUtilityWindow.cs:180)
DG.DOTweenEditor.DOTweenUtilityWindow:OnGUI() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenUtilityWindow.cs:156)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

PlayerSettings Validation: Requested build target group (5) doesn't exist; #define symbols for scripting won't be added.
UnityEditor.PlayerSettings:SetScriptingDefineSymbolsForGroup(BuildTargetGroup, String)
DG.DOTweenEditor.Core.ProEditorUtils:AddGlobalDefine(String) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenProEditor/Core/ProEditorUtils.cs:23)
System.Reflection.MethodBase:Invoke(Object, Object[])
DG.DOTweenEditor.DOTweenSetupMenuItem:ProEditor_AddGlobalDefine(String) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenSetupMenuItem.cs:92)
DG.DOTweenEditor.DOTweenSetupMenuItem:Setup(Boolean) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenSetupMenuItem.cs:79)
DG.DOTweenEditor.DOTweenUtilityWindow:DrawSetupGUI() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenUtilityWindow.cs:180)
DG.DOTweenEditor.DOTweenUtilityWindow:OnGUI() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenUtilityWindow.cs:156)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

PlayerSettings Validation: Requested build target group (6) doesn't exist; #define symbols for scripting won't be added.
UnityEditor.PlayerSettings:SetScriptingDefineSymbolsForGroup(BuildTargetGroup, String)
DG.DOTweenEditor.Core.ProEditorUtils:AddGlobalDefine(String) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenProEditor/Core/ProEditorUtils.cs:23)
System.Reflection.MethodBase:Invoke(Object, Object[])
DG.DOTweenEditor.DOTweenSetupMenuItem:ProEditor_AddGlobalDefine(String) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenSetupMenuItem.cs:92)
DG.DOTweenEditor.DOTweenSetupMenuItem:Setup(Boolean) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenSetupMenuItem.cs:79)
DG.DOTweenEditor.DOTweenUtilityWindow:DrawSetupGUI() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenUtilityWindow.cs:180)
DG.DOTweenEditor.DOTweenUtilityWindow:OnGUI() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenUtilityWindow.cs:156)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

PlayerSettings Validation: Requested build target group (15) doesn't exist; #define symbols for scripting won't be added.
UnityEditor.PlayerSettings:SetScriptingDefineSymbolsForGroup(BuildTargetGroup, String)
DG.DOTweenEditor.Core.ProEditorUtils:AddGlobalDefine(String) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenProEditor/Core/ProEditorUtils.cs:23)
System.Reflection.MethodBase:Invoke(Object, Object[])
DG.DOTweenEditor.DOTweenSetupMenuItem:ProEditor_AddGlobalDefine(String) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenSetupMenuItem.cs:92)
DG.DOTweenEditor.DOTweenSetupMenuItem:Setup(Boolean) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenSetupMenuItem.cs:79)
DG.DOTweenEditor.DOTweenUtilityWindow:DrawSetupGUI() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenUtilityWindow.cs:180)
DG.DOTweenEditor.DOTweenUtilityWindow:OnGUI() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenUtilityWindow.cs:156)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

PlayerSettings Validation: Requested build target group (16) doesn't exist; #define symbols for scripting won't be added.
UnityEditor.PlayerSettings:SetScriptingDefineSymbolsForGroup(BuildTargetGroup, String)
DG.DOTweenEditor.Core.ProEditorUtils:AddGlobalDefine(String) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenProEditor/Core/ProEditorUtils.cs:23)
System.Reflection.MethodBase:Invoke(Object, Object[])
DG.DOTweenEditor.DOTweenSetupMenuItem:ProEditor_AddGlobalDefine(String) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenSetupMenuItem.cs:92)
DG.DOTweenEditor.DOTweenSetupMenuItem:Setup(Boolean) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenSetupMenuItem.cs:79)
DG.DOTweenEditor.DOTweenUtilityWindow:DrawSetupGUI() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenUtilityWindow.cs:180)
DG.DOTweenEditor.DOTweenUtilityWindow:OnGUI() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenUtilityWindow.cs:156)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

PlayerSettings Validation: Requested build target group (22) doesn't exist; #define symbols for scripting won't be added.
UnityEditor.PlayerSettings:SetScriptingDefineSymbolsForGroup(BuildTargetGroup, String)
DG.DOTweenEditor.Core.ProEditorUtils:AddGlobalDefine(String) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenProEditor/Core/ProEditorUtils.cs:23)
System.Reflection.MethodBase:Invoke(Object, Object[])
DG.DOTweenEditor.DOTweenSetupMenuItem:ProEditor_AddGlobalDefine(String) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenSetupMenuItem.cs:92)
DG.DOTweenEditor.DOTweenSetupMenuItem:Setup(Boolean) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenSetupMenuItem.cs:79)
DG.DOTweenEditor.DOTweenUtilityWindow:DrawSetupGUI() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenUtilityWindow.cs:180)
DG.DOTweenEditor.DOTweenUtilityWindow:OnGUI() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenUtilityWindow.cs:156)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Assets/Demigiant/DOTweenPro/DOTweenAnimation.cs(271,55): error CS1929: Type `TMPro.TextMeshProUGUI' does not contain a member `DOText' and the best extension method overload `DG.Tweening.ShortcutExtensions46.DOText(this UnityEngine.UI.Text, string, float, bool, DG.Tweening.ScrambleMode, string)' requires an instance of type `UnityEngine.UI.Text'

Assets/Demigiant/DOTweenPro/DOTweenAnimation.cs(274,51): error CS1929: Type `TMPro.TextMeshPro' does not contain a member `DOText' and the best extension method overload `DG.Tweening.ShortcutExtensions46.DOText(this UnityEngine.UI.Text, string, float, bool, DG.Tweening.ScrambleMode, string)' requires an instance of type `UnityEngine.UI.Text'
-------

Thanks.

**Comment by Demigiant** [comment]
Ahoy!

The "PlayerSettings Validation" logs look evil but they're actually good. They don't create any issues but allow DOTween to set defines on all Unity versions.

"Type TMPro.TextMeshProUGUI' does not contain a memberDOText'" instead is not good. But can I ask you to get the latest version of DOTween's core [from here](http://dotween.demigiant.com/download.php) (to install, replace your DOTween folder with its contents), re-run the Setup, and let me know?

**Comment by ohbado** [comment]
Thank you for your reply.

> The "PlayerSettings Validation" logs look evil but they're actually good. They don't create any issues but allow DOTween to set defines on all Unity versions.

Is "PlayerSettings Validation" log not a bad error?
I understood.
However, I think that it is better to include this answer in the FAQ. That way, similar questions will not increase.

> "Type TMPro.TextMeshProUGUI' does not contain a memberDOText'" instead is not good. But can I ask you to get the latest version of DOTween's core from here (to install, replace your DOTween folder with its contents), re-run the Setup, and let me know?

I imported it according to your advice.
The error has been resolved. Thank you.
If you can, I think that it is better to register the above latest version in the asset store.
Then your burden of support will decrease.

Thanks.

**Comment by Demigiant** [comment]
> Is "PlayerSettings Validation" log not a bad error?
I understood.
However, I think that it is better to include this answer in the FAQ. That way, similar questions will not increase.

You are completely right, and I added a note to the panel in the new version I'll release next :)

> I think that it is better to register the above latest version in the asset store.

You are right again. Going to do it during the weekend
