### ISSUE TITLE
[Feature] fake gravity Tween Ease

### ISSUE THREAD

**Issue by jmp909** [Demigiant/dotween#215]
Hi @Demigiant 

I've got a project where I need some objects to fall at the same speed as some default physics objects under gravity forces, but I can't really enable physics on these ones  as I need them to stop at a specific random Y position (ie they dont hit the ground) and also they don't collide with other objects (I guess I could run an Update check on the position though and disable physics when they reach it)

But it would be good to have an Ease that (potentially used the physics setting so that it) does a gravity-like acceleration

maybe other people can suggest why this feature would be useful.

I'm just approximating with an `Ease.OutSine` at the moment as best as I can match the two

**Comment by jmp909** [comment]
actually I can see a potential problem here, as I would not want it to come to rest abruptly.. it needs to ease out slightly towards the end... and that's not how gravity works.

possibly a use case where I just need my own specific implementation. 

again, unless other people can find use for a mock-gravity easing.

**Comment by Demigiant** [comment]
Ahoy,

Fake-gravity would be out of scope for a tween engine I believe, but you can use a custom `AnimationCurve` (which, if serialized and shown in the Inspector, has a nifty curve-drawing editor) to draw the ease you prefer, and pass it to `SetEase`, which accepts an `AnimationCurve` too.
