### ISSUE TITLE
transform.DoMoveY causes rigidBody2D.DORotate to be stepped not smooth

### ISSUE THREAD

**Issue by jmp909** [Demigiant/dotween#217]
if i call this,  my rotation is stepped not smooth (also doesn't use short angle - as per other issue raised)

```C#
transform.DOMoveY(targetY, tweenTime)   
rigidBody2D.DORotate(targetBottleRotation, tweenTime);
```

is it best not to mix transform and rigidBody tweens?

**Comment by Demigiant** [comment]
Indeed you should never mix transform and rigidbody animations (neither with DOTween nor manually inside Unity), because it makes the phsyics engine go crazy (though I didn't think it would go this crazy).
