### ISSUE TITLE
[Feature] Kill by "tag" or current MonoBehaviour etc

### ISSUE THREAD

**Issue by jmp909** [Demigiant/dotween#218]
Hi @Demigiant 

it would be useful to be able to only kill the tweens on the current (or specified) GameObject/MonoBehaviour etc (including tweens on nested items on the GameObject)

currently `KillAll()` is a bit too drastic

with MEC for example you  can tag a group of coroutines  so that you can then call eg `Timing.KillCoroutines("simulation");` to kill any coroutines tagged with "simulation"

it would be useful to be able to do `DOTween.KillAll("someTag")` (not Unity tags just a string reference)
after maybe calling `myTween.SetTag("someTag")`

for instance I have an array of items falling down the screen and I want to be able to stop the tween on all of these, but I don't want to stop the tween that's animating my UI in front of them. 

also in some case `KillAll` kills all tweens on all GameObjects/MonoBehaviours, but I just want to kill tweens on the current MonoBehaviour etc

I'm thinking the following overrides could work

`KillAll(MonoBehaviour mono)` => `DOTween.KillAll(this)`
`KillAll(GameObject go, bool includeChildren)` => `DOTween.KillAll(this.gameObject, true)`
`KillAll(String tag)` => `DOTween.KillAll("someTag")`

again this is stuff we can manage ourself, but would be a handy feature.

thanks
J.

**Comment by Demigiant** [comment]
Ahoy,

You can use [myTween.SetId(myId)](http://dotween.demigiant.com/documentation.php?api=SetId) and [DOTween.Kill(myId)](http://dotween.demigiant.com/documentation.php#controls) :)

**Comment by jmp909** [comment]
@Demigiant 

yep sorry found that one after I raised it. wasn't sure if you could assign multiple tweens with the same id
