### ISSUE TITLE
Move to Transform/GameObject in the DOTweenAnimation component

### ISSUE THREAD

**Issue by vabric** [Demigiant/dotween#22]
Could you add the possibility to move to a Transform or a GameObject in the DOTweenAnimation inspector?
It would be usefull in cases where we want to move towards an object that doesn't have a pre-determined position.
Thanks

**Comment by Demigiant** [comment]
Hello,

I thought about it, but the problem with a "follow tween" would be that it wouldn't be able to be rewinded or manipulated as the other tweens (because in order to allow it to readapt correctly to its follow target's position every frame, it would need to change its start value too). I'm thinking that maybe I could add an extra "DOTweenFollow" component just for that. What you think of it?

**Comment by vabric** [comment]
Hi,

I was thinking of something much more simpler (though a "follow tween" would be great as well). The idea is just to get the position of the GameObject as the destination when the tween start.
For example, if I want some text to move from the center of the screen to an element of my HUD, I'd like to set the element as the destination instead of entering its coordinates. This way, if I reorganize my UI layout later, I don't have to modify my tweens.
I'd be glad to help add this feature if it's ok with you.

Thanks

**Comment by Demigiant** [comment]
Hello,

Ah! That would be indeed much simpler! I'm going to see if I can add it later today then :) In the meantime, if you don't have access to DOTween Pro's private download area, follow [these instructions](http://forum.demigiant.com/index.php?topic=2.0), so I can send you a link as soon as it's done.

Cheers

**Comment by Demigiant** [comment]
[Voilà](http://forum.demigiant.com/index.php?topic=63.0) :)

There is now a switch button next to the Vector3 field of Move tweens, which can be used to tell DOTweenAnimation to use a target instead of a Vector3 value

**Comment by vabric** [comment]
Awesome! Thanks for the quick update :).

**Comment by Jayatubi** [comment]
Would the tween auto update the destination position if the gameobject moves away before the tween finishes?

**Comment by ghost** [comment]
does the tween update its destination when the transform moves while the tween is happening ?

**Comment by Demigiant** [comment]
No, the position is evaluated only when the tween starts.

**Comment by Anma-wp** [comment]
You can make the object move in the target local space that would be similar to moving toward the target object. Something like that
```
public static TweenerCore<Vector3, Vector3, VectorOptions> DOMoveInTargetLocalSpace(this Transform transform, Transform target, Vector3 targetLocalEndPosition, float duration)
        {
            var t = DOTween.To(() => transform.position - target.transform.position,
                x => transform.position = x + target.transform.position, targetLocalEndPosition, duration);
            t.SetTarget(transform);
            return t;
        }
```

You can also try playing with formulas to make the movement even better. All that you need is set the right value in DOSetter. I think you got the idea. But I don try to use speed based movement.

**Comment by Ayfel** [comment]
Vote for the DOTweenFollow idea, I would definitely use that

**Comment by Ayfel** [comment]
Just an update. I added extensions to tween in local space of the target, that way it behaves just like following a target. I got the idea from another post. Here is the position and rotation code for it

```
 public static TweenerCore<Vector3, Vector3, VectorOptions> DOMoveInTargetLocalSpace(this Transform transform, Transform target, Vector3 targetLocalEndPosition,float duration)
    {
        var t = DOTween.To(
            () => transform.position - target.transform.position, // Value getter
            x => transform.position = x + target.transform.position, // Value setter
            targetLocalEndPosition, 
            duration);
        t.SetTarget(transform);
        return t;
    }

    public static TweenerCore<Quaternion, Quaternion, NoOptions> DORotateQuaternionLocalSpace(
        this Transform transform, 
        Transform target,
        Quaternion endValue,
        float duration)
    {
        TweenerCore<Quaternion, Quaternion, NoOptions> t = DOTween.To<Quaternion, Quaternion, NoOptions>((ABSTweenPlugin<Quaternion, Quaternion, NoOptions>) PureQuaternionPlugin.Plug(), (DOGetter<Quaternion>) (() => Quaternion.Inverse(target.rotation)*transform.rotation), (DOSetter<Quaternion>) (x => transform.rotation = target.rotation * x), endValue, duration);
        t.SetTarget<TweenerCore<Quaternion, Quaternion, NoOptions>>((object) transform);
        return t;
    }
```

To follow the object exactly use Vector3.zero and Quaternion.Identity for the targetLocalEndPosition and endvalue
