### ISSUE TITLE
can't loop inner sequence?

### ISSUE THREAD

**Issue by jmp909** [Demigiant/dotween#220]
what would be the correct way to do this? (or it's possibly a bug)

object starts at `X=0`. I want to move it to the left `(X=-5)` then have it repeat right/left from `X=-5` to `X=5`

the loop setting is ignored, and it only runs once

```C#
DOTween
    .Sequence()
    .Append
    (
        transform.DOMoveX(-5f, 0.5f)
    )
    .Append
    (
        DOTween
            .Sequence()
            .Append
            (
                transform.DOMoveX(5f, 1)
            )
            .Append
            (
                transform.DOMoveX(-5f, 1)
            )
            .SetLoops(-1)
    );
```

**Comment by jmp909** [comment]
i assumed you could nest sequences. I guess in the example above the sequence only runs once and then stops..so the inner loops don't run, because the  outer sequence is no longer running.

this would be my solution (below), 

```C#
IEnumerator StartTween()
{
    Tween initialTween = bottle.transform.DOMoveX(-5f, 0.5f);

    yield return initialTween.WaitForCompletion();

    DOTween
        .Sequence()
        .Append
        (
            transform.DOMoveX(5f, 1)
        )
        .Append
        (
            transform.DOMoveX(-5f, 1)
        )
        .SetLoops(-1);

    yield return 0f;
}
```

**Comment by Demigiant** [comment]
Sequences can be nested, but [infinite loops don't work on nested tweens](http://dotween.demigiant.com/documentation.php?api=SetLoops) :P That's because a Sequence needs to know its duration (own loops aside), which can't be calculated if it contains nested infinite loops

**Comment by jmp909** [comment]
thanks for the clarification
