### ISSUE TITLE
[Feature] DOFade autoActive (automatically SetActive(false) when fade to 0 etc)

### ISSUE THREAD

**Issue by jmp909** [Demigiant/dotween#221]
in Greensock's GSAP there is a parameter to automatically hide objects when fading to 0

this would be a useful extension to DOTween
eg 
`rend.DOFade(1, 0.5f, autoActive: true); // sets gameObject active before fade in`
`rend.DOFade(0, 0.5f, autoActive: false); // sets gameObject inactive after fade out`

(maybe the parameter should be `true` for both .. the meaning would still be obvious `set the appropriate active property`)

```C#
// Note: Using MEC Coroutines
IEnumerator<float> _ShowLogo()
{
    // assuming logo alpha was 0
    // set the logo active, then fade in
    logoSpriteRenderer.gameObject.SetActive(true);
    logoSpriteRenderer.DOFade(1, 0.5f);
    yield return 0f;
}

IEnumerator<float> _HideLogo()
{ 
    // fade out the logo
    Tween hideTween = logoSpriteRenderer.DOFade(0, 0.5f);
    
    // wait until tween completes
    yield return Timing.WaitUntilDone(hideTween.WaitForCompletion(true));
   
    // set the logo inactive
    logoSpriteRenderer.gameObject.SetActive(false);
}
```

admittedly the latter could be achieved with
```C#
logoSpriteRenderer.DOFade(0, 0.5f).OnComplete (
    () => logoSpriteRenderer.gameObject.SetActive(false)
);`

**Comment by Demigiant** [comment]
Ahoy,

Architecture-wise, one of the main concepts of DOTween is that it has no idea of what gameObjects are nor that a Transform/Renderer/etc is tied to one, so OnComplete for the win ;)

**Comment by jmp909** [comment]
yes I did wonder about that. thanks for looking anyway
