### ISSUE TITLE
DOJump unexpectedly makes transform slow down as it falls

### ISSUE THREAD

**Issue by mrtenda** [Demigiant/dotween#222]
Transform.DOJump's "jump effect" behaves in a way that I wouldn't have expected it to. It seems to make the Transform slow down as it reaches the end of the jump. This is inconsistent with the laws of physics, as objects don't usually slow down as they're falling through the air (if anything, they would accelerate and fall faster as time goes on). Because of this, it looks strange to me when DOJump is used on objects in the game world.

Example video: https://www.youtube.com/watch?v=_Gdx4a-LCP0
(Notice how the cube slows down as it falls)

Is this the intended behavior? If so, is DOJump only intended to be used on UI elements or that kind of thing, where this kind of behavior might be desired? If it's intended to be used on real objects in a game world, then it seems to not look quite right.

It's also possible I'm misusing DOJump somehow, so I've included my code below (using Unity 2017.1.0f3 and DOTween v1.1.710):
```
public class DOTweenJumpTest : MonoBehaviour
{
    public Vector3 StartPos = Vector3.zero, EndPos = new Vector3(5f, 0f, 0f);

    private Sequence _jumpSequence;

    public void Update()
    {
        if (Input.GetKeyDown("space"))
        {
            if (_jumpSequence != null)
            {
                _jumpSequence.Kill();
                _jumpSequence = null;
            }

            transform.position = StartPos;
            _jumpSequence = transform
                .DOJump(EndPos, 4, 1, 4f)
                .OnKill(() => _jumpSequence = null);
        }
    }
}
```

**Comment by Demigiant** [comment]
DOJump indeed has a "physical" approach (slows down when it peaks, than accelerates when it falls down), but it being a tween, it also changes according to the default ease, which unless you changed it is EaseQuad. If you want the correct jump, chain a Linear ease to it.

P.S. I reckon this is my bad and I should recommend Linear ease for DOJump in the docs, will update them asap
