### ISSUE TITLE
Material doesn't have a color property '_Color'

### ISSUE THREAD

**Issue by sarebots** [Demigiant/dotween#224]
Versions:
DOTween Pro 0.9.690
DOTween Core v1.1.710
TextMesh Pro 1.2.3
Unity 2018.1.0f2
Windows 10 64bit

Issue:

When I add DO Tween Animation (Script) Component to a GameObject containing text mesh pro, and set the animation to fade, I get this error:

> `Material doesn't have a color property '_Color'
> UnityEngine.Material:get_color()
> DG.Tweening.<>c__DisplayClass20_0:<DOFade>b__0() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/ShortcutExtensions.cs:266)
> DG.Tweening.Tweener:DoStartup(TweenerCore`3) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Tweener.cs:132)
> DG.Tweening.Core.TweenerCore`3:Startup() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenerCore.cs:168)
> DG.Tweening.Core.TweenManager:Update(UpdateType, Single, Single) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:390)
> DG.Tweening.Core.DOTweenComponent:Update() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:51)
> `
> 
> `Material doesn't have a color property '_Color'
> UnityEngine.Material:get_color()
> DG.Tweening.<>c__DisplayClass20_0:<DOFade>b__0() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/ShortcutExtensions.cs:266)
> DG.Tweening.Plugins.ColorPlugin:EvaluateAndApply(ColorOptions, Tween, Boolean, DOGetter`1, DOSetter`1, Single, Color, Color, Single, Boolean, UpdateNotice) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Plugins/ColorPlugin.cs:72)
> DG.Tweening.Core.TweenerCore`3:ApplyTween(Single, Int32, Int32, Boolean, UpdateMode, UpdateNotice) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenerCore.cs:178)
> DG.Tweening.Tween:DoGoto(Tween, Single, Int32, UpdateMode) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:248)
> DG.Tweening.Core.TweenManager:Update(UpdateType, Single, Single) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:436)
> DG.Tweening.Core.DOTweenComponent:Update() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:51)
> `

When I set the animation to text it says 'No valid component was found for the selected object.

**Comment by Demigiant** [comment]
Hi,

I assume you imported and ran DOTween's setup BEFORE importing TextMesh Pro (which deletes TMP's extra shortcuts). In that case, please reimport DOTween Pro and re-run the setup. Sorry for the inconvenience :P

**Comment by sarebots** [comment]
Hey, thanks for the quick reply, I've tried setting up Dotween Pro multiple times, re-imported it, and even replaced Dotween folder with the latest version of Dotween Core. Still no luck.

**Comment by Demigiant** [comment]
That is very weird :O I just did the same process in a new project in the exact same version of Unity and everything worked. Are you using TextMesh Pro from the Asset Store (DLL version) or from their forum (loose script version)?

**Comment by sarebots** [comment]
I'm using the one from Package Manager

**Comment by sarebots** [comment]
I was able to reproduce the error:

- Open a new 2D project
- Install TextMesh Pro from Window>Package Manager>All
- Go to Window>Resources>Import Textmesh pro essentials
- Import DOTween Pro from Asset Store
- Create new GameObject and add a TextMeshPro Component
- Add DOTween animation component to it
- Change Type to Text(No valid component was found) or Color (Material doesn't have property '_Color')(During runtime)

**Comment by AlCaTrAzzALZ** [comment]
have the same issue in 2018.2.0f2 - looks like it cant see the package manager version of textmeshpro

**Comment by Demigiant** [comment]
Ahoy, and sorry for the late update.

The new Package Manager version of TextMesh Pro is external, so indeed DOTween Pro can't recognize it anymore. I just made a new update that fixes this issue, but I haven't yet released it. Can you two write me a mail with your name (and the PDF of your DOTween Pro purchase, so I know it's you), so I can send it to you?

P.S. alternatively, in the meantime you can [follow these instructions](http://dotween.demigiant.com/support.php?faq=TextMesh%20Pro) to fix it.

Cheers,
Daniele

**Comment by Demigiant** [comment]
P.S. to write me a mail, use the contact form [here](http://www.demigiant.com/about.php#contactWrap) :P

**Comment by c-andrews** [comment]
Hi, Any news on an update as i'm having the same issue? I've tried to manually remove the ".addon" to the TextMeshPro file (I could only see one) but I am still getting the "No Valid Comonent..." message on my GO.

**Comment by Demigiant** [comment]
I apologize, I forgot to indicate that you also have to add a "DOTWEEN_TMP" define. [I updated the instructions](http://dotween.demigiant.com/support.php?faq=TextMesh%20Pro).

The update is ready but I'm having issues with the upgrade process (in some cases existing DOTweenAnimations/Paths lose their references). I really aim to solve it and push it within the end of this week.

**Comment by c-andrews** [comment]
Thanks, that did the trick
