### ISSUE TITLE
DOTween stops working when platform is switched to Android

### ISSUE THREAD

**Issue by dixitabhi** [Demigiant/dotween#225]
I am building a game in unity and am using DOTween to animate the spawning of objects. Everything works really great but when i switch my platfrom to android from windows nothing works at all. I've tried almost everything and nothing seems to work. What could possibly be causing this?

**Comment by Demigiant** [comment]
Hi! Saw your mail and am gonna reply there :)

**Comment by h3xed** [comment]
@Demigiant I have this same problem. Can you reply here? :)

**Comment by Demigiant** [comment]
@h3xed Ahoy! Sure, I'm going to copy-paste what I wrote to Abhinav :)

> There is nothing that could stop tweens working when changing platform. I have a feeling that you're having issues with Unity's "random call order" instead.
> 
> You know that the Awake/Start/Update/etc methods of your components aren't called in a specific order, right? Meaning that, for example, if you have 3 components with Awake that are active in the scene since startup, you can't know which one will call its Awake first (unless you use ScriptExecutionOrder). I believe that's your problem. Your Awake/Start/Update order was good on Windows, and then when you switched to Android Unity scrambled it again and now it's bad, so maybe you're calling tweens before a variable in another component's Awake has been initialized or things like that.
> 
> A trick to debug this. First of all, deactivate "safe mode" from DOTween's options. That way tweens won't capture errors and fail silently, but tell you what's happening. If this is not enough, add Debug.Logs to a tween's OnStart and OnKill callbacks, to see what's happening.
> 
> Oh, and also check that, for some weird reason, your timeScale wasn't set to 0 on Android :P

**Comment by h3xed** [comment]
Thank you for instant reply!

I resolved my problem. For learn Unity i working on template from store. Author wrap a lot of code by #if AADOTWEEN directive. It work correctly on Linux platform but not working after switch to Android. I don't know why but remove this block or add AADOTWEEN declaration resolved problem :)

**Comment by Demigiant** [comment]
Ah, glad you solved it :)
