### ISSUE TITLE
How to kill a tween which create in the generic way?

### ISSUE THREAD

**Issue by AemaethMonster** [Demigiant/dotween#228]
I'm writing a script that each value changes on their own.
But I don't know how to stop just one of them.

    public float offset_x = 0;
	void Start ()
    {
        DOTween.To(() => offset_x, x => offset_x = x, 6, 10);
        Invoke("stop", 2);
    }
	
    void stop()
    {
        DOTween.Kill(offset_x);
    }
Must has some mistakes↑
Need help:D

BTW，Dotween is a great job.
Unity's Invoke can only call a void method.
Dotween's .OnComplete(MyCallback) can have params.

**Comment by Demigiant** [comment]
Ahoy!
Thanks for the nice words :)
You can either store you tween reference when creating it, and then kill that:

```
myTween` = DOTween.To(() => offset_x, x => offset_x = x, 6, 10);
...
myTween.Kill();
```
Or you can give it an ID via `SetId` and then pass that ID to the static Kill method.

**Comment by AemaethMonster** [comment]
Thank you~
