### ISSUE TITLE
Question about Sequence.InsertCallback()

### ISSUE THREAD

**Issue by AemaethMonster** [Demigiant/dotween#229]
void try2_sequence()
    {
        ms2 = DOTween.Sequence();
        for(int i = 0; i<5; i++)
        {
            ms2.InsertCallback(i, () => say(i.ToString()));
        }
    }
    void say(string words)
    {
        Debug.Log(words);
    }
This code Debug.Log as ↓ .
```
 5
 5
 5
 5
 5
 ```

Can this Debug.Log as ↓ ？
```
0
1
2
3
4
```

**Comment by Demigiant** [comment]
To be sure you're using the right assignment, re-declare the variable inside the loop, otherwise "i" will always have the last value assigned:
```
for(int i = 0; i<5; i++)
{
   string s = i;
   ms2.InsertCallback(i, () => say(s.ToString()));
}
```

**Comment by AemaethMonster** [comment]
Thank you~
