### ISSUE TITLE
Callbacks are still called even though the sequence was killed

### ISSUE THREAD

**Issue by ehudros** [Demigiant/dotween#23]
Hi,
I'm seeing a strange issue where killing a sequence does not prevent callback it contains from running. This ends up throwing the following error after an object is destroyed:

I have the following code:

```
sequence = DOTween.Sequence();              
sequence.AppendInterval(3 * delayFactor);               
sequence.AppendCallback(() => {
this.transform.GetComponent<MeshRenderer>().enabled = !this.transform.GetComponent<MeshRenderer>().enabled;
});

sequence.SetLoops(-1, LoopType.Restart);
sequence.Play();

void OnDestroy()
    {
        if (sequence != null)
        {
            sequence.Kill();
            //sequence = null;
        }
    }
```

After an object is destroyed I get the following error:
DOTWEEN :: An error inside a tween callback was silently taken care of > The object of type 'BuildingIdleAnimation' has been destroyed but you are still trying to access it. Your script should either check if it is null or you should not destroy the object.

Am I missing something here? It seems like killing the sequence does not prevent it from calling the callback it contained?

Thanks!

**Comment by Demigiant** [comment]
Hello,

Killing a Sequence renders it immediately inactive, so callbacks won't be called anymore.

I even replicated your code to be sure nothing weird was happening, and everything is killed correctly here. So I suppose you have some other similar object where the OnDestroy is not called, or maybe you didn't store the sequence variable but created the Sequence anonimously, so the Kill is not happening?

I'm closing this for now, since I'm pretty sure it must be a script error on your side, but let me know.

Cheers,
Daniele

**Comment by ehudros** [comment]
Thanks for the quick reply, I'll take a closer look at what's going here and reopen this if I find anything that's indeed Dotween related.

On a related note, is there any way to see the currently running tweens like Hotween manager used to display them? (meaning the objects themselves and not just an "Active tweens" counter)

**Comment by Demigiant** [comment]
Sorry but no: there is no way to see the actual objects. DOTween has a different logic than HOTween, and it knows absolutely nothing of the object it's tweening: it keeps track only of the properties.

**Comment by zszen** [comment]
DOTween.Kill(target) can't kill sequence with this target.

**Comment by Demigiant** [comment]
@zszen Not sure what you mean :P

**Comment by benjamin-asdf** [comment]
Hi, 

Am I assuming correctly that this is also the case for pausing tweens? Eg. we pause kill in an `OnDisable` function, is it save to assume there are no callbacks from the next frame onwards?

**Comment by Demigiant** [comment]
Ahoy! Yes, pausing/killing a tween will also pause/kill all callbacks
