### ISSUE TITLE
Can't use DOTween.defaultEaseType at the MonoBehaviour properties and fields

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Demigiant/dotween#236]
Heya, Daniele!

I recently noticed this problem: when I use DOTween.defaultEaseType at the MonoBehaviour filed, I get these 2 errors at the Unity Console after scripts recompilation:

1:
> get_isEditor is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'ItemsSnap' on game object 'Carousel'.
> See "Script Serialization" page in the Unity Manual for further details.
> UnityEngine.Application:get_isEditor()
> DG.Tweening.DOTween:.cctor() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:116)
> ItemsSnap:.ctor() (at Assets/Application/Scripts/Runtime/UI/Carousel/ItemsSnap.cs:16)
> ItemsSnap:.ctor() (at Assets/Application/Scripts/Runtime/UI/Carousel/ItemsSnap.cs:13)

2:
> UnityException: get_isEditor is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'ItemsSnap' on game object 'Carousel'.
> See "Script Serialization" page in the Unity Manual for further details.
> DG.Tweening.DOTween..cctor () (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:116)
> Rethrow as TypeInitializationException: An exception was thrown by the type initializer for DG.Tweening.DOTween
> UI.ItemsSnap..ctor () (at Assets/Application/Scripts/Runtime/UI/Carousel/ItemsSnap.cs:13)
> 

DOTween 1.1.640

Example where it produces such errors:
`public class ItemsSnap : MonoBehaviour
{
	public Ease snappingEasing = DOTween.defaultEaseType;`

This one works fine though:
`public class ItemsSnap : MonoBehaviour
{
	public Ease snappingEasing = Ease.OutQuad;`

**Comment by Demigiant** [comment]
Dmitriy!!! :)

Ah, damn!!! That's because DOTween's static constructor queries `Application.isEditor`, and apparently you're the first person to add a call to a DOTween property in a MonoBehaviour's getter, so I never realized this issue before :B

I will move the Application.isEditor query into some other class then! Is this urgent, or you can wait until next week when I publish the Modules update (which I'll close with this fix)? :P

**Comment by DmitriyYukhanov** [comment]
Totally no rush here,  take your time! =)

**Comment by DmitriyYukhanov** [comment]
Ah and huge thanks for the so quick reaction! I know you're pretty busy now so hoped this way will not be as disturbing as direct messages ^^

**Comment by Demigiant** [comment]
You can direct message me anytime you want, but thanks for the consideration ^_^

**Comment by Demigiant** [comment]
Done! Will send this to you along the other things we were talkign about ;)
