### ISSUE TITLE
  moving platforms use  rigidbody2D.DOMoveX  Physical effect is incorrect

### ISSUE THREAD

**Issue by XiaoFanJX** [Demigiant/dotween#244]
I have a moving platform Using  rigidbody2D.DOMoveX functions The character will slide on it
But I use rigidbody2D.MovePosition The character Will not slip 
Said in the document rigidbody2D.DOMoveX use rigidbody2D.MovePositio What is the difference?

**Comment by Demigiant** [comment]
Hi,

You should also use SetUpdate(UpdateType.Fixed), so the tweens will not only use rigidbody, but also run during FixedUpdate only. I'm pondering since a while if I should automatically set Rigidbody tweens to UpdateType.Fixed: I guess I will do that :P

**Comment by XiaoFanJX** [comment]
is work!

**Comment by novavision** [comment]
```I guess I will do that```
@Demigiant did you?

**Comment by novavision** [comment]
> I guess I will do that :P

@Demigiant , did you?
