### ISSUE TITLE
DOLocalJump: having any delay messes up the y-component

### ISSUE THREAD

**Issue by mikatu** [Demigiant/dotween#249]
Should be reproducible in v1.2.055 with the following

transform.DOLocalJump(new Vector3(1, 1), 0.1f, 2, 0.4f).SetDelay(1);

**Comment by fmoyano** [comment]
I've also experienced this error with the same version. I had to change "DoLocalJump" to "DoLocalMove".

**Comment by CongDeveloper** [comment]
This error still exist in v1.0.244. It happen when meet the conditions:

- startValue is not equals endValue
- use SetDelay

If use PrependInterval instead of SetDelay, it work well.

**Comment by Demigiant** [comment]
For anyone having this problem [here's the update](http://dotween.demigiant.com/tmp/DOTween_1_2_560.zip) that fixes it (will release it publicly in a few days).
