### ISSUE TITLE
exception stack trace is swallowed when using safemode

### ISSUE THREAD

**Issue by theshked** [Demigiant/dotween#25]
Hi,

When using useSafeMode=True, if an exception occurs within a callback (e.g. inside an OnComplete callback), the exception stack trace is swallowed, and only the exception message is printed to the log. This make debugging significantly harder.

DoTweenPro v0.9.160
Unity v5.0.1f1

Thanks!

**Comment by Demigiant** [comment]
Hello,

You're totally right. Grab [this new update](http://dotween.demigiant.com/tmp/DOTween_1_0_775.zip) which now shows stack trace correctly.

Cheers,
Daniele
