### ISSUE TITLE
Tween allocation 40b every frame

### ISSUE THREAD

**Issue by alexander12356** [Demigiant/dotween#250]
Hi,
this code:
DOTween.To(() => ArrowAnimationCoeff, (value) => ArrowAnimationCoeff = value, _arrowMoveCoeffTarget, _arrowMoveDuration).SetLoops(-1, LoopType.Yoyo);
allocation 40b every frame. 
Unity version 2017.4.9f1
DOTween version: 1.1.640 [Release build]
Can you help pls
Thanks

**Comment by Demigiant** [comment]
What is ArrowAnimationCoeff? Is it a property? My assumption is that that is the one that's generating allocations when called every frame

**Comment by alexander12356** [comment]
OOh
Thanks! My shame:)

**Comment by Demigiant** [comment]
:)
