### ISSUE TITLE
Is Dotween included System.dll?

### ISSUE THREAD

**Issue by chris1054** [Demigiant/dotween#254]
I'm trying to build games on WebGL and using System.dll makes my our games pretty long to load scripts.
Also, it makes the build size a little bigger.
I just wonder if Dotween can exclude this dll?

**Comment by Demigiant** [comment]
Hi,

I'm sorry but I reeeally need to use System.dll because DOTween needs some Reflection at startup, in order to communicate with its non-dll modules.
