### ISSUE TITLE
ChangeValues do not apply

### ISSUE THREAD

**Issue by eduardhasanaj** [Demigiant/dotween#256]
Hi,
I am changing tweener values like and then I perform some operations like:
ChangeValues();
Complete();

It does not apply new values. I call complete but it does not go to new endValue

**Comment by eduardhasanaj** [comment]
Oh sorry I just came across this "NOTE: works on regular tweens, not on ones that do more than just animate one value from one point to another (like DOLookAt). 
Does this state that in tweener like DoAnchorPosX it wont work?

**Comment by eduardhasanaj** [comment]
Hmm just tested with DoAnchorPos and it do not work

**Comment by 0kk470** [comment]
Emmm.. Also not work for DOtween.To.

**Comment by Demigiant** [comment]
Please check that the tween is not set to auto-kill-on-complete (by chaining a `SetAutoKill(false)`) :P
