### ISSUE TITLE
Can't build my hololens application due to Dotween

### ISSUE THREAD

**Issue by wesket** [Demigiant/dotween#257]
Hello,

Everytime i try to build my application to the hololens i get errors. What can i do to fix this?

Reference rewriter: Error: method `System.Reflection.Assembly[] System.AppDomain::GetAssemblies()` doesn't exist in target framework. It is referenced from DOTween.dll at System.Type DG.Tweening.Core.Utils::GetLooseScriptType(System.String).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:989)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:211)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Reference rewriter: Error: type `System.AppDomain` doesn't exist in target framework. It is referenced from DOTween.dll at System.Type DG.Tweening.Core.Utils::GetLooseScriptType(System.String).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:989)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:211)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Reference rewriter: Error: type `System.AppDomain` doesn't exist in target framework. It is referenced from DOTween.dll at System.Type DG.Tweening.Core.Utils::GetLooseScriptType(System.String).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:989)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:211)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Reference rewriter: Error: type `System.AppDomain` doesn't exist in target framework. It is referenced from DOTween.dll at System.Type DG.Tweening.Core.Utils::GetLooseScriptType(System.String).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:989)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:211)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Reference rewriter: Error: method `System.Reflection.MethodInfo System.Type::GetMethod(System.String,System.Reflection.BindingFlags)` doesn't exist in target framework. It is referenced from DOTween.dll at System.Void DG.Tweening.Core.DOTweenComponent::Awake().
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:989)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:211)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Reference Rewriter found some errors while running with command --target="Temp\StagingArea\DOTween.dll" --additionalreferences="Temp\StagingArea","Temp\StagingArea\Plugins\X64","Temp\StagingArea\Plugins\X86","Temp\StagingArea\Plugins\ARM","Temp\StagingArea\Plugins\ARM","Temp\StagingArea\Plugins\X86","Temp\StagingArea\Plugins\X64","Temp\StagingArea\Plugins\X64","Temp\StagingArea\Plugins\ARM","Temp\StagingArea\Plugins\X86","Temp\StagingArea\Plugins\ARM","Temp\StagingArea\Plugins\X64","Temp\StagingArea\Plugins\X86","Temp\StagingArea\Plugins\x86","Temp\StagingArea\Plugins\x64","Temp\StagingArea\Plugins\ARM","Temp\StagingArea\Plugins\X64","Temp\StagingArea\Plugins\X86","Temp\StagingArea\Plugins\x64","Temp\StagingArea\Plugins\x86","C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.17134.0\Facade","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Calls.CallsVoipContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.SocialInfo.SocialInfoContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.StartupTaskContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Devices.Custom.CustomDeviceContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Devices.DevicesLowLevelContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Devices.Printers.PrintersContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Devices.SmartCards.SmartCardEmulatorContract\5.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Foundation.FoundationContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Foundation.UniversalApiContract\6.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Gaming.XboxLive.StorageApiContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Graphics.Printing3D.Printing3DContract\4.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Networking.Connectivity.WwanContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Services.Store.StoreContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Services.TargetedContent.TargetedContentContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.System.Profile.ProfileHardwareTokenContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.System.Profile.ProfileSharedModeContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.UI.ViewManagement.ViewManagementViewScalingContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Activation.ActivatedEventsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Activation.ActivationCameraSettingsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Activation.ContactActivatedEventsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Calls.Background.CallsBackgroundContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Calls.LockScreenCallContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.FullTrustAppContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Preview.InkWorkspace.PreviewInkWorkspaceContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Preview.Notes.PreviewNotesContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Resources.Management.ResourceIndexerContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Search.Core.SearchCoreContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Search.SearchContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Wallet.WalletContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Devices.Portable.PortableDeviceContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Devices.Printers.Extensions.ExtensionsContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Devices.Scanners.ScannerDeviceContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Devices.Sms.LegacySmsApiContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Gaming.Input.GamingInputPreviewContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Gaming.Preview.GamesEnumerationContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Gaming.UI.GameChatOverlayContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Gaming.UI.GamingUIProviderContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Management.Deployment.Preview.DeploymentPreviewContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Management.Workplace.WorkplaceSettingsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Media.AppBroadcasting.AppBroadcastingContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Media.AppRecording.AppRecordingContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Media.Capture.AppBroadcastContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Media.Capture.AppCaptureContract\4.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Media.Capture.AppCaptureMetadataContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Media.Capture.CameraCaptureUIContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Media.Capture.GameBarContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Media.Devices.CallControlContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Media.MediaControlContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Media.Playlists.PlaylistsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Media.Protection.ProtectionRenewalContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Networking.Sockets.ControlChannelTriggerContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Networking.XboxLive.XboxLiveSecureSocketsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Perception.Automation.Core.PerceptionAutomationCoreContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Security.EnterpriseData.EnterpriseDataContract\5.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Security.ExchangeActiveSyncProvisioning.EasContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Services.Maps.GuidanceContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Services.Maps.LocalSearchContract\4.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Storage.Provider.CloudFilesContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.System.Profile.SystemManufacturers.SystemManufacturersContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.System.Profile.ProfileRetailInfoContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.System.UserProfile.UserProfileContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.System.UserProfile.UserProfileLockScreenContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.UI.ApplicationSettings.ApplicationsSettingsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.UI.Core.AnimationMetrics.AnimationMetricsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.UI.Core.CoreWindowDialogsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.UI.Xaml.Hosting.HostingContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Web.Http.Diagnostics.HttpDiagnosticsContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.System.SystemManagementContract\5.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.Calls.CallsPhoneContract\4.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Embedded.DeviceLockdown.DeviceLockdownContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Networking.NetworkOperators.NetworkOperatorsFdnContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Phone.PhoneContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.Phone.StartScreen.DualSimTileContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.17134.0\Windows.UI.WebUI.Core.WebUICommandBarContract\1.0.0.0" --platform="C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.17134.0\Facade\Windows.winmd" --dbg=pdb --support="Temp\StagingArea\WinRTLegacy.dll" --supportpartialns=Unity.Partial --system=System --lock=UWP\project.lock.json --alt=Microsoft.Win32.SafeHandles,System.IO.FileSystem;Microsoft.Win32.SafeHandles,System.Runtime.Handles;System,System.ComponentModel;System,System.Data.Common;System,System.Runtime;System,System.Runtime.Extensions;System,System.Runtime.InteropServices;System,System.Threading.Tasks;System.CodeDom.Compiler,System.Diagnostics.Tools;System.Collections,System.Collections;System.Collections,System.Collections.NonGeneric;System.Collections,System.Runtime;System.Collections.Generic,System.Collections;System.Collections.Generic,System.Runtime;System.Collections.ObjectModel,System.ObjectModel;System.Collections.ObjectModel,System.Runtime;System.Collections.Specialized,System.Collections.NonGeneric;System.Collections.Specialized,System.Collections.Specialized;System.Collections.Specialized,System.ObjectModel;System.ComponentModel,Microsoft.Win32.Primitives;System.ComponentModel,System.ComponentModel;System.ComponentModel,System.ComponentModel.EventBasedAsync;System.ComponentModel,System.ObjectModel;System.ComponentModel,System.Runtime;System.ComponentModel.DataAnnotations,System.ComponentModel.Annotations;System.Data,System.Data.Common;System.Data.Common,System.Data.Common;System.Diagnostics,System.Diagnostics.Debug;System.Diagnostics,System.Diagnostics.StackTrace;System.Diagnostics,System.Runtime;System.Diagnostics,System.Runtime.Extensions;System.Diagnostics.CodeAnalysis,System.Diagnostics.Tools;System.Globalization,System.Globalization;System.Globalization,System.Globalization.Calendars;System.Globalization,System.Globalization.Extensions;System.Globalization,System.Runtime;System.IO,System.IO;System.IO,System.IO.FileSystem;System.IO,System.IO.FileSystem.Primitives;System.IO,System.IO.UnmanagedMemoryStream;System.IO,System.Runtime;System.IO,System.Runtime.Extensions;System.IO,System.Runtime.Handles;System.IO.Compression,System.IO.Compression;System.IO.IsolatedStorage,System.IO.IsolatedStorage;System.Linq,System.Linq;System.Linq,System.Linq.Expressions;System.Linq,System.Linq.Queryable;System.Linq.Expressions,System.Linq.Expressions;System.Net,System.Net.Primitives;System.Net,System.Net.Requests;System.Net,System.Net.WebHeaderCollection;System.Net.NetworkInformation,System.Net.NetworkInformation;System.Net.NetworkInformation,System.Net.Primitives;System.Net.Security,System.Net.Primitives;System.Net.Sockets,System.Net.Primitives;System.Net.Sockets,System.Net.Sockets;System.Reflection,System.Reflection;System.Reflection,System.Reflection.Extensions;System.Reflection,System.Reflection.Primitives;System.Reflection,System.Reflection.TypeExtensions;System.Reflection,System.Runtime;System.Reflection,System.Runtime.InteropServices;System.Reflection.Emit,System.Reflection.Primitives;System.Resources,System.Resources.ResourceManager;System.Runtime,System.Runtime;System.Runtime.CompilerServices,System.Runtime;System.Runtime.InteropServices,System.Runtime;System.Runtime.InteropServices,System.Runtime.Handles;System.Runtime.InteropServices,System.Runtime.InteropServices;System.Runtime.InteropServices.ComTypes,System.Runtime.InteropServices;System.Runtime.Serialization,System.Runtime.Serialization.Primitives;System.Runtime.Serialization,System.Runtime.Serialization.Xml;System.Runtime.Serialization.Json,System.Runtime.Serialization.Json;System.Security,System.Runtime;System.Security.Authentication,System.Net.Primitives;System.Security.Principal,System.Security.Claims;System.Security.Principal,System.Security.Principal;System.ServiceModel,System.ServiceModel.Duplex;System.ServiceModel,System.ServiceModel.Http;System.ServiceModel,System.ServiceModel.NetTcp;System.ServiceModel,System.ServiceModel.Primitives;System.ServiceModel,System.ServiceModel.Security;System.ServiceModel.Channels,System.ServiceModel.Http;System.ServiceModel.Channels,System.ServiceModel.NetTcp;System.ServiceModel.Channels,System.ServiceModel.Primitives;System.ServiceModel.Channels,System.ServiceModel.Security;System.ServiceModel.Description,System.ServiceModel.Primitives;System.ServiceModel.Dispatcher,System.ServiceModel.Primitives;System.ServiceModel.Security,System.ServiceModel.Primitives;System.ServiceModel.Security,System.ServiceModel.Security;System.ServiceModel.Security.Tokens,System.ServiceModel.Security;System.Text,System.Globalization.Extensions;System.Text,System.Runtime;System.Text,System.Text.Encoding;System.Text,System.Text.Encoding.Extensions;System.Text.RegularExpressions,System.Text.RegularExpressions;System.Threading,System.Runtime;System.Threading,System.Threading;System.Threading,System.Threading.Overlapped;System.Threading,System.Threading.Timer;System.Xml,System.Runtime.Serialization.Xml;System.Xml,System.Xml.ReaderWriter;System.Xml,System.Xml.XmlDocument;System.Xml.Linq,System.Xml.XDocument;System.Xml.Schema,System.Xml.ReaderWriter;System.Xml.Serialization,System.Xml.ReaderWriter;System.Xml.Serialization,System.Xml.XmlSerializer;<winmd>,Windows.winmd;<winmd>,Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract.winmd;<winmd>,Windows.ApplicationModel.Calls.CallsVoipContract.winmd;<winmd>,Windows.ApplicationModel.SocialInfo.SocialInfoContract.winmd;<winmd>,Windows.Appl<message truncated>

Thanks

**Comment by Demigiant** [comment]
Hi,

It seems that your build doesn't contain the Reflection libraries. What stripping settings did you use?

**Comment by wesket** [comment]
Hello,

Where can i find what stripping settings i use?

Greet Wesley

**Comment by joranmarcy** [comment]
Hi, I'm getting the same error too. I was using Dotween 1.1.605 [Compatibility build] with Unity 5.6.5f1 ant it was building fine. Now I'm using Unity 2017.4.3f1 with the latest DoTween release 1.2.0.55 and I can't build my project anymore for an UWP application. 

Thanks, Joran.

**Comment by joranmarcy** [comment]
Not sure where the strip settings are but maybe this screenshot of the player settings could help
<img width="525" alt="stripping" src="https://user-images.githubusercontent.com/15970955/46025356-08a8e700-c0e9-11e8-940d-b9047e6224b4.PNG">
 :

**Comment by Demigiant** [comment]
Hi,

I investigated this some more, and it seems that after all it's a Unity bug with Hololens, which Unity says should be solved with the upcoming release of Unity 2018.3. In the meantime, I would recommend to revert to DOTween 1.1.710 (you can download it [from here](http://dotween.demigiant.com/download.php#changelog): expand the "old versions and changelog" dropdown and click the version to download).

To downgrade, completely delete the DOTween folder, ignore the errors, import the new DOTween zip file, close and reopen the project and everything should work correctly.

**Comment by joranmarcy** [comment]
Hi,

Thanks for the quick answer. I did the revert and now it's working fine with the Hololens.

Have a nice one.
Joran.

**Comment by wesket** [comment]
Hello,

Thanks for the answer. I will try this in the afternoon.

Have a nice day!

**Comment by mohe-iji** [comment]
Hi,
Can I downgrade the dotween pro to solve this problem?
I am using dotween pro 1.0.075.
In order to cope with this problem I deleted the dotween folder in the Demigiant folder and installed an old version of dotween.
However, even if I pressed the setup dotween button, setup did not end. The bar chart has been displayed all the time.

**Comment by Demigiant** [comment]
Hi,
Did you try upgrading Unity to 2018.3, in case this bug was solved? Other than that, if you downgrade and the setup doesn't end, that is very weird. Did you downgrade both DOTween and DOTween Pro, or only DOTween? Please write me via [this contact form](http://www.demigiant.com/about.php#contactWrap), so in case I can send you an older version of both.

**Comment by mohe-iji** [comment]
Thank you for your reply.

I confirmed the operation with unity 2018.3, and dotween pro worked normally.
However, considering the other assets I use in my game, I would like to use unity 2017.2.

I downgraded only the dotween folder.
Because I do not know how to get an old version of dotween pro, I could not downgrade the entire dotween pro.

  I will contact you from contact form.

**Comment by Ariel-Feldman** [comment]
> Hi!!!
> 
> I investigated this some more, and it seems that after all it's a Unity bug with Hololens, which Unity says should be solved with the upcoming release of Unity 2018.3. In the meantime, I would recommend to revert to DOTween 1.1.710 (you can download it [from here](http://dotween.demigiant.com/download.php#changelog): expand the "old versions and changelog" dropdown and click the version to download).
> 
> To downgrade, completely delete the DOTween folder, ignore the errors, import the new DOTween zip file, close and reopen the project and everything should work correctly.

**Thanks**!, it solved it completely!:)
 Unity 2018 | UWP (Hololens) | .NET 4.x | DOTween v1.2.235

The demon appeared for me with the face of:
" The name 'AppDomain' does not exist in the current context... "

**Comment by OzoneABN** [comment]
> **Thanks**!, it solved it completely!:)
> Unity 2018 | UWP (Hololens) | .NET 4.x | DOTween v1.2.235
> 
> The demon appeared for me with the face of:
> " The name 'AppDomain' does not exist in the current context... "

Hello,
Using DOTween 1.2.235 will cause the " The name 'AppDomain' does not exist in the current context... "
build error inside Unity (2018.3.12f1). Trying to exclude the corresponding lines in DOTweenModuleUtilities.cs (line 56+) from build using

    [UnityEngine.Scripting.Preserve]
        // Just used to preserve methods when building, never called
        static void Preserver()
        {
    #if !WINDOWS_UWP
            Assembly[] loadedAssemblies = AppDomain.CurrentDomain.GetAssemblies();
            MethodInfo mi = typeof(MonoBehaviour).GetMethod("Stub");
    #endif
        }

will fix the build-problem inside Unity, but when trying to build it forHoloLens with VS the same error occurs again (but somewere else).

Downgrading to DOTween 1.1.710 solved this error for me.
Will there be an fix in a newer version of DOTween anytime soon?
 Regards

**Comment by Demigiant** [comment]
On a secondary note, this was fixed in DOTween 1.2.196 (though @OzoneABN has still issues which are discussed in another, uh, issue)
