### ISSUE TITLE
Infinite importing DOTweenSettings.asset

### ISSUE THREAD

**Issue by rodrigod89** [Demigiant/dotween#258]
When I import DOTween I'm getting stuck in an infinite import loop. Here is the editor log

> Hashing assets (1 files)... 0.000 seconds
  file read: 0.000 seconds (0.001 MB)
  wait for write: 0.000 seconds (I/O thread blocked by consumer, aka CPU bound)
  wait for read: 0.000 seconds (CPUT thread waiting for I/O thread, aka disk bound)
  hash: 0.000 seconds
Updating Assets/Extensions/DOTween/Editor/Imgs/DOTweenIcon.png - GUID: 13ecd96179ee24e9faaea1e0056ac9d7...
 done. [Time: 96.373270 ms] 
Updating Assets/Extensions/DOTween/Editor/Imgs/Footer_dark.png - GUID: 96710bca2b5844ea693d002ffa2b1742...
 done. [Time: 12.492028 ms] 
Updating Assets/Extensions/DOTween/Editor/Imgs/Footer.png - GUID: a78c39d15a756494f8c12941269d4b84...
 done. [Time: 8.642509 ms] 
Updating Assets/Extensions/DOTween/Editor/Imgs/Header.jpg - GUID: db4169f5b3abc47aa8739a233df367a1...
 done. [Time: 26.218124 ms] 
Updating Assets/StaticAssets/TheApp/Prefabs/prefab_WebSocket_Master.prefab - GUID: 5300c68bd15ce4a55994c4e43b0e32ee...
 done. [Time: 12.214662 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 3.368018 ms] 
Updating Assets/Extensions/DOTween/DOTween.XML - GUID: 076e2c134b522416fbb270b80f6a9ea3...
 done. [Time: 4.975959 ms] 
Updating Assets/Extensions/DOTween/Editor/DOTweenEditor.XML - GUID: 2aafa3af591be401e9e2dc4c8a42179c...
 done. [Time: 9.374890 ms] 
Unloading 113 Unused Serialized files (Serialized files now loaded: 0)
System memory in use before: 450.5 MB.
System memory in use after: 450.8 MB.

>Unloading 110 unused Assets to reduce memory usage. Loaded Objects now: 4478.
Total: 7.448625 ms (FindLiveObjects: 1.642969 ms CreateObjectMapping: 0.336645 ms MarkObjects: 5.120667 ms  DeleteObjects: 0.347382 ms)

>Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 2.786445 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.924832 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.910533 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 3.409895 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.925575 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 2.226972 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.811594 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.693072 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.716707 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.674768 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.676561 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.668262 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.678972 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 3.996946 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.702753 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.700999 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.723133 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.731537 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.756561 ms] 
Updating Assets/Resources/DOTweenSettings.asset - GUID: f58eee9e9ccfe48b582d5d87cebf6496...
 done. [Time: 1.778190 ms] 

This keeps going indefinitely saying "importing small assets...". Any ideas of what it could be?
Only happens when I import DOTween. It's a clean install, no Unity stripping, and it's the latest update in the website.

**Comment by Demigiant** [comment]
Hi,

Uhmmm that is very weird and I didn't have any similar report. Can you try [this new version](http://dotween.demigiant.com/tmp/DOTween_1_2_125.zip) (1.2.125) and let me know (it changes some import routines so I hope this won't happen)?

**Comment by rodrigod89** [comment]
Weird indeed, I tried deleting the library files and rebuilding and it kept happening and now it randomly got fixed... let's just blame this on Unity, I've seen already some posts about it, so no worries on your end. Thanks for the quick reply!

**Comment by rodrigod89** [comment]
Aaand it's back... sorry for the trouble I updated with the new DOTween version you sent but it's doing the same thing again. I've deleted the library files to see if the reimport works but I'm not sure what to do at this point. I have Unity version 2018.2.8f1, I'll try new versions and see what happens

I tried it in another computer and I got the same behaviour, so I went and tried an older DOTween library and it doesn't get stuck anymore. I'm using DOTween v1.1.620 (July 13, 2017) for now.

![image](https://user-images.githubusercontent.com/1161021/46149802-649b7900-c26b-11e8-8a8d-65c5e71abba8.png)

**Comment by dongyiqi** [comment]
I met the same error under latest Unity2018.2.12f1. always update the DOTweenSettings.asset in my project.
It's ok while in the brand new project.
Where can I find the older version of DoTween pro?

**Comment by Demigiant** [comment]
Hi,

Please write me [via this form](http://www.demigiant.com/about.php#contactWrap) so I can send you an older version via mail, though this is all very weird. Can you please send me here Unity's editor log so I can see what's happening?

**Comment by Demigiant** [comment]
Hi,

Got the editor log, and it's related to DOTweenSettings preferences file, which is independent from DOTween (because that's not a reimport that I trigger directly) and a rare Unity bug I sadly can't control, usually related to a broken project's Library. Can you try [this suggested fix](https://www.linkedin.com/pulse/unity-fix-importing-small-assets-forever-chan-calvin/) and let me know how it goes? Also, can you attach here a screenshot of Unity's Editor preferences (so I can see how did you setup serialization)?

**Comment by Demigiant** [comment]
Hi,

I added an additional fix in recent versions, so there's no need for the fix at the link above.
