### ISSUE TITLE
Setup DoTween through code

### ISSUE THREAD

**Issue by dantasulisses** [Demigiant/dotween#259]
Hi
I'm currently trying to setup my project for a CI/CD process, but when I clone my repository and open in Unity the DoTween plugin doesn't keep the setup (enabled and disabled modules). So because I'm using package manager stripping, the build fails.
Is there a way to correctly edit/apply the modules settings through code?
So then we will be able to do this setup during, maybe the PostImport or in PreBuild steps.
Or another option, during the reimport process the DoTweenEditor automatically setup itself if the Settings file is found?

Current DoTween version: 1.2.120 and DoTweenPro version: 1.0.065
Unity version 2018.2.8

**Comment by dantasulisses** [comment]
Looks like
            `DG.DOTweenEditor.UI.DOTweenUtilityWindowModules.ApplyModulesSettings();`
Does the work!

**Comment by Demigiant** [comment]
You were awesome to find it yourself, and sorry for the delayed answer (now useless) :) Cheers!

**Comment by tiagomartines11** [comment]
How did you solve this? When/how are you calling `DG.DOTweenEditor.UI.DOTweenUtilityWindowModules.ApplyModulesSettings();`?
