### ISSUE TITLE
Support for 3D Gizmos for path handles.

### ISSUE THREAD

**Issue by xCyborg** [Demigiant/dotween#26]
I would be good general ergonomical enhacement.
1.0.720

**Comment by Demigiant** [comment]
Hi,

You can set "Handles Type" to "Full" in DOTweenPath's Inspector to use 3D gizmos instead of the default free handles.

**Comment by xCyborg** [comment]
Also changing "Handle Mode" to perspective does the job, sorry for the inconvenience, a new user.
It's TERRIFIC by the way!

**Comment by Demigiant** [comment]
No worries, and I'm very glad you like it :)
