### ISSUE TITLE
Dotween Pro preview not reset to initial state

### ISSUE THREAD

**Issue by growold** [Demigiant/dotween#265]
While I set DotweenAnimation Component like image below, it won't set back to initial value when i press stop button
![_15415729451553](https://user-images.githubusercontent.com/1187526/48115684-b1c52e80-e29e-11e8-812f-6bfdaa5f7b2a.png)

key point: Loops set to 1 & Loop Type set to Yoyo mode & animation direction set to from mode

Unity Version: 2018.2.11f1
Dotween Pro version: 1.0.075
Dotween version: 1.2.135

**Comment by Demigiant** [comment]
Fixed! Will push to the Asset Store in a couple days :)
