### ISSUE TITLE
OnPlay on individual tween in Sequence is only called the first time through the sequence

### ISSUE THREAD

**Issue by StephenTriviumDev** [Demigiant/dotween#266]
I have a sequence and for one of the individual tweens, I want a function called when the tween plays, so I added a "OnPlay" callback onto that individual tween. However it is only called the first time the Sequence runs through, which seems counter to what OnPlay is suppose to do (be called each time the tween is played, or resumed from a paused state). OnStart would only be called the first time. Here's a snippet of my code:

            mainAnimation = DOTween.Sequence();
            mainAnimation.Append(this.largeCircleWithCone.DOScale(0, 1.5f));

            if(this.smallCircle0)
            {
                if(this.smallCircle0Video)
                {
                    mainAnimation.Append(this.smallCircle0.DOScale(1, 1f).SetDelay(-0.75f).OnPlay(this.smallCircle0Video.Play)); // OnPlay should play the video each time the tween starts however it doesn't, only called 1st time
                }
                else mainAnimation.Append(this.smallCircle0.DOScale(1, 1f).SetDelay(-0.75f));
                mainAnimation.Append(this.smallText0.DOFade(1, 0.75f));
                mainAnimation.Join(this.smallText0.rectTransform.DOAnchorPosY(75, 0.75f).From(true));
                mainAnimation.AppendInterval(UpdateScreensController.breadcrumbScreenTime);
                mainAnimation.Append(this.smallText0.DOFade(0, 0.75f));
                mainAnimation.Join(this.smallText0.rectTransform.DOAnchorPosY(75, 0.75f).SetRelative(true));
                mainAnimation.Append(this.smallCircle0.DOScale(0, 1f));

I could use an AppendCallback but the SetDelay makes that a bit messy, because I need the video to play when the tween starts, and doing an AppendCallback before this Append causes the video to play 0.75 seconds after the tween has started. I could do an InsertCallback after appending this tween and set the insertion point to be the current length of the sequence minus the length of the last tween... but I feel like that is a bit overkill and unclean, and I feel like this should work. Any thoughts? Possible bug or just the way that Sequences work?

**Comment by Demigiant** [comment]
Hi,

I must admit I never though of using OnPlay inside a nested Tweener. Since the nested Tweener is never paused after entering play-mode the first time (only the Sequence is paused), OnPlay doesn't repeat. I will think more about this, but there's no easy way to change this behaviour, so I'll probably update the docs to reflect this.

On a secondary note, I also see you're using a negative delay value. I didn't even think that would work, that's interesting.

**Comment by StephenTriviumDev** [comment]
Thanks for the quick response. I didn't realize the tween had to be paused and resumed for the OnPlay to be called (thought just having it "start over" would work). Perhaps you need to add another callback, "OnBegin" which is called each time the tweener is played from the beginning.

I got around the issue using this instead:
mainAnimation.InsertCallback(mainAnimation.Duration(false) - 1, this.smallCircle0Video.Play);

which isn't really that bad.

Yeah I wasn't sure the on delay being negative would work... but it does.

Thanks for taking a look, I really love DOTween, not sure how I could live without it.
