### ISSUE TITLE
Add support for RepeatDelay 

### ISSUE THREAD

**Issue by ehudros** [Demigiant/dotween#27]
Hey,
Loving DOTween and finding it very useful. However, one feature is sorely missing in my opinion - the ability to set a delay between repeats without having to use a sequence (with AddInterval).
I suggest either adding it as a parameter to SetLoops(loopAmount, LoopType, repeatDelay) or a separate SetRepeatDelay chained method.

Thanks!

**Comment by Demigiant** [comment]
Hi!

I thought about that, but I prefer to keep the repeat delay feature inside Sequences. It's a rarely used feature, and adding to a simple Tweener would make it heavier and slower (even if for a tiny amount, but, you know, I'm striving for efficiency everywhere).

Cheers,
Daniele

**Comment by ehudros** [comment]
Fair enough. It might be just our use case, but in our project it's a very common scenario.

Cheers :)

**Comment by Demigiant** [comment]
By the way, on a side note, you could also simulate a repeatDelay with a Tweener by using a custom AnimationCurve for ease, and setting the final part of the curve so it's even.

Cheers :)
