### ISSUE TITLE
[Enhancement] Showing Tweener/Sequence Id on DOTweenInspector

### ISSUE THREAD

**Issue by sp-alberto-uriarte** [Demigiant/dotween#270]
It would be great if the DOTweenInspector shows the Tweener/Sequence Id in the list of "Playing tweens" and "Paused tweens". Right now is hard to guess what sequences are paused or playing since the name in the list is only "[Sequence]". (For a Tweener is easier because it shows the name of the target)

Thanks!

**Comment by Demigiant** [comment]
[There you go](http://dotween.demigiant.com/download.php) (I also made it generally nicer) :)
