### ISSUE TITLE
DOTween Animation Autokill disable not working

### ISSUE THREAD

**Issue by thsbrown** [Demigiant/dotween#271]
I'm unable to play a DotweenAnimation on a gameobject twice. I thought this was originally due to the fact that autokill was checked, but disabling it has no effect. No matter what I can not play the animation twice.

**Comment by Demigiant** [comment]
I assume you're using DOPlay to replay the animation, but DOPlay just starts playing the animation from where it currently is. Use DORestart instead, which first rewinds it then plays it.
