### ISSUE TITLE
Negative TimeScale value results in loosing object reference

### ISSUE THREAD

**Issue by PascalSaP** [Demigiant/dotween#273]
Hello, 
i hope the title explains somehow whats the point. My aim is to dynamically change the timescale to play all animations forwards or backwards in a dynamic way. Therefore i change DOTween.timeScale by subtracting 0.01 every frame while a key is pressed. The tween goes slower every time, Until its 0 or less, then it stops. Tween.timeScale is still changed, but no animation occures. When adding a Rigidbody, the object gets affected by gravity, until timeScale returns to a positive value. Then the object jumps back to the old position and the animation goes on. To me it seems the reference is lost when timeScale is negative. Also the animation is stopped, because the object jumps back to the exact same location it was before.

Im using Unity 2018.2.16f1 and DOTween (HOTween v2) version 1.2.055

Minimalistic Code example: (add rigidbody to the object)
----------------------------------------------
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using DG.Tweening;
using System;

public class CubemovementDoTween : MonoBehaviour
{
    Tween myTween;
    void Start()
    {
        myTween = transform.DOMove(new Vector3(5, 5, 5), 25).SetAutoKill(false).SetUpdate(true);
    }

    void Update()
    {
        if (Input.GetKey(KeyCode.J))
        {
            DOTween.timeScale -= 0.01f;
        }
        if (Input.GetKey(KeyCode.K))
        {
            DOTween.timeScale += 0.01f;
        }
    }
}
```
--------------------------------------------

**Comment by Demigiant** [comment]
Took a while (and I forgot to report it here, sorry), but it's fixed in [the latest versions](http://dotween.demigiant.com/download.php) :)
