### ISSUE TITLE
Sequence not work with use only callbacks and without intervel or interval with value 0

### ISSUE THREAD

**Issue by OdareNNbI** [Demigiant/dotween#274]
Sequence not working, if append only callbacks with method sequence.AppendCallback() and don't use interval between callback sequence or use interval with value 0, example:
```
		Sequence seq = DOTween.Sequence();

		seq.AppendCallback(() =>
		   {
			   Debug.Log("test");
		   });
```
or 
	```
	seq.AppendInterval(0f).AppendCallback(() =>
		{
			Debug.Log("test");
		});
        ```
Expected result: callbacks invokes.
Actual result: callback don't invoke.

if I set interval at begin or end with value not 0, all will work 
```
	seq.AppendCallback(() =>
		{
			Debug.Log("test");
		}).AppendInterval(0.01f);

```

**Comment by Demigiant** [comment]
It's really cool that sometimes DOTween is used weirdly. But it's an animation engine, why have 0 duration Sequences made only of callbacks, argh! :D Jokes apart, I'll check this out (but will take a while because I'm working on a big-ish feature first which I have to finish).

**Comment by OdareNNbI** [comment]
Hi, thank you for answer. 
It's really possible. I set delays between callbacks in Unity inspector, and this delays - it's list, and delay can be 0. Make checking delay on 0 it's not cool and uncomfortable :( It's make code bigger and more incomprehensible

**Comment by Demigiant** [comment]
Forgot to update this, but in [the latest updates](http://dotween.demigiant.com/download.php) now 0 duration Sequences will correctly invoke callbacks :)
