### ISSUE TITLE
The issue is cause by that the Object Spawned before Unity's OnEnable Method

### ISSUE THREAD

**Issue by Rain624** [Demigiant/dotween#276]
When I use PoolManager.Pools[poolName].Spawn(object,object.position,object.rotation,object.parent),I found that object is enable before that object spawned in object.position.This will cause some question.I hope the issue that can be solved. Sorry, My English is very bad. I'm not sure you understand me.

**Comment by Demigiant** [comment]
Hi,
Forgot to reply sooner, sorry. I assume you're talking about an Asset called PoolManager and not about DOTween, so this is the wrong place (and I am not involved in PoolManager) :P
Cheers!
