### ISSUE TITLE
how to prevent kill an invalid tween?

### ISSUE THREAD

**Issue by armnotstrong** [Demigiant/dotween#285]
Hi,

I want to check if a tween is still active and playing then kill it. (cause I couldn't assign another movement through physics otherwise).

so I write code like this:
 ```
  if(centerStartTween != null && centerStartTween.IsPlaying())
   {
            centerStartTween.Kill();
   }
```

it should be noted that this may executed multi times.

The first time it executed was ok. but when called more than 2 times, everytime there will be complain about accessing a killed tween
```
This Tween has been killed and is now invalid
UnityEngine.Debug:LogWarning(Object)
```
I thought the check before kill it was safely enough. but it doesn't. So how could I do this?

**Comment by Demigiant** [comment]
Hi,

What is complaining is `centerStartTween.IsPlaying()`. You should set your `centerStartTween` reference to NULL when you kill the tween and then you will never reach that point :)

```
if(centerStartTween != null && centerStartTween.IsPlaying())
{
           centerStartTween.Kill();
           centerStartTween = null;
}
```

**Comment by armnotstrong** [comment]
thanks for the quick response, seems ok now!

**Comment by Estecka** [comment]
Hi, can I suggest adding a `IsValid()` or `IsDead()` method to tweens and sequences ?
This is the thing I intituively went looking for instead of setting variables to `null`.

**Comment by Demigiant** [comment]
Ahoy,

If you want to check if a tween is active (meaning it hasn't been killed) you can use [myTween.IsActive()](http://dotween.demigiant.com/documentation.php?api=IsActive) (works with both Tweeners and Sequences). But if your tween reference is NULL that will still fail, so just to be on the safe side you should check that too :P

**Comment by Estecka** [comment]
Hi !
No more problems here, I've been using `IsActive()` since then, and everything works perfectly.  
There is just this specific bit of code that I end up writting a lot in my scripts :
```
if (animation?.IsActive() ?? false)
	animation.Kill();
```
And by "a lot" I mean at least once for each monobehaviour that needs to animate.  

On my side I ended up writting my own Extension Method for this, so I just wanted to suggest integrating it. (Integrating it as an extension method rather than an actual member also has the interesting effect of preventing exceptions if the tweener you call it onto is null.)

**Comment by Demigiant** [comment]
Ahoy!
But `Kill` is already an extension method that doesn't generate exceptions :) When you call `myTween.Kill()` it will either kill an existing tween or just do nothing and throw no exceptions even if myTween is NULL (it might throw a warning if you set DOTween's logBehaviour to warnings though).

**Comment by Vivraan** [comment]
@Demigiant I am in a position where I called `TweenerCore<...>.Kill()` once in my code and later even removed the call to it, but the editor keeps on declaring that it's killed and invalid.

This happens when I try to cache my tween inside a Unity `IEnumerator` coroutine:
```cs
tween ??= DOTween.To(...).SetEase(...);
yield return tween.WaitForCompletion();
```

**Comment by Demigiant** [comment]
Ahoy @Vivraan,

I think the problem is that in your code you're assigning the "DOTween.To..." to your tween variable only if the variable isn't NULL (because you're using the "??=" null-coalescing assignment operator instead of a direct assignment—consider that once a tween you reference is killed it does not become NULL, because in C# that's impossible unless you NULL it yourself), and I guess instead it had a killed tween already assigned to it and that's why WaitForCompletion tells you it's not valid.

If that doesn't help, your console log should give you more info and you can share them here.

**Comment by Vivraan** [comment]
> Ahoy @Vivraan,
> 
> I think the problem is that in your code you're assigning the "DOTween.To..." to your tween variable only if the variable isn't NULL (because you're using the "??=" null-coalescing assignment operator instead of a direct assignment—consider that once a tween you reference is killed it does not become NULL, because in C# that's impossible unless you NULL it yourself), and I guess instead it had a killed tween already assigned to it and that's why WaitForCompletion tells you it's not valid.
> 
> If that doesn't help, your console log should give you more info and you can share them here.

Well, that was no help, sadly, since this was happening even when I was never calling nulling my tween reference explicitly in my code.

**Comment by scott-lin** [comment]
In case it helps anyone, I ran into this issue with the latest version as of writing (v1.2.705). I followed the suggested advice quoted below, but it did not work. In my scenario, I'm checking `IsComplete()` as opposed to `IsPlaying()`, but I suspect there's not a significant difference with respect to the warning `This Tween has been killed and is now invalid`.

> What is complaining is `centerStartTween.IsPlaying()`. You should set your `centerStartTween` reference to NULL when you kill the tween and then you will never reach that point :)
> 
> ```
> if(centerStartTween != null && centerStartTween.IsPlaying())
> {
>            centerStartTween.Kill();
>            centerStartTween = null;
> }
> ```

This code was still showing the warning when `IsComplete()` is called:
```
if ( this.Tween != null && !this.Tween.IsComplete() )
{
    this.Tween.Kill();
    this.Tween = null;
}
```

After I added the `IsActive()` check as below, the warning no longer was present.
```
if ( this.Tween != null && this.Tween.IsActive() && !this.Tween.IsComplete() )
{
    this.Tween.Kill();
    this.Tween = null;
}
```

Hope this helps.
