### ISSUE TITLE
OnComplete isn't called in cases where the origina and target values are equal

### ISSUE THREAD

**Issue by ehudros** [Demigiant/dotween#29]
Hi,
Unless I missed something, it looks like in cases where a tween is created but no actual movement needs to happen (the target value is the same as the original value) the tween is aborted and its callbacks are not called.
I'm guessing this is an intentional design choice? Doesn't it make more sense for the tween to be totally agnostic about such things and basically run as usual?

**Comment by Demigiant** [comment]
Hi,

The tween indeed doesn't care if there actual change or not, and it runs anyway and calls the callbacks. Maybe it's getting killed for other reasons (try to set LogBehaviour to Verbose to get more info).
