### ISSUE TITLE
Does SetAutoKill(false) tween needs to be manually killed?  

### ISSUE THREAD

**Issue by optimisez** [Demigiant/dotween#290]
Let's say I use transform.DOScale(Vector3.one, 0.3f).SetAutoKill(false). Does DOTween has any API to call to remove the tween from memory or the tween will be automatically removed after MonoBehaviour that uses the tween has been destroyed?

**Comment by Demigiant** [comment]
Tweens are not linked to MonoBehaviours or GameObjects, so if the tween is running and the target is destroyed you'll have to kill the tween manually.

Alternatively:
1. You can activate safe mode, which will kill the tween automatically (but only if it's running, not if it's paused) if it fails (which in this case would mean it tries to update while the transform is NULL)
2. You can use the new [SetLink](http://dotween.demigiant.com/documentation.php?api=SetLink) method and link the tween to the transform's gameObject, in which case the tween will be automatically killed when the gameObject is destroyed (even if it's not playing)

**Comment by optimisez** [comment]
Thanks for the rely. Btw do you mean kill the tween manually is getting the Tweener reference from any kind of tween you created such as transform.DOScale(Vector3.one, 0.3f).SetAutoKill(false).Pause() then call Kill() API?

**Comment by Demigiant** [comment]
Exactly, like:

```
myTween = transform.DOScale(Vector3.one, 0.3f).SetAutoKill(false).Pause();
// Later...
myTween.Kill();
```
