### ISSUE TITLE
Safe mode does not work when the target of a nested tween is destroyed.

### ISSUE THREAD

**Issue by TamuraKazunori** [Demigiant/dotween#291]
**Environment:**

DOTween v1.2.196
Unity 2018.3.0f2

**Code:**

```csharp
public class Test : MonoBehaviour
{
    [SerializeField]
    private Transform _tr1;
    [SerializeField]
    private Transform _tr2;
    [SerializeField]
    private Transform _tr3;

    void Start()
    {
        var seq = DOTween.Sequence();
        seq.Append(_tr1.DOLocalMoveX(100, 1));
        seq.Append(_tr2.DOLocalMoveX(100, 1));
        seq.Append(_tr3.DOLocalMoveX(100, 1));
        seq.OnUpdate(() => Debug.Log(_tr2.gameObject));
        seq.SetLoops(-1, LoopType.Yoyo);
    }
}
```

**How to reproduce it:**

While playing the tween in the above code, destroy the GameObject that contains `_tr2` in the hierarchy view.
Then the sequence keeps running though `_tr2` has been destroyed.
This is not reproduced in DOTween v1.1.710.
When I use v1.1.710, the sequence seems to be killed when it tries to tween `_tr2`.
In both environments, I check "Safe Mode" in the DOTween preferene window.

Is this change by design?

**Comment by Decavoid** [comment]
This behaviour was changed in v1.2.060 and not mentioned in the changelog. I think they should add a configurable setting "Kill sequence when nested tween fails".

**Comment by Demigiant** [comment]
Uh, you're right, somehow that didn't make into the changelog, sorry. I fixed that now.

I never thought that killing the whole Sequence would be a "wanted" behaviour, but I'm marking this as a todo.

**Comment by Demigiant** [comment]
Option added (v1.2.200) and committed. Gonna release it on DOTween's website as soon as I check a few other things.

**Comment by Demigiant** [comment]
Done, you can download the update [here](http://dotween.demigiant.com/download.php).

**Comment by Demigiant** [comment]
P.S. the option is "On Nested Tween Failure", selectable in DOTween Utility Panel if safe mode is active.

**Comment by TamuraKazunori** [comment]
Thank you for adding the option!
I will try to use it.
