### ISSUE TITLE
The variable is assigned but its value is never used

### ISSUE THREAD

**Issue by hershko** [Demigiant/dotween#292]
I upgraded my Unity project from DOTween v1.2.155 to DOTween v1.2.196 and I now see these warnings at the console:

```
Assets/DOTween/Modules/DOTweenModuleUtils.cs(59,24): warning CS0219: The variable `loadedAssemblies' is assigned but its value is never used
Assets/DOTween/Modules/DOTweenModuleUtils.cs(60,24): warning CS0219: The variable `mi' is assigned but its value is never used
```

I don't remember seeing any warnings before (i.e. on the older version).

**Comment by Demigiant** [comment]
Ouch, those are new, related to stuff inside a method I indeed don't use but added as a "storage system" to prevent stuff from being stripped with medium/high stripping levels on Android and other platforms. For some reason I'm not getting those warnings, but I'll fix them asap.

**Comment by Demigiant** [comment]
Done! You can download the fix [here](http://dotween.demigiant.com/download.php). Can you let me know if it indeed stops those warnings for you?

**Comment by hershko** [comment]
I think it's OK now (don't see the warnings anymore). Thanks!

________________________________

**Comment by Demigiant** [comment]
Great :)
