### ISSUE TITLE
Question regarding how to change the animation delay at runtime

### ISSUE THREAD

**Issue by Rud156** [Demigiant/dotween#295]
I have a tween made using the DoTween Editor of which I'm changing the animation delay value when running it.

I'm using
```cs
cardAnimation.delay = 0;
cardAnimation.DORestart();
```

to replay the animation after updating the `delay`. But updated delay value is not used. The initial delay that was set through the editor is being used.

Is there something else that I need to do to update the delay and replay the animation. 

### Edit:
I updated it so that I use a sequence. But now I have a different problem. Is there a way to start all the elements of a sequence animation at the same time. Looks like it executes it sequentially as the name suggests. Am I correct in assuming that I need to call them separately to have them play in parallelly.

**Comment by Demigiant** [comment]
Hi,

Glad you went with Sequences :) And nono, the name is confusing and I apologize, but elements in a Sequence don't need to be in a sequence: they can overlap. Other than Append, you can [Insert](http://dotween.demigiant.com/documentation.php?api=Insert) elements wherever you want, or [Join](http://dotween.demigiant.com/documentation.php?api=Join) them (insert them at the starting time of the last element that was added).

**Comment by Rud156** [comment]
OK. Thanks a lot.
