### ISSUE TITLE
Feature request: DoTweenAnimation extension

### ISSUE THREAD

**Issue by ghost** [Demigiant/dotween#297]
We extensively use DoTweenPro with DoTweenAnimation compoment in our project. We would like to extend it so we can use it for some of our custom components. For example, we would like to tween a CirlceRadiusController.radius parameter so that we can attach DoTweenAnimation component and choose a custom DoTweenAnimationType in the inspector, i.e. Radius. I dug into the code and looked into how tk2D and TextMeshPro plugins are integrated and managed to wire up things. Basically, modifying DoTweenAnimation.CreateTween method and added dictionary _CustomAnimationTypeToComponent in inspector. Final piece that is missing is being able to modify DOTweenAnimationType and TargetType enums so I can wire everything. Would it be difficult to expose those enums as editable files instead of being put into assembly? Thanks.

**Comment by Demigiant** [comment]
Ahoy!

Did it :) Can you write me via the address you find [here](https://assetstore.unity.com/publishers/1341) under the logo (please also attach DOTween Pro's invoice so I'm sure it's you) so I can send you an update to test?
