### ISSUE TITLE
Argument out of range TweenManager.cs:79

### ISSUE THREAD

**Issue by NautilusPara** [Demigiant/dotween#298]
Full stack trace:
[Exception] IndexOutOfRangeException: Array index is out of range.
TweenManager.GetTweener[Single,Single,FloatOptions]()    D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:79

DOTween.ApplyTo[Single,Single,FloatOptions]()    D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:981

DOTween.To()    D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:290

DOTweenModuleUI.DOFade()    Assets/Demigiant/DOTween/Modules/DOTweenModuleUI.cs:25

Sorry project is very complicated to find out how to repro this. Hope you can help to solve this issue ASAP. 

<3 :)

**Comment by Demigiant** [comment]
Agh! This should definitely not happen ever anymore :O But are you on the latest DOTween version([1.2.235](http://dotween.demigiant.com/download.php))?

**Comment by NautilusPara** [comment]
Thanks, I was in 1.2.055 ill update.

**Comment by NautilusPara** [comment]
Fixed 🥇  Thank you. Can close 👍
