### ISSUE TITLE
Can't kill a tween. Can't save a reference to a tweener.

### ISSUE THREAD

**Issue by vladislav-kostin** [Demigiant/dotween#301]
I have overlaping tweens resulting in ugly behaviour. But the old tween can't be killed. DoTween.Kill() returns 0 if I pass the target. 
```
scaleTweener = DOTween.To()......
id = scaleTweener.id;
```
**scaleTweener** there is always zero. So I can't get the id, or save the reference to call Kill() directly.

Am I doing something wrong?

**Comment by vladislav-kostin** [comment]
var id = DOTween.To(...).id ;

is always null;

 var id = DOTween.To(...).intId ;

is always -999;

The animation works though.

**Comment by Demigiant** [comment]
Hi,

Tween ids are set by the user, via the `SetId` chaining method. But if you want to store a reference to the tween and kill it you can simply use:

```
var myTween = DOTween.To(...);
// and later...
myTween.Kill();
```

**Comment by vladislav-kostin** [comment]
Yes I tried that and it didn't work. 

```
scaleTweener = DOTween.To(...);
Debug.Log(scaleTweener);
```

Was always null, I swear! :) I tried many times. Now I changed a lot of code and it works. But I'm certain it wasn't my mistake, I checked many times. Weird..

Thank you for such a quick reply!

**Comment by Demigiant** [comment]
Glad it's working now :) And if that didn't work there the only reason I can think of is you got a log telling you the tween wasn't created because of wrong data/elements. If you didn't get that log though it's very weird, because returning a tween reference is one of the core functionalities of DOTween and it's superimportant :O

**Comment by vladislav-kostin** [comment]
Yes, tween were created, animations worked, no errors. I turned off autokill, and it started giving me the tweener. But after that it started working with autokill on or off regardless.

**Comment by Demigiant** [comment]
I tried to crash it in various ways but I can't reproduce it (nor I ever saw such an error before). I guess it will remain a mystery as long as it's working for you again :P

**Comment by ghost** [comment]
Hi Demigiant, this question might be too new for this issue, but in case I have OnEnable() and OnDisable(), i set my DO.LocalRotate() inside OnEnable(), and as you mentioned above to store a reference with var only can be done inside one method, OnEnable. do you have any suggestion if i want to kill the tween inside the OnDisable() ? Thanks in advance
