### ISSUE TITLE
IL2CPP error on building

### ISSUE THREAD

**Issue by chmodseven** [Demigiant/dotween#302]
Hi Daniele,
I am getting this error when attempting an IL2CPP build for my iOS project:

IL2CPP error for type 'DG.Tweening.Plugins.SpiralPlugin' in SpiralPlugin.cs:48
Additional information: Invalid method 'null' found in vtable for 'DG.Tweening.Plugins.SpiralPlugin'

I have DOTween v1.2.235 and DOTween Pro v1.0.110.  I'm on Unity 2018.3.7f1.

**Comment by chmodseven** [comment]
Update: I have deleted the Demigiant folder and reinstalled DOTween Pro from the store and it seems to build out okay now.  Not sure what the issue was, but looks like the cleanout worked for now.

**Comment by Demigiant** [comment]
Ahoy! There's indeed a SpiralPlugin issue that I discovered a few days ago, where in rare cases and older non-clean versions this would happen. I'm pushing a fix to the Asset Store soon, but in the meantime glad the clean install worked :)

**Comment by suntabu** [comment]
@Demigiant  Happened again in my project, how to solve it, please help!!!!

**Comment by Demigiant** [comment]
@suntabu Answered you on the other issue you opened. It really shouldn't be this same issue because what caused it was solved, but please let me know :|
