### ISSUE TITLE
Incorrect collisions after rigidbody.DoMove

### ISSUE THREAD

**Issue by qzmp** [Demigiant/dotween#308]
When moving an object by rigidbody.DoMove colliders of its children are incorrect. They just don't update from original position. Behaviour changed in Unity 2018.3.10, was fine before.

If you want, I can sent a you simple project presenting the problem.

**Comment by Demigiant** [comment]
Hi,

If you want more collider precision when moving a rigidBody's transform you should also set the tween to use FixedUpdate:
```
myTween.SetUpdate(UpdateType.Fixed);
```

**Comment by qzmp** [comment]
Hey,
unfortunately your suggestion doesn't change the behaviour. The problem is that the colliders of the moving objects children are not updating at all during the tween.

I made a repo showing the behaviour: https://github.com/qzmp/CollisionTesting
After running the sample scene the plane will move, but the collider of cube on it will stay in place. Editor shows correct position but you can go throught it, move by WASD. It works like that only on Unity 2018.3.10 or later.

Maybe that's the issue with Unity, but moving the plane by Unity functions works fine.

**Comment by rwetzold** [comment]
Did you ever find a solution to this issue? I have the same right now in Unity 2021.1.3f

**Comment by qzmp** [comment]
Hey, 
It was a bug with Unity. After I submitted it, they wrote back that they fixed it in version 2019.1.7f1.
