### ISSUE TITLE
Duration of a tween with SetSpeedBased option is incorrect

### ISSUE THREAD

**Issue by s-h-a-r-d** [Demigiant/dotween#310]
When a new tween is created like this:
`Tween pathTween = transform.DOPath(path, constantSpeed, PathType.CatmullRom).SetSpeedBased();`

`pathTween.Duration()` returns that same constantSpeed variable, even though it might take much longer or shorter for that tween to finish.

**Comment by Demigiant** [comment]
A tween's SpeedBased duration is evaluated the moment the tween moves for the first time and is this initialized, which means the frame after the tween is created (unless it's paused at creation, in which case it's the frame after you call Play). But if you want to calculate the duration immediately, you can use `myTween.ForceInit()`.
