### ISSUE TITLE
Cannot build if using asmdefs generated by the UtilityPanel

### ISSUE THREAD

**Issue by nlebedenco** [Demigiant/dotween#315]
In DOTweenPro 1.0.145, after creating asmdefs using the Utility Panel the game cannot build anymore. This is due to the scripts in DOTweenPro/Editor being compiled in the assembly defined by the DOTweenPro.Scripts.asmdef above it. 

Editor folders are not handled specially if there is an asmdef anywhere in the parent chain. In order to fix it, I had to add an asmdef (DOTweenPro/Editor/DOTweenEditor.Scripts.asmdef) as follows: 

```json
{
    "name": "DOTweenProEditor.Scripts",
    "references": [
        "Unity.TextMeshPro",
        "DOTween.Modules",
        "DOTweenPro.Scripts"
    ],
    "optionalUnityReferences": [],
    "includePlatforms": [
        "Editor"
    ],
    "excludePlatforms": [],
    "allowUnsafeCode": false,
    "overrideReferences": false,
    "precompiledReferences": [],
    "autoReferenced": true,
    "defineConstraints": [],
    "versionDefines": []
}
```

**Comment by Demigiant** [comment]
Hi,

Sorry for this issue, I pushed a fix [here](http://dotween.demigiant.com/download.php) a couple days ago, and the Asset Store Pro version will be out soon (but if you upgrade DOTween from there that's all that's need to fix this).
