### ISSUE TITLE
AppendCallback not working in oncomplete function

### ISSUE THREAD

**Issue by KimYeonmu** [Demigiant/dotween#318]
![bug](https://user-images.githubusercontent.com/38003448/60560705-d4efa180-9d8b-11e9-9aeb-56804a0e0150.PNG)
![bug1](https://user-images.githubusercontent.com/38003448/60560706-d5883800-9d8b-11e9-870e-28b25da85471.PNG)

Why doesn't it work?

![fix](https://user-images.githubusercontent.com/38003448/60560751-15e7b600-9d8c-11e9-9b8d-2edb4682dbe5.PNG)
![fix2](https://user-images.githubusercontent.com/38003448/60560752-15e7b600-9d8c-11e9-9dfe-d4ec3dbc7a8e.PNG)

It works well in this case.

**Comment by KimYeonmu** [comment]
used Unity 2018.4.3f1, DOTween 1.2.250

**Comment by Demigiant** [comment]
Hi,

Thank you for the detailed pictures, that helped a lot :) The reason it doesn't work is that once a Sequence starts nothing can be appended to it anymore. If you create the Sequence outside the OnComplete it will then start the next frame, BEFORE OnComplete is called, even if empty.

Cheers,
Daniele

**Comment by Demigiant** [comment]
P.S. The appended DOMoveX doesn't work either in the first case, am I right? Because if it does then that's unexpected and something I should investigate.

**Comment by KimYeonmu** [comment]
yes. DOMoveX doesn't work... Thank you!
