### ISSUE TITLE
Can I set any userdata to a tweener and access it in the callbacks?

### ISSUE THREAD

**Issue by Jayatubi** [Demigiant/dotween#321]
I'd like to set some information when I play a tweener and then I could access them when the tweener's oncomplete callback fires.

**Comment by lordlycastle** [comment]
Sure. Use the `onComplete` callback. You can store whatever you wish in the callback.

**Comment by Demigiant** [comment]
And if you want to pass a parameter to the OnComplete callback you can use a lambda:
`myTween.onComplete(()=>MyMethod(someParameter));`
