### ISSUE TITLE
TextMeshPro DOText doesn't parse escape characters

### ISSUE THREAD

**Issue by mpb84** [Demigiant/dotween#324]
When using .DoText(" some text \n some more text", 1f) for example, the escape character isn't properly parsed.

I have insured that parse escape characters is turned on in the TMPRO script and any changes to the text in the editor cause the \n to be parsed as a new line properly.

**Comment by Demigiant** [comment]
Hi,

I just tested it to be on the safe side and it's working here. What do you mean that it's not properly parsed?

P.S. As a secondary note, if you're using TextMesh Pro and multi-line text, DOMaxVisibleCharacters is a better solution (but you'll have to determine the max visible characters you need first), because it doesn't increase the line count while it composes the text, but simply shows the existing characters one at a time.

**Comment by mpb84** [comment]
![image](https://user-images.githubusercontent.com/17381657/62531935-6d58c600-b811-11e9-88d9-dd97676a8e7b.png)


This text said sample text before I used .DOText("This escape character \n doesn't parse", 1f);

Then after I click into the input box and add a period...

![image](https://user-images.githubusercontent.com/17381657/62532045-94af9300-b811-11e9-82ef-0738c8ec04b3.png)

The character parses.

Since you can't reproduce it though I'll check this again in an empty project myself.

**Comment by mpb84** [comment]
Okay I found the issue.

calling .ForceMeshUpdate(); on the text in an update loop prevents it from properly parsing the characters.

I doubt this has anything to do with dotween so I'll close the issue.

**Comment by mpb84** [comment]
I'm really sorry but that was a false positive.

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
using DG.Tweening;

public class TMPROTest : MonoBehaviour
{
    public string SayThis = "some text \n some more text";
    public TextMeshPro text;

	// Use this for initialization
	void Start ()
    {
        StartCoroutine(SayDialogueCoroutine());
    }

    private void Update()
    {
        text.ForceMeshUpdate();
        text.GetRenderedValues();
    }


    public IEnumerator SayDialogueCoroutine()
    {
        yield return null;


        text.DOText(SayThis, 1f);


        yield return null;
    }
}
```


Try running this code. It seems like if you pass it a string as a variable it doesn't work.

Typing  .DOText(" some text \n some more text", 1f) does seem to work as intended

**Comment by mpb84** [comment]
Okay final thoughts,

This code doesn't work.

```
    public string SayThis; // This has to be written in the inspector to break it:  "some text \n some more text";
    public TextMeshPro text;

    void Start ()
    {
        StartCoroutine(SayDialogueCoroutine());
    }

    public IEnumerator SayDialogueCoroutine()
    {
        text.DOText(SayThis, 1f);

        yield return null;
    }
```


And this code does work.

```
    public string SayThis = "some text [n] some more text";
    public TextMeshPro text;

     void Start ()
    {
        StartCoroutine(SayDialogueCoroutine());
    }

    public IEnumerator SayDialogueCoroutine()
    {
        SayThis = SayThis.Replace("[n]", "\n");
        text.DOText(SayThis, 1f);

        yield return null;
    }
```


If you type an escape character into the inspector it doesn't work. But if you use a stand in for the escape character you want and replace it with the real one in the code it works.

I don't fully know what's going on but I still think this is Unity and TMPro's fault more so than DOTweens.


I'm going to reclose the issue. Hopefully this helps someone down the line.

**Comment by Demigiant** [comment]
Uhmm I just gave it more thought and I think I understand the issue now. When you write "\n" in the Inspector it actually writes "\\n", while instead if you do a search & replace for a stand-in you end up writing "\n" instead of "\\n". So that's one thing, but it still seems to behave weirdly. I believe it's not related to DOTween either, but I'll try to investigate too when I find the time :)

**Comment by BeregAl** [comment]
I fixed that with replacing \n with \u000a (UTF-16)

**Comment by PaulineB-Bylor** [comment]
A bit like @BeregAl, I used Replace(@"\n", "\n") to replace the literal \n with the escape character

**Comment by fralvarezz** [comment]
Hi, @Demigiant . Sorry to revive a years-long issue, but this has been the only result I have been able to find in Google when trying to find information about animating multi-line TMP text using DOText. In your very first response, you say that:

> P.S. As a secondary note, if you're using TextMesh Pro and multi-line text, DOMaxVisibleCharacters is a better solution (but you'll have to determine the max visible characters you need first), because it doesn't increase the line count while it composes the text, but simply shows the existing characters one at a time.

Which indeed does work great! I believe this information should be easier to find, and maybe somehow belongs in the documentation? I have seen multitude of games having problems with multi-line linebreaks when animating text, and this is a pretty straightforward solution to implement, so it would be sad that it is only contained in a response to a closed issue
