### ISSUE TITLE
Individual tweener manual Update

### ISSUE THREAD

**Issue by kultie** [Demigiant/dotween#325]
Checking the API have DOTween.Pause(tweener). Can we have somethings like DOTween.ManualUpdate(tweener)?
The ManualUpdate feature right now update all tweens that have UpdateType Manual

**Comment by Xriuk** [comment]
Yep, would need that!

**Comment by Xriuk** [comment]
https://github.com/Demigiant/dotween/issues/433#issuecomment-685525542 looking at this comment it seemed that you already added that @Demigiant , but I can't seem to find it. I'm using DOTween PRO btw

**Comment by fa1ntl1ght** [comment]
Same issue, this method presents in docs, but I can't find it in the assembly.
@Demigiant Would be nice to know happened with it

**Comment by Demigiant** [comment]
Ah, sorry, it's a Tween method, not a Tweener method. So you should store your Tweener reference as a generic Tween and then you have it :)

**Comment by kultie** [comment]
@Demigiant sorry for late reply, I've download DOTween version 1.2.632 but still cannot file the ManualUpdate method for Tween instance. 
![image](https://user-images.githubusercontent.com/20599099/147102377-97d75021-3128-4ffe-a795-9c5bff469750.png)

**Comment by Demigiant** [comment]
It's implemented as an extension method so you can't see it from the class inspection itself, but the code will allow you to write it
