### ISSUE TITLE
DG.DemiEditor not resolving.

### ISSUE THREAD

**Issue by jeremedia** [Demigiant/dotween#327]
The DG.DemiEditor namespace is not resolving in new projects. I can't determine why. I've attached a minimal example project that won't compile when with a DG.DemiEditor using directive.

[Example.zip](https://github.com/Demigiant/dotween/files/3479694/Example.zip)

**Comment by Demigiant** [comment]
Hi,

DemiEditor is an editor class, not a runtime class. That means that it behaves as regular Unity editor classes and can only be included/used in other editor code, not in runtime code :P

**Comment by jeremedia** [comment]
I know, I love and use this:


#if UNITY_EDITOR

DG.DOTweenEditor.DOTweenEditorPreview.PrepareTweenForPreview(rotateTween, false, true);

DG.DOTweenEditor.DOTweenEditorPreview.Start();

#endif


Throughout another project in monobehaviors without a problem. It's only in new projects that I can't access DG.DOTweentEditor. Is there any reason for this?

**Comment by jeremedia** [comment]
My project is huge and I do everything possible to not enter play mode. Everything works in the editor, including tweens since the inclusion of DOTweenEditorPreview. I must have something wired up that has enabled DG.DOTweenEditor access in non-editor scripts without issue.

Perhaps the way I have my assembly definitions set up... though in my code's ass-def I reference only DOTweenPro.Scripts.

**Comment by jeremedia** [comment]
Yeah, putting an assembly definition at the root of the Assets folder makes DG.DOTweenEditor available everywhere. I'm sure it's not considered best practice, but not having to write an editor class just to preview tweens outside play mode is very useful.
