### ISSUE TITLE
RotateMode.Fast equivalent for any float value

### ISSUE THREAD

**Issue by jquentin** [Demigiant/dotween#328]
I have a 360º float value that I want to tween using Dotween.To, and I want it to go the shortest way, like a DORotate in Fast mode.
What would be the way to achieve this?

**Comment by Demigiant** [comment]
Hi, [here's how DORotate works](https://github.com/Demigiant/dotween/blob/c8cc8dc6a789715f44611ed17a555982f34664b0/_DOTween.Assembly/DOTween/ShortcutExtensions.cs#L564-L570) by actually using a DOTween.To :)
