### ISSUE TITLE
dotween doesn't work when turning off domain reload in unity 2019.3 alpha

### ISSUE THREAD

**Issue by Pyromuffin** [Demigiant/dotween#329]
there's some static variables that dotween uses that aren't being reset with the new domain-reload-less unity workflow in 2019.3 alpha. It would be cool if dotween worked with it, because it saves hours of time waiting for playmode to start. I've had to switch to a different tweening library in the mean time.

**Comment by Demigiant** [comment]
Ahoy! I will be away until the end of the week, but as soon as I'm back I'll investigate and fix this :)

**Comment by Demigiant** [comment]
Fixed it in the latest [v1.2.270 version](http://dotween.demigiant.com/download.php) :) If you use it please let me know if everything works correctly on your side.

**Comment by Pyromuffin** [comment]
Looks like it works! Thanks!
