### ISSUE TITLE
Using dotween as a "package"

### ISSUE THREAD

**Issue by mjholtzem** [Demigiant/dotween#334]
I've been experimenting with Unity's new package manager stuff. I attempted to set dotween apart as its own package but it is not currently possible.

The dotween setup relies on loading assets from the Asset folder and since all the dotween code is now outside of the assets folder the path is no longer valid.

Not sure if you had any plans to distribute dotween as a package now that git repositories are getting supported in the package manager UI but just wanted to bring this to your attention.

**Comment by Razenpok** [comment]
#251?

**Comment by Demigiant** [comment]
Yes, closing it as duplicate and moving to #251  :P
