### ISSUE TITLE
How do do a consistent DOShakePosition each time?

### ISSUE THREAD

**Issue by nicmar** [Demigiant/dotween#340]
I want to shake an object using DOShakePosition, but the shake is random, sometimes big, and sometimes small. How can I have the exact same amount each time?

I tried SetLoops and LoopType.Restart, but it didn't make difference. Here's what I tried:

```cs
transform.DOShakePosition(effectDuration, new Vector3(shakeStrength,0,0), shakeVibrato, shakeRandomness).SetLoops(1, LoopType.Restart);
```

Is it possible, or do I need to make something custom?

Thanks!

**Comment by Demigiant** [comment]
Ahoy,

If you store a reference to your tween and restart the tween itself (myTween.Restart) each time, the shake will always be the same because it won't be recreated :)

**Comment by nicmar** [comment]
Thanks, but I'm trying to read the documentation how to store a reference to my tween, but I can't figure it out.

Also, how do I know how much/less shake there will be? Can I set a random seed or something? As it was random when running multiple times, i guess the one I store could also be random for each play of the game?

Thanks!

**Comment by Demigiant** [comment]
When you create a tween via a shortcut (or via `DOTween.To/Etc`) it also returns a reference to the tween itself, which you can store and reuse as long as you disable its auto-killing behaviour (`myTween.SetAutoKill(false)`) :)

Shake is completely random and there's no seeds, so the one you store will be repeated the same every time, but will be generated randomly the first, yes. If you want manual control on every shake the alternative (which I wouldn't recomment tho) would be to create a `Sequence` and manually append every shake iteration via `DOMove\DORotate\DOScale` methods.

**Comment by BeatlesCoder** [comment]
I have the same problem, usually I just need a fixed vibration amplitude, not random. Now DoShakePosition() seems to be random, but DoPunchPosition() can also be used to do vibrations, and with a fixed amplitude。Why DoShakePosition() must be random?

**Comment by Demigiant** [comment]
But a non-random shake is a Punch. Consider that the shake randomizes the positions/scale/rotations but the intensity does decrease in time (if you enable that with the "fadeOut" parameter).

**Comment by BeatlesCoder** [comment]
> But a non-random shake is a Punch. Consider that the shake randomizes the positions/scale/rotations but the intensity does decrease in time (if you enable that with the "fadeOut" parameter).

Oh~, I understand now. Thank you！
