### ISSUE TITLE
DOTweenPath copy/paste from clipboard bug

### ISSUE THREAD

**Issue by KosaJunior** [Demigiant/dotween#341]
Hello,
I have problem with copy-paste wpts in DOTweenPath.
When I copy and paste waypoint like: <68.6, 0.8, 647>, console gives me an error:
"ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

Parameter name: i
System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) (at <0079a30f96a047348857e1cecc6c638a>:0)
DG.DOTweenEditor.DOTweenPathInspector.PasteWaypointsFromClipboard () (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenProEditor/DOTweenPathInspector.cs:664)"

When copy Vector3 which only includes floats, ie.:
![image](https://user-images.githubusercontent.com/26622851/66722003-0bb46980-ee09-11e9-8a4e-89e45d8ebece.png)
After paste I get:
![image](https://user-images.githubusercontent.com/26622851/66722023-2d155580-ee09-11e9-84e8-5c505c2e71de.png)

DOTween v1.2.196
DOTweenPro v1.0.110
Unity 19.1.9f1

**Comment by Demigiant** [comment]
Ahoy!

Took me a while to understand what was happening, but I finally realized it's the commas and new versions of Unity localizing string representations of floats (which previously they didn't). Working on it.

**Comment by Demigiant** [comment]
Fixed :) Can you write me [from this contact form](https://www.demigiant.com/about.php) so I can send you an updated version while I work on other things before the Asset Store push?
