### ISSUE TITLE
I am pro user,please help!! IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by stkman** [Demigiant/dotween#342]
![image](https://user-images.githubusercontent.com/6999099/66814321-fce4c880-ef68-11e9-95ed-6e9ae7d6b1dd.png)

if kill some tween in OnDisable()  this bug should happen every time.

**Comment by Demigiant** [comment]
Hi,
Sorry for this bug, I am still verifying that I fixed it completely, but I should've. Could you download [this latest version of DOTween](http://dotween.demigiant.com/download.php) (just replace your DOTween folder with the contents of the ZIP) and let me know if everything works?

**Comment by stkman** [comment]
Ok i am trying this.
&nbsp;
------------------
 
闫鹏
 
Tel:15110174663
 
QQ:280759591
 
E-mail:last-time@qq.com

 &nbsp;


&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by stkman** [comment]
still error


my code ,&nbsp; and i want to rest transfrom state when a tween not play finished, but some error happen




&nbsp;private void OnDisable()
&nbsp;{
&nbsp; &nbsp; &nbsp; &nbsp; if (m_tweenAlpha != null &amp;&amp; m_tweenAlpha.active)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; m_tweenAlpha.Complete();
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; if (m_tweenScale != null &amp;&amp; m_tweenScale.active)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; m_tweenScale.Complete();
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; if (m_tweenPos != null &amp;&amp; m_tweenPos.active)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; m_tweenPos.Complete();
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; if (m_tweenRotate != null &amp;&amp; m_tweenRotate.active)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; m_tweenRotate.Complete();
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; if (m_tweenColor != null &amp;&amp; m_tweenColor.active)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; m_tweenColor.Complete();
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; &nbsp; if (agileData != null)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (m_resetOnDisable)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (agileData.usePos)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (agileData.posData.posType == MoveType.MoveToRelativePos || agileData.posData.posType == MoveType.MoveToTarget)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; transform.position = originalPos;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; transform.localPosition = originalLocalPos;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (agileData.useScale)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; transform.localScale = originalScale;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (agileData.useRotation)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; transform.localEulerAngles = originalRatate;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; m_resetOnDisable = false;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp;}



&nbsp;
------------------
 
闫鹏
 
Tel:15110174663
 
QQ:280759591
 
E-mail:last-time@qq.com

 &nbsp;


&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by stkman** [comment]
![image](https://user-images.githubusercontent.com/6999099/66818160-7bdcff80-ef6f-11e9-95d3-f9e07fdfad27.png)

still error

here is my code, i want to reset transform state when tween not play finished.

![image](https://user-images.githubusercontent.com/6999099/66818224-97480a80-ef6f-11e9-9c48-b9102a92919b.png)

**Comment by stkman** [comment]
for example, UISomeOne has a tween animation,if user close the UISomeOne,  the transform of tween has error state such as  position ,scale and so on,  so I need rest transform state when tween was hide or  destory.

**Comment by stkman** [comment]
by the way, please open and close UISomeOne very quickly,this bug should happened.

**Comment by Demigiant** [comment]
Could you paste here the whole content of the CS file, so I can see how the tweens are created? From the screenshots everything seems ok

**Comment by stkman** [comment]
[UIAgileObject.zip](https://github.com/Demigiant/dotween/files/3728937/UIAgileObject.zip)
this is my code, it's really long code..

**Comment by stkman** [comment]
Hi  is this bug fixed?

**Comment by Demigiant** [comment]
The issue you're having derives from some specific usage of DOTween which I can't replicate (your CS file didn't help). I'm working on it, but if you could replicate the issue in a barebone project and send it to me it would be great.

**Comment by stkman** [comment]
OK, i will send you a test project later

**Comment by Demigiant** [comment]
Thank you. I replicated a similar environment where tweens were auto-completed OnDisable, but everything works here, so a test project would be great :)

**Comment by Demigiant** [comment]
Hey, for whomever still has the issue, [the latest version of DOTween](http://dotween.demigiant.com/download.php) should fix it forever.

**Comment by forawolf42** [comment]
thanks
