### ISSUE TITLE
[Feature request] Empty callback tween

### ISSUE THREAD

**Issue by Romaleks360** [Demigiant/dotween#348]
Sometimes I want to use DOTween just for playing some delayed actions, like calling functions or lambdas after a few seconds. Without DOTween I have to use Invoke() or create IEnumerators, which is really annoying. There's a very useful .OnComplete() feature, but currently, I have to animate some fictional property to use it with .Delay() (as far as I understand). It would be great to have such a feature provided - something like DOTween.Do(action).SetDelay().etc

**Comment by Demigiant** [comment]
If I understood correctly, you want [DOVirtual.DelayedCall](http://dotween.demigiant.com/documentation.php?api=DOVirtual.Delayed) :)
