### ISSUE TITLE
[BUG] Exception is thrown randomly when a scene is loaded.

### ISSUE THREAD

**Issue by Davidnovarro** [Demigiant/dotween#349]
I'm using Pro version, it throws this exception randomly when a new scene is loaded. Though I'm not sure what may cause the exception.
Please fix it.

IndexOutOfRangeException: Index was outside the bounds of the array.
DG.Tweening.Core.TweenManager.ReorganizeActiveTweens () (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:1042)
DG.Tweening.Core.TweenManager.Update (DG.Tweening.UpdateType updateType, System.Single deltaTime, System.Single independentTime) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:402)
DG.Tweening.Core.DOTweenComponent.Update () (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:73)

**Comment by Demigiant** [comment]
Hi David,

Sorry for the delayed reply but I had some email problems. If you press
"Check for Updates" in DOTween Utility Panel and get the latest version it
will fix this error (just replace the DOTween folder with the ZIP
contents). Will push it to the Asset Store asap.

Cheers,
Daniele

**Comment by Demigiant** [comment]
Hi David,

Sorry for the delayed reply but I had some email problems. If you press "Check for Updates" in DOTween Utility Panel and get the latest version (1.2.305) it will fix this error (just replace the DOTween folder with the ZIP contents). Will push it to the Asset Store asap.

Cheers,
Daniele
