### ISSUE TITLE
timescale issue

### ISSUE THREAD

**Issue by mackysoft** [Demigiant/dotween#351]
### Environment
- Unity 2019.2.15f
- DOTween v1.2.305
- DOTween v1.0.175
- DOTween preferences is default.

### How to reproduce
1. Call the Move(Vector3) method.
2. Set the timescale of tween to 0 during the tween. (The starting timescale is 1)
3. Set timescale of tween to 1, 

### What will happen
Tween remains stopped.

### Code
``` cs
public void Move (Vector3 position) {
	var tween = transform.DOJump(position,power,steps,duration).OnComplete(Complete);
	tween.OnUpdate(() => tween.timeScale = m_Timeline.timeScale);
}
```

**Comment by mackysoft** [comment]
Was self resolved.

When the tween timescale is set to 0, OnUpdate seems not to be called.

**Comment by DanTulovsky** [comment]
Is this working as expected?  I ran into this as well. What is the best workaround for this? I ended up checking in the main Update() function if timeScale has change, and resetting the tween's timescale. Is there a better way?

**Comment by mackysoft** [comment]
As far as I know, you need to use `MonoBehaviour.Update()` or something similar to observe and change the timeScale.

**Comment by DanTulovsky** [comment]
Ok thanks, that is what I ended up doing.
