### ISSUE TITLE
[Feature] Unity's Vector Graphics support

### ISSUE THREAD

**Issue by flow38** [Demigiant/dotween#352]
Hello,

I'm struggle to tween the color (or the alpha) of a SVGImage component ([from unity's vector graphics lib](https://docs.unity3d.com/Packages/com.unity.vectorgraphics@1.0/manual/index.html)). DoColor and DoFade shortcurts are both availables on  SVGImage components but do not work as expected at runtime: svg become instantly white.

I know Vector Graphics is a in preview but do you have any plan for support it ?

Best regards

Florent

**Comment by Demigiant** [comment]
Ahoy!

I will certainly add shortcuts for the vector graphics lib, but in the meantime remember that even without pre-existing shortcuts you can tween anything you want with the [generic mode](http://dotween.demigiant.com/documentation.php#creatingTweener) :)

**Comment by flow38** [comment]
Hi, just to inform you that the DOColor shortcut already works when I use a Color constant (e.g. Color.Red) but not when I use a custom color via the Color constructor (e.g. new Color(redVal, greenVal, blueVal)). In second scenario the SVG become white (as explained in my first message). Not sure if it's relative to DOTween or to Vector Graphics lib !!!

Anyway, thank you for your fantastic tool ;)

**Comment by Demigiant** [comment]
That is very weird then :B Could I ask you if you can create a sample package that replicates this issue so I can check it out (I imported the Vector Graphics package but I'm having a little trouble understanding it on the fly :P)?

**Comment by flow38** [comment]
Yes the lack of [documentation](https://docs.unity3d.com/Packages/com.unity.vectorgraphics@2.0/manual/index.html) is a shame ! 

Please find below a project with 4 usecases:

**SpriteRenderer usecases :**
SpriteRenderer 's "sprite" properties are set with a svg import as "VectorSprite".
One where DoColor is done with endValue set to Color.red and the other where endValue is a "custom" color.

**SVGImage usecases (UI) :**
SVGImage 's "source SVG Image" properties are set with a svg import as "UI SVGImage".
One where DoColor is done with endValue set to Color.red and the other where endValue is a "custom" color.

DoColor tweens are created and played in Start() of  DoColor_SVGImage and DoColor_SpriteRender scripts, so you just need to open the scene "Issue" and press play !

Unity 2019.2.13- LRWP 6.9.2 - Vector Graphics 2.0.0-preview.11 - DOTween 1.2.305
[Project](https://drive.google.com/open?id=1HW_GAyBr1GLLhD0UCefwfcgy7x7L0qIg)

**Comment by Demigiant** [comment]
Ahoy! Thank you for the very detailed project :) The problem was simpler than we thought. When you're setting a custom Color you're setting it the wrong way. In Unity, Color parameters go from 0 to 1, not from 0 to 255. So you were forcing a white color every time.

**Comment by Demigiant** [comment]
P.S. Try setting this as Color and you'll see it working :)
`new Color(0.75f, 0.24f, 0.6f)`

**Comment by flow38** [comment]
OMG I'm so sorry, I will never get used to this normalized way of expressing a color value ! 
Thank for having pointed out my error! Have a nice day and a happy new year too !
Ciao!
