### ISSUE TITLE
DOTween not compatible with Unity's new Playmode options feature

### ISSUE THREAD

**Issue by wilczarzgit** [Demigiant/dotween#354]
Hi Daniele, 
I would like to let you know that I've tried Unity's new "Playmode options" feature and DOTween gave me some trouble. I think it should be easy to fix for you, and it might be worth checking out.

So if you don't know, Playmode options allows to skip one or both of these two steps:
1) Domain reloading
2) Scene reloading

Most of the cases only step one is enough to drastically cut the time of entering the playmode (even 10 times faster, like below one second for me!) You can read about it here:

https://blogs.unity3d.com/2019/11/05/enter-play-mode-faster-in-unity-2019-3/
https://forum.unity.com/threads/configurable-enter-play-mode.768689/ 

In these short articles you can see that all you need to do is to take care of static stuff in your classes, which means cleaning them in a special way. So in order for my game to work with this feature, I needed to make two things:

1) Add this class to my project:
```
    public class StaticGuard
    {
        [RuntimeInitializeOnLoadMethod]
        static void Init()
        {
            DOTween.KillAll();
        }
    }
```

2. Add DOTween Manager to my scenes. I am not sure why this was required, but it worked. However the component has a big warning that DOTween should initialize itself. And I agree, I would rather not have it in my scenes :) 

Do you think you can add a class like this to DOTween that would clear the static stuff in a proper way? I really think this shouldn't be a difficult task. 

Thanks,
Tom

PS. DOTween continues to be the best asset in the store :)

**Comment by Demigiant** [comment]
Ahoy! :) Are you sure you're using [the last DOTween version](http://dotween.demigiant.com/download.php)? Unless Unity changed something again, I added support for the new playmode options in v1.2.270 :P

**Comment by StudioKucma** [comment]
Hi there,
So yeah.. I was on 1.2.250. But I updated for sure before testing it out! This must have been of the cases when Asset Store serves some older version of asset. It happens to me quite often I don't know why (not only with DOTween) :/

Anyway.. playmode options work just fine with newest version so you can close this ticket :)
Tom

**Comment by Demigiant** [comment]
Great! :) And yeah, the Asset Store goes crazy sometimes :|

**Comment by shredder2500** [comment]
Seems to be broken on version 1.2.632. My exact issue was calling `transform.DoComplete()` was throwing trying to access after already destroyed error. Adding the above Kill All call on RuntimeInitializeOnLoadMethod fixed the issue
