### ISSUE TITLE
DOColor, and other material tweens change the .mat file

### ISSUE THREAD

**Issue by alerad** [Demigiant/dotween#356]
Is there any way to avoid this? 

Sorry for using this  as a forum, but couldn't find the answer anywhere.

**Comment by Demigiant** [comment]
Hi :)

It depends on what material reference you're using. DOColor, when used with materials, changes the color property of a material (exactly as if you change it directly, except it does it every frame while it's active). So if you apply it to your `Renderer.sharedMaterial` it will change that material color for the whole project, and if instead you apply it to your `Renderer.material` it will only change the color for the specific Renderer (but the first time you access it it will create a clone of that material). You can read more [here](https://docs.unity3d.com/ScriptReference/Renderer-sharedMaterial.html).
