### ISSUE TITLE
DoTween.To() is not reaching target value

### ISSUE THREAD

**Issue by ivankras** [Demigiant/dotween#358]
I have the following line (where _score, x and target_ are "long"):

`Tween t = DOTween.To(() => _score, x => _score = x, target, transitionTime).OnUpdate(() => myText.text = _score.ToString("C0"));`  

For instance: in the particular case in which _score is initially 0 and target is 999,999,999,999,999 the _score gets stuck at 999,999,986,991,104 (always the same value).

**Comment by ivankras** [comment]
https://forum.unity.com/threads/dotween-hotween-v2-a-unity-tween-engine.260692/page-24

Here *agstanescu* experiences the same problem and describes it better:

> I am using the generic To(getter, setter...) method. The provided setter simply ignores values until time accumulates to X milliseconds and then it actually sets the value to the object. It resets the time counter and repeats.
There is a small catch that the setter might not be called an exact number of times and the object might never be set to the end value (the last set value might be ignored). To fix this, in the custom setter I also store the last value the Tweener tried to set, and onComplete I set this value to the object.

**Comment by bestnet** [comment]
I have the same issue is there any solution yet?

**Comment by ivankras** [comment]
> I have the same issue is there any solution yet?

No. I had to understand that the `DoTween.To()` was just an animation feature, so I set the value manually at the event `OnComplete()`. Didn't like it very much, but was enough for my purpose (animation -> final value)

**Comment by alexxB** [comment]
I ran into the same. Shouldn't it be reliable that the final intended value is reached?
Is there maybe a switch I haven't seen which ensures it?
(Besides mentioning DoTween is extremely cool and helpful and Daniele a hero for maintaining it in even a free version)

**Comment by xucian** [comment]
is this still happening?

**Comment by Demigiant** [comment]
Ahoy! Sorry if I missed this before, but this definitely shouldn't be happening because, if the tween has reached completion, I force it to its last value (though I might've added this after the reports). Please let me know if it's happening with the latest version and let me know the code you're using (I just tested to be sure and it works correctly), in which case I'll reopen the thread.

**Comment by alexxB** [comment]
Hi Daniele,

that bug actually still exists in v1.2.705.

```
DOTween.To(() => scale, x => scale = x, scale, drawingDuration)
    .From(Vector3.zero)
    .SetDelay(drawingDelay)
    .SetEase(Ease.OutBack)
    .OnPlay(() => { clipManager.Play("BlockerScale", transform.position); })
    .OnComplete(() => 
        { 
            // DoTween bugfix
            TransformBlockerParts();
        }
    );
```
That is the code that fails for me without the fix in the OnComplete()

Cheers

Alex

**Comment by Aspharr86** [comment]
I have the same issue, but in different situation.
When I tested in an empty scene, always got expected result:
```
public TextMeshProUGUI text;
private long fromValue = 0;   // Starting value
private long endValue = 10000000;   // Ending value
private float duration = 0.5f;   // Duration of the animation

// ...
DOTween.To(() => fromValue, x => fromValue = x, endValue, duration)
.OnUpdate(() =>
{
    text.text = fromValue.ToString("N0");
})
.OnComplete(() =>
{
    Debug.LogWarning("Completed, fromValue: " + fromValue);
    Debug.LogWarning("Completed, endValue: " + endValue);
    text.text = endValue.ToString("N0");
});
// ...
```
![image](https://user-images.githubusercontent.com/82156567/231343248-e79960d8-278f-45eb-83e2-4345ec1d7c09.png)
![image](https://user-images.githubusercontent.com/82156567/231341451-63fa3795-301b-4a2c-a8ac-5241b95bef14.png)

But in my company project, sometimes got unexpected result:
(The tween count is changing during executing above code)
![image](https://user-images.githubusercontent.com/82156567/231344010-0cdd4761-e252-41ec-9e12-bf79a8058332.png)
![image](https://user-images.githubusercontent.com/82156567/231341274-3632f33a-b7ba-4a72-ad12-e300005f7808.png)

**Comment by DragonMinK** [comment]
I have the same issue. In Unity Editor, the final value is always equal to endValue.
When running on Windows Standalone, the final value exceeds endValue.

So, I'm using the following code, but if there is a better idea, please let me know.
`
static public class DOTweenExt
{
    public static Tween To(DOGetter<long> getter, DOSetter<long> setter, long endValue, float duration)
    {
        long startValue = getter();
        DOSetter<long> boundedSetter =
            (val) =>
            {
                if (val > startValue && val > endValue) setter(endValue);
                else if (val < startValue && val < endValue) setter(endValue);
                else setter(val);
            };
        Tween tween = DOTween.To(getter, boundedSetter, endValue, duration).OnComplete(() => setter(endValue));
        return DOTween.Sequence().Append(tween);
    }
}
`

**Comment by DragonMinK** [comment]
I am experiencing the same issue where in Unity Editor, the final value is always equal to endValue, but when running on Windows Standalone, the final value does not reach endValue. I am currently using the following code, but if there is a better solution, please let me know.

```c#
static public class DOTweenExt
{
    public static Tween To(DOGetter<long> getter, DOSetter<long> setter, long endValue, float duration)
    {
        long startValue = getter();
        DOSetter<long> boundedSetter =
            (val) =>
            {
                if (val > startValue && val > endValue) setter(endValue);
                else if (val < startValue && val < endValue) setter(endValue);
                else setter(val);
            };
        Tween tween = DOTween.To(getter, boundedSetter, endValue, duration).OnComplete(() => setter(endValue));
        return DOTween.Sequence().Append(tween);
    }
}
```

**Comment by eric-zhu94** [comment]
I had a similar issue and setting my endValue and duration variables as static worked. When it was not static it would stop at a different fixed value and duration for some reason.
