### ISSUE TITLE
Appending / Inserting a Sequence to another paused Sequence prevents future modifications

### ISSUE THREAD

**Issue by ghost** [Demigiant/dotween#36]
**What steps will reproduce the problem?**

```
Sequence rootSequence = DOTween.Sequence();
rootSequence.Pause();

Sequence Seq = DOTween.Sequence();
rootSequence.Append (Seq);

Seq.InsertCallback(1, delegate { Debug.Log ("My test callback!"); });

rootSequence.OnComplete(delegate {
    Debug.Log ("Sequence is complete");
});

rootSequence.Play();
```

The callback is never called, neither the OnComplete delegate.

**What is the expected output? What do you see instead?**
As rootSequence is paused (and therefore Seq), I should be able to Append/Insert new elements to both sequences, but it is not the case and nothing happens.

**What version of the product are you using?**
DOTween v1.0.800

**Workaround**
Add Seq to rootSequence just before playing it.

```
Sequence rootSequence = DOTween.Sequence();
rootSequence.Pause();

rootSequence.OnComplete(delegate {
    Debug.Log ("Sequence is complete");
});

Sequence Seq = DOTween.Sequence();
Seq.InsertCallback(1, delegate { Debug.Log ("My test callback!"); });
rootSequence.Append (Seq);

rootSequence.Play();
```

**Comment by Demigiant** [comment]
The issue here is that, once you add something to a Sequence, it becomes locked. That's because a Sequence needs to know the full duration and contents of another nested tween/sequence when it adds it, so that subsequent Append/Insert/etc methods can add stuff at the right position.
