### ISSUE TITLE
Extra DOTweenComponent spawned in hierarchy after assembly reload

### ISSUE THREAD

**Issue by aybe** [Demigiant/dotween#360]
Whenever I update my code during play mode, I noticed that an extra instance of `DOTweenComponent` is spawned in hierarchy after assembly reload:

![Unity_2020-01-08_22-16-22](https://user-images.githubusercontent.com/1537591/72016665-8522f300-3264-11ea-807f-e35d5ca99096.png)

Is this something to worry about or can be safely ignored ?

PS I don't do anything fancy, just using `DOTween.To`

Thank you !

**Comment by lordlycastle** [comment]
Default behavior is that this shouldn't happen. Something is happening in your project that is causing this. Can't help without more info.

**Comment by Demigiant** [comment]
I would really recommend never to update code in Play Mode: it simply never works with anything :P Other than that, if you're on DOTween older than 1.2.270 an update might solve it.

**Comment by lordlycastle** [comment]
Newer Unity versions also has new features to not reload changed code until you exit play mode.

**Comment by aybe** [comment]
OK x2
