### ISSUE TITLE
Utility panel height is too small on 2019.3+

### ISSUE THREAD

**Issue by aybe** [Demigiant/dotween#361]
As you can see, some options are not visible:

![Unity_2020-01-09_00-09-45](https://user-images.githubusercontent.com/1537591/72023913-6593c680-3274-11ea-9f9e-8c82f435e717.png)

**Comment by Demigiant** [comment]
Ahoy! Are you using [the last version of DOTween](http://dotween.demigiant.com/download.php)? I did update the height a couple commits ago (but didn't push it on the Asset Store yet).

**Comment by aybe** [comment]
I thought I was (1.2.235) but in fact no, the package manager does not seem to be able to guess there's a newer version.

Edit: 

I could effectively upgrade it by downloading it directly from your website and problem is fixed!

For the sake of clarity, I opened #362

Thanks :)
