### ISSUE TITLE
Unity's Package Manager is not able to fetch last version

### ISSUE THREAD

**Issue by aybe** [Demigiant/dotween#362]
Even though asset store shows last version:

![chrome_2020-01-09_03-35-09](https://user-images.githubusercontent.com/1537591/72032919-1314d300-3291-11ea-9d76-45e885cc1e40.png)

The package manager is irremediably stuck to the version the time I added it:

![2020-01-09_03-32-58](https://user-images.githubusercontent.com/1537591/72032802-c5986600-3290-11ea-8819-ce23f796fc92.png)

TL;DR; impossible to update through official way

**Comment by Demigiant** [comment]
The package manager is not the official way yet but still in alpha sadly, and I have no influence over how Unity uses it :P

**Comment by aybe** [comment]
Alright, thanks anyway!

Le 9 janv. 2020 12:05, Daniele Giardini <notifications@github.com> a écrit :

The package manager is not the official way yet but still in alpha sadly, and I have no influence over how Unity uses it :P
