### ISSUE TITLE
Calling GoTo() crashes Unity Editor

### ISSUE THREAD

**Issue by birdkingz** [Demigiant/dotween#363]
```
if (m_tweener == null)
        {
            m_tweener = DOTween.To(() => m_currentAngle, newAngle => m_currentAngle = newAngle, m_targetAngle, m_duration)
                        .SetUpdate(UpdateType.Fixed)
                        .SetEase(Ease.Linear)
                        .SetAutoKill(false)
                        .OnUpdate(OnTweenUpdated)
                        .OnComplete(OnTweenCompleted)
                        .OnRewind(OnTweenCompleted);
           m_tweener.Goto(0.5f, true); // this crashes the Editor
        }
```

Is this a bug?
Any idea how can I use Goto() without waiting the tweener completed its tween?

What I'm trying to achieve is 
I have multiple objects moving from from (-10, 0) to (10, 0), but I want them to start from a randomized point along the tweening. I thought Goto() fits my need but unfortunately the crash makes it totally not useable.

Please advise.

**Comment by Demigiant** [comment]
Ahoy!

Goto definitely fits what you'd like to do and should definitely not crash the editor: it's been super tested so I'd assume it's something else, like what's happening in your OnTweenUpdated method?

**Comment by birdkingz** [comment]
I should have posted more codes.

```
public void Move(bool isReversed)
    {
        if (m_tweener == null)
        {
            m_currentAngle = 0.0f;
            m_tweener = DOTween.To(() => m_currentAngle, newAngle => m_currentAngle = newAngle, m_targetAngle, m_duration)
                        .SetUpdate(UpdateType.Fixed)
                        .SetEase(Ease.Linear)
                        .SetAutoKill(false)

            float anglePerSec = m_targetAngle / m_duration;
            float startTime = m_currentAngle / anglePerSec;
            m_tweener.Goto(startTime , true);
        }

         if (!isReversed)
         {
             m_tweener.Restart();
         }
         else
         {
             m_tweener.PlayBackwards();
         }
    }
```

This crashes the Editor.

**Comment by birdkingz** [comment]
I found out that if I don't call Restart or `PlayBackwards `after `Goto `then it won't crash the Editor.
But I still I just don't understand what does the `Goto `doing behind the scene. 

I'm tweening multiple objects to move in a circular form. All of them share the same duration
(5 secs to complete a circle, 360 deg). But I want them to start from different angle.

For example:
ObjectA starts from 0 deg, so I'm expecting it to reach 360 deg at 5sec time.
ObjectB starts from 180 deg, so I'm expecting it to reach 360 deg at 2.5sec time.

also I noticed after `Goto `completed its tween, whenever I call `Restart`, the objectB doesn't restart from 0 deg, instead of it jumps to 180 deg.

Notice my code that I set the tween from 0 deg to 360 deg.
`m_currentAngle = 0.0f;`
`m_targetAngle = 360.0f`

**Comment by Demigiant** [comment]
I tested that code to be on the safe side and it doesn't crash the editor. As I said, I would really recommend you to check what's happening around the tween because I'm pretty sure it's not the tween engine that's crashing Unity, but some other surrounding code. Like I said, you're using a OnUpdate/Complete/Rewind to act on the tweened values, so probably something is creating an errror there. Or, if this simple code above crashes your project, maybe you're calling it in a loop and generating a stackOverflowException?

**Comment by birdkingz** [comment]
Hmm after I rewrote my codes then I don't see it crashes anymore. Although I'm not really sure which part of my codes causing it to crash.
Anyway, thanks for the help.
