### ISSUE TITLE
DOTweenPath.DOGoto not working

### ISSUE THREAD

**Issue by Trisibo** [Demigiant/dotween#367]
I'm trying to use the `DOGoto` method on a `DOTweenPath` instance, but it doesn't seem to do anything. However, `DOTween.Goto` works.

```
DOTween.Goto(path.tween.target, 1, true);  // This works.
path.DOGoto(1, true);  // This doesn't work.
```

**Comment by Demigiant** [comment]
DOGoto is an extension method that works directly on a tween's target (contrary to the dynamic Goto which is a tween's method). So you should call:
`path.tween.target.DOGoto(1, true);`
or store the path tween (`path.GetTween()`) and use this;:
`myPathTween.Goto(1, true);`
