### ISSUE TITLE
DOAlpha -> CanvasGroup

### ISSUE THREAD

**Issue by frankvdb7** [Demigiant/dotween#37]
It would be nice if a DOAlpha shortcut is added to the CanvasGroup UI component (Unity 4.6+). 

EDIT:
My bad, DOFade is the function I mentioned, which is already implemented :+1:!

**Comment by Demigiant** [comment]
Hi,

Check out [DOFade](http://dotween.demigiant.com/documentation.php?api=DOFade__4), it's the same thing ;)

**Comment by Darkfafi** [comment]
Its gone in the new version..

**Comment by Demigiant** [comment]
You probably reimported DOTween and didn't re-run the setup, so the DOTween46.dll has not been unpacked ;)

**Comment by Darkfafi** [comment]
You are right. Thank you!
