### ISSUE TITLE
Non-managed DOTweenAnimation unresponsive to play methods while game object is disabled or immediately following OnEnable

### ISSUE THREAD

**Issue by HG-Dev** [Demigiant/dotween#373]
Hi. I'm attempting to use DOTween to improve upon the basic Toggle, using an array of DOTweenAnimation components to play the activate/deactivate animations for a toggle. One functional requirement I have is the ability to change the appearance of the toggle to the end state of its activation tween while its GameObject is disabled, or at least before anybody notices during OnEnable. However, as seen below, I'm having trouble getting the DOTweenAnimation components to budge during either of these periods: the middle toggle (which was left alone when this panel was switched to) should look like the toggle below it, which I manually clicked on to play backwards, then forwards. The color change is not a tween, which is why it's unaffected.

![image](https://user-images.githubusercontent.com/29112495/74407592-a5525d00-4e75-11ea-82c8-14f2141ed9f4.png)

Because the DOTweenAnimations are modified by the toggle and not by enabling/disabling, they're driven entirely by the Toggle's PlayEffect method.
```csharp
for (int i = 0; i < animations.Length; i++)
{
    if (!instant)
    {
        if (isOn)
            animations[i].DOPlayForward();
        else
            animations[i].DOPlayBackwards();
    }
    else
    {
        if (isOn)
            animations[i].DOComplete();
        else
            animations[i].DORewind();
    }                
}
```
Both DOComplete and DORewind successfully operate the DOTweenAnimation when I used the "restore defaults" button, not pictured.

Have any ideas how I could force a DOTweenAnimation to jump to its end state while its parent game object is disabled?

**Comment by HG-Dev** [comment]
I have successfully reproduced the problem. Requires importing the Demigiant DOTween asset folder.
[ToggledTweenDemonstration.zip](https://github.com/Demigiant/dotween/files/4197545/ToggledTweenDemonstration.zip)
EDIT: This problem may have been resolved with the latest update to DOTween. After upgrading, I can't reproduce the problem in this sample project.

**Comment by HG-Dev** [comment]
Yup, it's resolved. Great timing on that update!

**Comment by Demigiant** [comment]
Ahoy! Glad it was solved so fast :)
