### ISSUE TITLE
How to add OnComplete callback to DOTweenAnimation dynamically?

### ISSUE THREAD

**Issue by Jayatubi** [Demigiant/dotween#375]
I want to play the DOTweenAnimation by code and do something just after the animation finishes. It seems like I have to set the callback in the inspector. It there a way I could set the callback at the runtime dynamically?

**Comment by Demigiant** [comment]
Ahoy.

As long as you're sure your DOTweenAnimation has generated its tween (which happens inside its Awake) you can get it using `myDOTweenAnimation.GetTweens()[index]` (where index is the position of the DOTweenAnimation on a specific gameObject, 0 if there's only one) and then assign its OnComplete with the regular [DOTween code](http://dotween.demigiant.com/documentation.php?api=OnComplete): `myTween.OnComplete(myCallback)`.

**Comment by Jayatubi** [comment]
I see. Thanks.
