### ISSUE TITLE
In looping Sequence,Should Tweener.OnStart() be called every loop?

### ISSUE THREAD

**Issue by tompsono** [Demigiant/dotween#377]
In looping Sequence,should Tweener.OnStart() be called every loop?
In under code,Debug.Log() is called only twice.
Is it by design?

**Example:**
```
var sequence = DOTween.Sequence();
var tween1 = DOTween.To(() => 0, v => { }, 0, 1).OnStart(() => Debug.Log("OnStart(tween1)"));
var tween2 = DOTween.To(() => 0, v => { }, 0, 1).OnStart(() => Debug.Log("OnStart(tween2)"));
sequence.Append(tween1);
sequence.Append(tween2);
sequence.SetLoops(-1);
```

**Expected:**
OnStart(tween1)
OnStart(tween2)
OnStart(tween1)
OnStart(tween2)
...

**Result:**
OnStart(tween1)
OnStart(tween2)

Now, to realize this feature, I set Tweener.playedOnce(false) and Tweener.startupDone(true) in Sequence.OnStepComplete().

**Comment by Demigiant** [comment]
Ahoy!

It is [by design](http://dotween.demigiant.com/documentation.php?api=OnStart): OnStart is called only **the very first time** the tween is set in a playing state.
If you want a repeating callback at the beginning of your sequence you can simply use [InsertCallback](http://dotween.demigiant.com/documentation.php?api=InsertCallback), and if you want a callbacks every time the tween enters a playing state you can use [OnPlay](http://dotween.demigiant.com/documentation.php?api=OnPlay) ;)

**Comment by tompsono** [comment]
Thank you for your replying, I understand,OK.

But I hope some way to recall Tweener.OnStart() in repeating if possible.
It enables more flexible use.

My case was like this:

```
var sequence = DOTween.Sequence();
foreach (var child in Children) {

    sequence.Append( child.GetIndivisualTweener() );
    //I don't know what tween comes.
    //Maybe, It sounds SFX onStart or onComplete.
    //(Like jumping motion)

}
sequence.SetLoops(-1);
```

Thank you.

**Comment by tompsono** [comment]
My solution.
I hope you make Tweener.onPlay as public..
Thank you.

```
static Sequence AppendEx(this Sequence sequence, Tweener tweener)
{
    var onStartField = typeof(Tweener)
	  .GetField("onStart", BindingFlags.NonPublic | BindingFlags.Instance);

    var onStart = onStartField.GetValue(tweener) as TweenCallback;
    if (onStart != null)
    {
	  sequence.AppendCallback(onStart);
	  onStartField.SetValue(tweener, null);
    }

    sequence.Append(tweener);

    if (tweener.onComplete != null)
    {
	  sequence.AppendCallback(tweener.onComplete);
	  tweener.onComplete = null;
    }

    return sequence;
}
```

**Comment by Demigiant** [comment]
Oh, sorry, I missed the fact you were talking about nested Tweeners and not the Sequence. But can you explain me (in words, not code—I'm in a delirium today and it would help me :)) what you were trying to achieve? It's not clear to me why `InsertCallback(atTweenerStart, callback)` wouldn't be the most flexible solution. Consider that if you're appending tweeners one after the other you can get the time where the next one will be appended by [checking the Sequence duration](http://dotween.demigiant.com/documentation.php?api=Duration) before the Append.

**Comment by tompsono** [comment]
More precisely, I need flexibility of choice to use a Tweener **as single tweener** or **as Sequence**.
InsertCallback() is useful only when what to do is determined.
It's weak at polymorphism.
Managing one animation includes onStart/onComplete action as one Tweener is very useful in many case.

Sorry,this is difficult issue to explain without any code...
I want use like this:

```
// ICreature is interface.
// So I don't know what is implemented in .GetBarkTweener() and .GetJumpTweener()
ICreature creature = GetComponent<ICreature>()

//GetBarkTweener() returns barking animation tweener(it moves creature sprite).
//It sounds sfx on start. Bark SFX is different each creatures.
creature.GetBarkTweener();  //sounds on start, 'Bow!' or 'Woof!' or silence
```

or :

```
//Bark(Bow!) -> Jump
creature.GetBarkTweener()  //sounds on start
    .OnComplete(()=>creature.GetJumpTweener());  //landing sound on complete
```

or :

```
//Bark(Bow!) -> Jump -> Bark(Bow!) -> Jump ->...
DOTween.Sequence();
    .Append(creature.GetBarkTweener());   //sounds on start
    .Append(creature.GetJumpTweener());   //sounds on complete
    .SetLoops(-1);
```


InsertCallback() is unsuitable in this case.
It forces the caller side to deside SFX and to write code to play SFX every place.

Using Tweener.Duration() is good way, but I want to use Sequence system.
It is easy to append and loop.
