### ISSUE TITLE
WaitForCompletion() inside Loop (for or while)

### ISSUE THREAD

**Issue by NikosPetrop** [Demigiant/dotween#381]
So i am trying to make an exp bar. The logic is set and i want to animate the Image.FillAmount with DoTween. so i initiate a sequence here:
```
private void UpdateUI(float experienceNormalized)
    {
        mySequence = DOTween.Sequence();

        //Animation logic of exp bar here!!
        if (experienceBarImage.fillAmount <= experienceNormalized && levelSystem.levelsToGain.Count()==0)
        {
            experienceBarImage.DOFillAmount(experienceNormalized, 1);
        }
        else //if (experienceBarImage.fillAmount > experienceNormalized || levelSystem.levelsToGain.Count > 0) 
        { 
            StartCoroutine(AnimateExperienceBarForLevelUp(experienceNormalized));
        }
    }
```

and the code for the Coroutine the code is

```
private IEnumerator AnimateExperienceBarForLevelUp(float experienceNormalized)
    {
        int firstLevelLoop = levelSystem.levelsToGain.First();
        int lastLevelLoop = levelSystem.levelsToGain.Last();
        for (int i = firstLevelLoop; i < lastLevelLoop; i++)
        {
            //Make a sequence and append each animation while adding the level
            //at the UI, when experience 100%
            yield return mySequence.Append(experienceBarImage.DOFillAmount(0.99f, 1.3f))
                .Append(experienceBarImage.DOFillAmount(0, 0f))
                .OnComplete(() => {
                    //experienceBarImage.fillAmount = 0f;
                    particle.SetActive(true);
                    SetLevelNumber(i + 1);
                }).WaitForCompletion();
            Debug.Log("Waited.");
        }
        yield return mySequence.Append(experienceBarImage.DOFillAmount(experienceNormalized, 1)).WaitForCompletion();
    }

```
The IEnumerator is kinda wrong cause i tried so many different things and none works so far. so i just copied paste my latest code. The problem as i see it is that coroutine is not waiting for the completion and also the second coroutine throws an 
`DOTWEEN ► This Tween has been killed and is now invalid`
 error. I tried with a while loop also to waitforcompletion and nothing works as planned. Also i am having problem with callbacks in .OnComplete() + yield return
PS. I am working on Unity **2019.2.9f1** !

**Comment by NikosPetrop** [comment]
So 15 mins after posting, and after 2.5 days trying to figure out how to make it work i finally found the solution. mysequence needed to re instantiate again. I putted 
`mySequence = DoTween.Sequence()` before `yield return` and that fixed it in a magic way.
i will post my code for future reference if someone ever try nesting loops inside coroutine with return yield WaitForCompletion() .
```
    private IEnumerator AnimateExperienceBarForLevelUp(float experienceNormalized)
    {
        int firstLevelLoop = levelSystem.levelsToGain.First();
        int lastLevelLoop = levelSystem.levelsToGain.Last();
        for (int i = firstLevelLoop; i < lastLevelLoop; i++)
        {
            //Make a sequence and append each animation while adding the level
            //at the UI, when experience 100%
            yield return mySequence.Append(experienceBarImage.DOFillAmount(0.99f, 1.3f))
                .Append(experienceBarImage.DOFillAmount(0, 0f))
                .OnKill(() => {
                    particle.SetActive(true);
                    SetLevelNumber(i + 1);
                    mySequence = DOTween.Sequence();    //This Fixed it !!!!
                    levelSystem.levelsToGain.Clear();
                }).WaitForCompletion();
            Debug.Log("Waited.");
        }
        mySequence = DOTween.Sequence();    //Also This !!!!
        yield return mySequence.Append(experienceBarImage.DOFillAmount(experienceNormalized, 1)).WaitForCompletion();
    }
```
P.S. I would like a answer for this by **Demigiant** or maybe a better solution/clean up this code.
Thanks for your time in advance :)

**Comment by Demigiant** [comment]
Ahoy! :)

I'm having some problems understanding exactly what you're doing by creating as many nested tweens as `lastLevelLoop - firstLevelLoop`, but I see the problem there. You cannot add/append/insert tweens to a Sequence once it has started, because it is locked as soon as that happens, and that's why you have to recreate it after you wait for completion (also because the Sequence is set to autoKill so when it completes it gets killed, and that's why you get the `This Tween has been killed` log).

Magic explained :)

**Comment by NikosPetrop** [comment]
> You cannot add/append/insert tweens to a Sequence once it has started

Mind exploded there. I haven't read it in documentation or maybe i didn't notice it. That will help in the future for sure.

I get the all the levels gained with the AddedExp( for example player may level up 5 levels) and storing these values in a List<>. So i get the first and the last elements as a reference in the For loop. (I had a while but as i tested my issue i changed to for to simplify it and not going into endless loop).
Also about the while loop. I had problem that while was entering endless loops when i was making a callback to change the flag. Any workaround? (Maybe with correct yield return that will get fixed)
Thanks for the fast reply though :)

**Comment by Demigiant** [comment]
I do mention the "tweens can't be added to a started Sequence" in the [Creating a Sequence](http://dotween.demigiant.com/documentation.php#creatingSequence) chapter, but maybe I should find a way to evidence it more.

About the while can you show me the code you were using so I can see if I find something weird?

Cheers :)

**Comment by NikosPetrop** [comment]
I just checked it and i think the quoted line will make it perfectly clear, though it has already made clear in the documentation.

About the while is the same loop but change For>While. But it's ok, thank you very much. I will keep you informed if something comes up again. You can close the topic, if you want :)

**Comment by Demigiant** [comment]
Yey, have a nice day :)

**Comment by spiNkerZ** [comment]
> Итак, через 15 минут после публикации и через 2,5 дня, пытаясь понять, как заставить его работать, я наконец нашел решение. mysequence необходимо повторно создать экземпляр. Я поставил `mySequence = DoTween.Sequence()`раньше `yield return`, и это исправило это волшебным образом. я опубликую свой код для дальнейшего использования, если кто-нибудь когда-нибудь попытается вложить циклы внутри сопрограммы с возвратом yield WaitForCompletion() .
> 
> ```
>     private IEnumerator AnimateExperienceBarForLevelUp(float experienceNormalized)
>     {
>         int firstLevelLoop = levelSystem.levelsToGain.First();
>         int lastLevelLoop = levelSystem.levelsToGain.Last();
>         for (int i = firstLevelLoop; i < lastLevelLoop; i++)
>         {
>             //Make a sequence and append each animation while adding the level
>             //at the UI, when experience 100%
>             yield return mySequence.Append(experienceBarImage.DOFillAmount(0.99f, 1.3f))
>                 .Append(experienceBarImage.DOFillAmount(0, 0f))
>                 .OnKill(() => {
>                     particle.SetActive(true);
>                     SetLevelNumber(i + 1);
>                     mySequence = DOTween.Sequence();    //This Fixed it !!!!
>                     levelSystem.levelsToGain.Clear();
>                 }).WaitForCompletion();
>             Debug.Log("Waited.");
>         }
>         mySequence = DOTween.Sequence();    //Also This !!!!
>         yield return mySequence.Append(experienceBarImage.DOFillAmount(experienceNormalized, 1)).WaitForCompletion();
>     }
> ```
> 
> PS Я хотел бы получить ответ от **Demigiant** или, может быть, лучшее решение/очистить этот код. Спасибо за ваше время заранее :)

Thank you man!
