### ISSUE TITLE
Pausing / Killing a Transform DOTween.Sequence causes GameObject to snap to floor

### ISSUE THREAD

**Issue by SHOSH-NI** [Demigiant/dotween#382]
Hi,
One of the ways I'm using DOTween, 
is to move around transforms both vertically and horizontally.

I have unique situations, where a transform is elevating and then descending through a sequence, 
in which I disrupt the ongoing sequence to start a whole new motion,
like another ascent and descent or movement only on the x and z axis,
by killing the ongoing sequence.

I noticed in attempting any of these motions - 
Where I kill an older running sequence, before starting a new one.
That the height of the object being sequence tweened by it's Transform,
always snaps into the ground, to the exact same height.
Instead of playing the next sequence from the height being the same as it was while descending.

But only if the sequence is playing after a previous sequence is killed. 
Playing them with no sequences running on the object,
has them perform the sequence actions with the correct height offset.

Here's the gist of the logic -
`

        private void TweenLaunch()
        {
                // Logic to determine launchAscentPositionY among other things...

                _playingTweenSequence = DOTween.Sequence();
                _playingTweenSequence.Append(transform.DOMoveY(launchAscentPositionY, ascentDuration).SetEase(Ease.OutCubic).OnStart(() => {// Logic}).OnUpdate(() => {// Logic}));

                // Apply pushback to play along side y axis ascension
                _playingTweenSequence.Join(transform.DOMoveX(launchAscentKnockbackPosition.x, ascentDuration).SetEase(Ease.OutCubic));
                _playingTweenSequence.Join(transform.DOMoveZ(launchAscentKnockbackPosition.z, ascentDuration).SetEase(Ease.OutCubic));

                _playingTweenSequence.Append(transform.DOMove(launchDescentPosition, descentDuration).SetEase(Ease.Linear).OnStart(() => {// Logic}).OnComplete(() => {// Logic}));
        }

        private void TweenJuggle()
        {
                if (_playingTweenSequence != null)
                        _playingTweenSequence.Kill();

                // Tweening logic - quite similar to launch...
        }
`

This same snap to the floor, occurs even when pausing the sequence -
to the exact same height as killing the sequence.
Sequence motions on the z and x axis, are fine when paused or killed.

If you need any more details, let me know! Thanks!!

**Comment by Demigiant** [comment]
Ahoy! And uhmmm I can't see any fault in your code, but I'm not sure I understand the problem. You mean that if you have Sequence S running and then you kill it and start another, the starting point isn't where S's target was but 0/ground (which I assume was S starting position)?
Could you whip up a sample project that replicates this and send it to me, so I can check it out?

Cheers :)
Daniele

**Comment by SHOSH-NI** [comment]
Hi, Daniele :)
I haven't had time to setup a sample project to replicate this, with the recent events unfolding, when I'll finally have time to continue, I'll send you!

**Comment by SHOSH-NI** [comment]
Hi Daniele, 
sorry I haven't given an update since last time.
I only had time today to check the project out again and I found what was the issue, indeed on my end.

If the object being tweened has a NavMesh agent on him the object weirdly bounds the height of the object to the height of the nav mesh on it's terrain, for a moment when the tween is being killed / paused.

Disabling the navmesh when tweening solved it.

**Comment by Demigiant** [comment]
Ahoy! And thank you for the update :)
