### ISSUE TITLE
SetDelay causes problems with tween startup if target has been destroyed

### ISSUE THREAD

**Issue by vjekob** [Demigiant/dotween#383]
Hi,

When SetDelay is called on a tween, DOTween doesn't check if target is invalid when it starts the tween after the delay time elapses. Instead, in any such situation, it will cause runtime errors.

It's very easy to repeat: create a tween with a delay, and create a coroutine that destroys the target object after time interval shorter than the delay. Like this:

public class TestSetDelay : MonoBehaviour
{
    public GameObject Prefab;

    private IEnumerator Wait(float time, UnityAction callback)
    {
        yield return new WaitForSeconds(time);
        callback();
    }

    private void Start()
    {
        var prefab = Instantiate(Prefab, transform);
        prefab.transform.DOScale(2.0f, 1.0f).SetDelay(2.0f);
        StartCoroutine(Wait(1.0f, () => Destroy(prefab)));
    }
}

I think this should be treated as a bug if for no other reason, then for the fact that if there was no SetDelay and the target gets destroyed *during* the tweening process, no error would happen:

    private void Start()
    {
        var prefab = Instantiate(Prefab, transform);
        var target = prefab.transform;
        target.DOScale(2.0f, 2.0f);
        StartCoroutine(Wait(1.0f, () => Destroy(prefab)));
    }

So - from the consumer perspective - it's valid for a target to get destroyed during tween execution, but it's not valid for it to get destroyed during the delay wait interval.

Thanks for considering this, and keep up the **AMAZING** work!

**Comment by Demigiant** [comment]
Ahoy, and thank you for the nice words :)

I can't replicate this here (copy-pasted your code). If SAFE MODE is active you get the usual warning that says that Startup failed and the tween is automatically killed, but no error logs. Are you using the latest v1.2.335?

Cheers :)

**Comment by vjekob** [comment]
Hi,

I am using version 1.2.305 - it's the Pro version from the Asset store, not from this github repo. And yes, it seems I was wrong - there is safe mode message in both of the cases I gave, except that in one case the message is given immediately while the tween is executing, and in another case it's give only after the app stops.

In any case, thanks for the response!

cheers :)
