### ISSUE TITLE
IL2CPP error on building #302

### ISSUE THREAD

**Issue by suntabu** [Demigiant/dotween#384]
Hi Daniele,
I am getting this error when attempting an IL2CPP build for my iOS project:

IL2CPP error for type 'DG.Tweening.Plugins.SpiralPlugin' in SpiralPlugin.cs:48
Additional information: Invalid method 'null' found in vtable for 'DG.Tweening.Plugins.SpiralPlugin'

![image](https://user-images.githubusercontent.com/7839044/77748862-0451e700-705c-11ea-89b7-99e8f69dcb92.png)

**Comment by Demigiant** [comment]
Ahoy!

That is very weird, the Pro and core versions you have installed are perfectly on-par with the API.

I see you haven't run DOTween' Setup (the green button). If you run it that should solve the problem. If it doesn't, please let me know and write me via mail (or via the contact form [here](https://www.demigiant.com/about.php#contactWrap)) so I can investigate and send you an update.
