### ISSUE TITLE
Sequences generate GC allocations 

### ISSUE THREAD

**Issue by PrometeoProduction** [Demigiant/dotween#391]
This is the script I use :

```
private void ScaleScore()
    {
        sequence = DOTween.Sequence();

        sequence.Append(scoreTransform.
           DOScale(scoreScaleDown, 0.1f)
           .SetEase(Ease.InOutSine))
           .AppendInterval(0.05f)
           .Append(scoreTransform
           .DOScale(scoreScaleUp, 0.1f)
           .SetEase(Ease.InOutSine));
    }
```

That's what the profiler tells me:

![dotweengarbage](https://user-images.githubusercontent.com/50480177/79995549-a88e4880-84b7-11ea-8e5d-668aee66789c.png)

Every call to this method causes 496B of allocation and the same thing happens with other sequences.

These are my settings:

![DOTween settings](https://user-images.githubusercontent.com/50480177/79995931-23effa00-84b8-11ea-9a0b-e155464eb4ec.png)

Am I using the sequences wrong or is that normal?

Maybe I should save the Sequence and reuse it instead of calling DOTween.Sequence()?

But I don't understand how.

**Comment by Demigiant** [comment]
Ahoy,

Yes, even if most of the "parts" of a Sequence are recycled generating one still does cause a minimal allocation (even with recycle tweens on, especially if the Sequence hasn't yet been killed and thus hasn't entered the recycling system). If you can reuse a Sequence/Tweener instead of recreating it every time it's definitely better, both in terms of allocations and performance :)

**Comment by PrometeoProduction** [comment]
I'm sorry, but I'm pretty dumb.

When I create a sequence like this:

```
Sequence sequence;

private void CreateSequence()
    {
        sequence = DOTween.Sequence();

        sequence.Append(scoreTransform.
           DOScale(scoreScaleDown, 0.1f)
           .SetEase(Ease.InOutSine))
           .AppendInterval(0.05f)
           .Append(scoreTransform
           .DOScale(scoreScaleUp, 0.1f)
           .SetEase(Ease.InOutSine));
    }
```

Then how do I use it again?

Thanks :).
