### ISSUE TITLE
Suggestion to add a DOCounter() in TextMeshPro

### ISSUE THREAD

**Issue by oriolmanya** [Demigiant/dotween#392]
Hi, Ive been using your solution for years and just today I bougth the PRO version.

Amazing job, congratulations.

I've just come up with a suggestion:
Add a DOCounter() in TextMeshPro, to allow to count from one integer or float to another, for counting "coins" in a game for example.

In the past I solved this using the Generic Way, but it would be super useful and straightforward to have a method right on TextMeshPro.

Thank you very much.

**Comment by Demigiant** [comment]
Ahoy!

That's a very nice idea. Adding it to my todo list (both for the free version and Text, and for the Pro and TextMesh Pro) :)

**Comment by Demigiant** [comment]
Done :) Will be out with the next update (in a couple days).

The API is:

`myText.DOCounter(int fromValue, int toValue, float duration, bool addThousandsSeparator=true, CultureInfo culture=null)`

where if culture is left to NULL it uses Invariant culture (only if adding thousandsSeparator obviously) :)
