### ISSUE TITLE
DoTweenPath ID (editor pro)

### ISSUE THREAD

**Issue by Serliton** [Demigiant/dotween#393]
Hi Daniele! Thank you for your incredible tool.
Why there is ID field on DoTweenPath (pro editor), but there is no PlayById (string) option? 
You can set ID to DoTweenPath, but you can`t play it by ID.
![1](https://user-images.githubusercontent.com/64669382/80850064-630f0f80-8c5d-11ea-804d-c10a04205dd0.png)

**Comment by Demigiant** [comment]
Ahoy :)

Huh, that is a good question :B Usually paths are played programmatically via code (DOTween.Play(id) static method) and I never thought of adding a DOPlayById to DOPath, nor it was asked before. Will implement it for the next release (but if you need it immediately write me [here](https://www.demigiant.com/about.php#contactWrap)).

**Comment by Serliton** [comment]
I will wait for the next release, thank you!
