### ISSUE TITLE
Using DOTweenEditorPreview.Start dirties the scene

### ISSUE THREAD

**Issue by msfredb7** [Demigiant/dotween#398]
I'm using the DOTweenEditorPreview API to make a custom preview of some of my animations. Unfortunately, using DOTweenEditorPreview.Start creates a "-[DOTween Preview>]-" gameobject that dirties the scene. This means my artists can't use the custom preview without "modifying the scene". This is bad with version control.

The "-[DOTween Preview>]-" gameobject should be created with the  ``HideFlags.HideAndDontSave`` flags so it doesn't dirty the scene. You can use ``EditorUtility.CreateGameObjectWithHideFlags(...)`` to do that.

**Comment by Demigiant** [comment]
Ahoy, the latest versions of DOTween don't create the DOTween Preview gameObject anymore for editor preview, but I still have to publish the downloadable version. In the meantime you can either get the latest from this repo ([here](https://github.com/Demigiant/dotween/tree/develop/_DOTween.Assembly/bin)) or use DOTweenEditorPreview.Stop when stopping the preview, which will clear the gameObject (and was the intended usage before this new non-gameObject version).
