### ISSUE TITLE
How to create a Tween which not killed by KillAll

### ISSUE THREAD

**Issue by suntabu** [Demigiant/dotween#404]
As showing in the title, I want to create an infinite loop tween which not killed by KillAll.

I know the method **KillAll(bool complete, params object[] idsOrTargetsToExclude)**
but I can't give the idsOrTargets for the method.

How to do this?

**Comment by Demigiant** [comment]
Ahoy!

Sorry for the delay. Let's say you have 3 tweens with an ID "dontKillMe" and 2 with an ID "letMeBe" and you want all of them not to be killed, you would write it like this:

```
// Using FALSE for the first param but it depends on you
DOTween.KillAll(false, "dontKillMe", "letMeBe");
```
