### ISSUE TITLE
OnStart and initial value does not work as expected (possible bug)

### ISSUE THREAD

**Issue by hershko** [Demigiant/dotween#405]
If I set an initial value for the property I'm tweening in OnStart, the tween doesn't do anything.

For example, assume an image with a scale of 1.0f (the variable image below is the transform).

This code works (image scale is set to 1.3f, and then scales down to 1.0f):
image.localScale = new Vector3(1.33f, 1.33f, 1.0f);
image.DOScale(new Vector3(1.0f, 1.0f, 1.0f), 1.0f));

But this doesn't do anything (the image just stays at 1.0f):
image.DOScale(new Vector3(1.0f, 1.0f, 1.0f), 1.0f).OnStart(() =>
{
image.localScale = new Vector3(1.33f, 1.33f, 1.0f);
});

I'm on the latest version of DOTween Pro. This link has a sample project showing the issue:
https://drive.google.com/file/d/1FZ0fMi4_463q_fwdpg9tb4egXn8pe-6E/view?usp=sharing

Thanks!

**Comment by Demigiant** [comment]
Ahoy,

OnStart is called when the tween plays the first time but AFTER it's been initialized, so that won't work because the starting value is already set :P
But you could do this instead: 
`image.DOScale(new Vector3(1.0f, 1.0f, 1.0f), 1.0f).From(new Vector3(1.33f, 1.33f, 1.0f));`

:)

**Comment by hershko** [comment]
Thanks, I guess even after using DOTween for a year I can still learn new stuff :)
