### ISSUE TITLE
How to use DOTweenPath?

### ISSUE THREAD

**Issue by lordlycastle** [Demigiant/dotween#409]
I was hoping to define a path in editor and use that on multiple instantiated games objects but it is not clear how to do this.

I ended up having to instantiate paths with each instance and then make them children of the path. Which seems like a lot of work. Can there be a way to copy path and set target as some other transform? How do I change duration/speed of paths dynamically? I want to speeds things up and down.

We really need documentation on the website as it only contains a video but on documentation of what the properties of the Path are. The video is also very old and only shows how to do a single simple things which is make something run on path. No way to recreate path, or shift is a little, or randomize it, or change duration, or get start waypoint, or anything really.

**Comment by Demigiant** [comment]
Ahoy,

Paths are per-object and there's indeed no way to randomize it, shift it, etc. Buuut, what you could do if you're just using a "sample path" that you want to replicate, is to grab the waypoints from it at runtime (by using `myDOTweenPath.wps`—remember that the first waypoint of a path won't be returned, and that it's always the position of your path-ed transform when the tween starts) and use them with [DOPath](http://dotween.demigiant.com/documentation.php?api=DOPath) runtime code, where you can change targets, duration, ease, etc.

**Comment by Demigiant** [comment]
P.S. I plan to add more documentation as soon as I finish a biiig new feature for the Pro
