### ISSUE TITLE
installing DOTween and Pro compiler errors on Unity 2018.4.12f1

### ISSUE THREAD

**Issue by imtomgamedev** [Demigiant/dotween#412]
I've installed DOTween and DOTween Pro and have received the 18 compiler errors at install, beginning with the following:

Assets/Demigiant/DOTweenPro/DOTweenTk2d.cs(24,81): error CS0246: The type or namespace name 'tk2dBaseSprite' could not be found (are you missing a using directive or an assembly reference?)

Should I be installing earlier versions of both?  If so, which ones, the changelog appears extensive.

Sincerely,
Tom

**Comment by Demigiant** [comment]
Ahoy!

That means you activated the 2D Toolkit module (in DOTween's setup) but you don't have the 2D Toolkit asset. All the modules inside the "External Assets" section are there to be activated only if you have those other assets in your project.

To fix it just run DOTween's Setup again and deactivate all external modules you don't have :)

Cheers,
Daniele

**Comment by imtomgamedev** [comment]
I've never had a faster support response! Thank you, Daniele!!!

**Comment by Demigiant** [comment]
^_^
