### ISSUE TITLE
Сan't kill a running sequence

### ISSUE THREAD

**Issue by Faymont** [Demigiant/dotween#413]
Hello there,
Thank you for your DoTween package.

Faced with such a problem when I create a sequence that contains 2 or more tweens, then when 1 and 2 tweens are working out. Kill() stops the sequence as expected, and starting with the 3 and so on Kill() does not stop the sequence and it continues the animation.

```
var tween = target.DOLocalMove(direction,duration) .SetLoops(4, LoopType.YOYO).SetEase(Ease.OutQuad)

tween.Kill();
```

Thanks and Regards,
Sam

**Comment by Demigiant** [comment]
Ahoy,

I can say with 100% certainty that killing a tween/Tweener/Sequence will kill it and stop its animation, so the porbable reasons why it's not happening could be:

1. You have multiple tweens on the same targets and you're killing only one
2. You're killing tweens inside a Sequence (which isn't allowed) and not the Sequence itself
