### ISSUE TITLE
Path visual editor feature cannot use in MacOS

### ISSUE THREAD

**Issue by ha-quang-vu** [Demigiant/dotween#415]
Hello,

With same project, I can use DoTween Path in Windows with Shift + CTRL. But I cannot use it in when I use MacOS with Shift + CMD.

Unity: 2019.3.13f1
Using newest DoTween Version in AssetStore.
Not worked with Blank Project and current project.

Thanks very much.

Edited:
I tested and it run well with 2017.4.40f1.

**Comment by Demigiant** [comment]
Hi,

A while ago I had another user with the same problem and it was a simple fix (for a Unity bug if I remember correctly), but I've tried to do various searches and I can't find the context again, nor I remember said fix :B Can you write me from [this contact form](https://www.demigiant.com/about.php#contactWrap) so I can send you the latest-est version of DOTween Pro and see if that fixes it?

Cheers
