### ISSUE TITLE
Am I supposed to use 'EditorPreview' from within a Monobehaviour, but at edit time with [ExecuteInEditMode]?

### ISSUE THREAD

**Issue by MostHated** [Demigiant/dotween#419]
Hey there,
    I was under the impression that I was going to need to use DOTweenEditorPreview.PrepareTweenForPreview, as I am trying to use it to animate some things in the scene view for my waypoint tooling, but Unity keeps coming back with "The type or namespace name 'DOTweenEditor' does not exist in the namespace 'DG'", which I am guessing is because it's not in an editor folder or anything. 

I am using the [ALINE](https://assetstore.unity.com/packages/tools/gui/aline-162772) drawing package, and I wanted to tween some of it's values, but my scripts are using an ALINE included MonoBehaviour wrapper (MonoBehaviourGizmos, which had Derived from MonoBehaviour, but I now have it deriving from Odins SerializedMonoBehaviour) and I am using [ExecuteInEditMode]. 

I could not seem to get any tweening working under ALINES OnDrawGizmos() method, so I figured that because I was doing this at edit time, I needed to use DOTweenEditorPreview, but since it's not an Editor script, it seems like it won't do that either. I am not quite sure how to proceed. Should Dotween be working without EditorPreview in a MonoBehaviour derived class if it is using [ExecuteInEditMode], or do I need to use the EditorPreview and it's just not doing what it should be doing? Perhaps I am just going about this incorrectly, to begin with?

This is a shortened down version of it.

```cs

    private float size;
    public Ease ease = Ease.InSine;
    public LoopType loopType = LoopType.Yoyo;
    Tween tween;

    void Awake()
    {
        Assignments();
        DOTween.Init();
    }

    public override void DrawGizmos()
    {
        setting = settingsData[wp.waypointClass];
        size = setting.waypointSize;
        tween = DOTween.To(() => size,
            x => Draw.Circle(
                new Vector3(position.x, setting.waypointHeight, position.z), Vector3.up, size = x, color),
            size + 0.3f, 1).SetEase(ease).SetLoops(-1, loopType); // These were just recently tacked on to see if it had anything to do with needing them, it was not working either or without them.
        tween.Play();
    }
```

Unity v2020.1.0b15
DoTween Pro: v1.0.178
(Not sure if it matters, but I use Doozy UI, but I removed all traces of Dotween, then installed Pro.)

**Comment by Demigiant** [comment]
Ahoy,

The (kinda hidden) process to custom-run tweens in editor mode is this:
1. Create your tween in the editor
2. Pass it to DOTweenEditorPreview.PrepareTweenForPreview
3. Call DOTweenEditorPreview.Start to start the preview
4. Call DOTweenEditorPreview.Stop to stop the preview

Buuut you can only do it from an editor class (so a class inside an "Editor" folder and not a MonoBehaviour), otherwise you won't have access to it. What you could do is create your own editor class with a static method that run the tween, and then use an "#if UNITY_EDITOR" define to call it from your MonoBehaviour.

**Comment by MostHated** [comment]
Thanks for the info. It seems like I was really close in what I was attempting to do. I had created a static editor script that was set with [InitializeOnLoad]. Here is a stripped-down version of what I have. This worked once, but has not worked again after the first time it played. 

(There is more to this, to detect what kind of item it is that is selcted, things to do if it's unselected, etc, etc)
<details>
<summary>Static method</summary>

```cs
#if UNITY_EDITOR
	[InitializeOnLoad]
	public class WaypointSelectionHandler : OdinEditor
	{
		private static ArrowVisual arrowVisual; // --- The item I am trying to tween
		private static bool isActive = true;
		static WaypointSelectionHandler()
		{
			SceneView.onSceneGUIDelegate -= OnSceneGUI;
			SceneView.onSceneGUIDelegate += OnSceneGUI;
			Selection.selectionChanged += SelectionChange; // --- When selecting something in the scene, moves ArrowVisual above the selected item

			if (arrowVisual == null) arrowVisual = FindObjectOfType<ArrowVisual>(); // --- Find it in the scene
		}

		static void HideIndicators()
		{
			arrowVisual.StopAnim();
			DOTweenEditorPreview.Stop();
			arrowVisual.isActive = false;
		}

		static void SelectionChange()
		{
			if (arrowVisual == null) arrowVisual = FindObjectOfType<ArrowVisual>();
			if (Selection.activeObject == null || Selection.activeGameObject == null)
			{
				if (arrowVisual.isActive) HideIndicators();
				return;
			}

			arrowVisual.transform.position = waypoint.transform.position + new Vector3(0, 1, 0);
			arrowVisual.isActive = true;

			var tween = arrowVisual.anim.tween;
			DOTweenEditorPreview.PrepareTweenForPreview(tween);
			DOTweenEditorPreview.Start();
			arrowVisual.PlayAnim();
		}
#endif
```
</details>


Here is the Arrow that I am trying to move, which then is to move up and down at its location via tween.

<details>
<summary>Item to tween </summary>

```cs
#if UNITY_EDITOR
	[ExecuteInEditMode]
	public class ArrowVisual : MonoBehaviour
	{
		[SerializeField] public bool isActive;
		[HideInInspector] public DOTweenAnimation anim;

		private void OnEnable()
		{
			DOTween.Init();
			anim = GetComponent<DOTweenAnimation>();
		}

		public void PlayAnim()
		{
			anim.DOPlay();
		}
        
		public void StopAnim()
		{
			anim.DOKill();
		}
	}
#endif
```
</details>

Then here were a few other things I tried, but could never get working.

<details>
<summary>Additional methods</summary>

```cs
this.gameObject.transform.DOLocalMove(new Vector3(
            this.gameObject.transform.position.x,
            1.3f,
            this.gameObject.transform.position.z),
        1
    )
    .SetEase(Ease.InOutBounce)
    .SetLoops(-1, LoopType.Yoyo)

    .SetTarget(this).Play();
```

```cs
        public float animY = 1.35f;
        public float heightY;
        public float heightVal = 1f;
		
		tween = DOTween.To(
		        getter: () => heightY,
		        setter: y => heightY = y,
		        endValue: animY,
		        duration: 1
		    )
		    .SetEase(Ease.InOutBounce)
		    .SetLoops(-1, LoopType.Yoyo)
		    .SetTarget(this)
		    .SetRelative()
		    .OnUpdate(() => heightVal = heightY);
		tween.Play();
```
</details>

Then here is the way I have the Arrow gameobject set up.

![](https://i.imgur.com/5MG4J5C.png)


With the way I have the static class and the arrow above, it worked one time today, then no matter what else I have tried, I can't get it to work again. Even with the code exactly the same. 

I clicked on another item, the arrow moved over to it, then nothing, it just never plays. I see the -[ DOTween Preview ► ]- item show up in the hierarchy, but nothing else happens. Am I missing something else?

Thanks,
-MH

**Comment by MostHated** [comment]
Sorry, nevermind. Looks like I finally got it worked out.

**Comment by Ariel-Feldman** [comment]
Hi @MostHated I've come across the exact same problem!! made the static editor hookup, run it ones - works like a charm, 
came back to it again - not working at all (!?!?!)
Any chance you remember what is the thing you did to solve it?

**Comment by MostHated** [comment]
Ah shoot, it's been some time since I touched that particular project. I certainly cannot remember off hand. I will try to open that project up and see if anything sparks my memory, but it might be hard to remember exactly what thing I had to do at the time.

**Comment by Ariel-Feldman** [comment]
Ok found the problem and the solution!! thanks!! if anyone reach here and intrested, adding my code for runing tween in editor, it works well, have a play button on the inspector and it reset the tween after its done, the TweenTransition class is base class for all my tweens and it have duration pramater and hold the refrence to the tween itself (after SetTween()) - which is used to await till end for reset:

`
[CustomEditor(typeof(TweenTransition), true )]
public class PlayTweenInEditor : Editor
{
    public override void OnInspectorGUI()
    {
        DrawDefaultInspector();
        if(GUILayout.Button("Play Tween"))
        {
            var tweenTransition = (TweenTransition)target;
            tweenTransition.SetTween();
            RunTween(tweenTransition);
        }
    }
`


    private async void RunTween(TweenTransition tweenTransition)
    {
        DOTweenEditorPreview.PrepareTweenForPreview(tweenTransition.Tween);
        DOTweenEditorPreview.Start();
        await Task.Delay((int)tweenTransition.Duration * 1000);
        DOTweenEditorPreview.Stop(true);
    }
}
`


Hi @Demigiant, I know realize it was you who responded here, I wish to take this space and thank you for everything you did and special for DoTween, you are simply a god to me.

**Comment by Demigiant** [comment]
❤️ ❤️ ❤️
