### ISSUE TITLE
cannt resolve symbol 'AsyncWaitForCompletion'. 

### ISSUE THREAD

**Issue by wang37921** [Demigiant/dotween#424]
`using DG.Tweening;

Tween tween = inst.transform.DOPath(pathPoints, moveSeconds, PathType.CubicBezier);
await tween.AsyncWaitForCompletion();`

cannt resolve symbol 'AsyncWaitForCompletion'. 
using version:
![image](https://user-images.githubusercontent.com/1498324/88991249-c8cd6f00-d312-11ea-9e35-89dac49fe06f.png)

**Comment by Demigiant** [comment]
Ahoy, AsyncWait methods require at least Unity 2018.1 and .NET Standard 2.0 or 4.6. Sorry for not mentioning it in the docs but I did it now. Otherwise you can use the regular [WaitForCompletion](http://dotween.demigiant.com/documentation.php?api=WaitForCompletion).
