### ISSUE TITLE
Bug in Mono breaks some minor stuff in DOTween

### ISSUE THREAD

**Issue by Darelbi** [Demigiant/dotween#43]
Extension methods with optional parameters fails to compile in Mono:

in example (from examples):

```
t.DORotate(new Vector3(0, 135, 0), 1);
```

says: "No overload of DORotate method accept 2 parameters". People like me having window Vista can't install VS 2013 (wich would be otherwise my choice). The only workaround seems specializing the overload.

It could possibly be related with localized version of Mono if you can't reproduce the issue (actually the real error message is: "Nessun overload del metodo DORotate accetta 2 argomenti")

Mono Version:
4.0.1

Unity Version:
5.1.2f1

.ween version:
1.0.810

Thanks for keeping DOTween free, that's a really cool framework ;) (I wanted to remove broken code but apparently I'm unable to compile DOTween with Mono)

**Comment by Demigiant** [comment]
Hey Dario!

Agh! That sounds superbad :O What version of MonoDevelop are you using? I just tried the one that comes with Unity 5.1.1 (v4.0.1) and have no issues like that.

**Comment by Darelbi** [comment]
Ha funzionato: ora funziona alla perferzione u.u (ho anche provato a riavviare Unity ieri e non funzionava, oggi invece che ho acceso il computer che era rimasto in ibernazione con Unity aperto funziona alla perfezione: tralaltro non mi andavano anche altre cose, anche i named parameters non compilavano.. boo ___ i misteri di unity )

**Comment by Demigiant** [comment]
Well great that it works now :D
