### ISSUE TITLE
DOPath rotate before starting path

### ISSUE THREAD

**Issue by emrys90** [Demigiant/dotween#431]
DOPath seems to immediately rotate the object to face the direction of the waypoint. How would I go about having it lerp to that rotation instead, and probably not start moving until its facing the right direction?

**Comment by Demigiant** [comment]
Closing because [duplicate](https://github.com/Demigiant/dotween/issues/430).

**Comment by Dan-Matt** [comment]
Those issues don't seem to be the same, is there a way to gradually rotate to the paths starting rotation?
