### ISSUE TITLE
DOJump look at direction

### ISSUE THREAD

**Issue by emrys90** [Demigiant/dotween#432]
How would I go about having a DOJump rotate to face the direction its moving in?

**Comment by Matthew-J-Spencer** [comment]
I'd like to know also.

**Comment by theroarer** [comment]
I can't get this to work either.

**Comment by Demigiant** [comment]
There is no "lookAt" option in DOJump, but you could do it manually by chaining a SetUpdate method to your jump and using that to calculate the direction of your movement frame-by-frame, then "look at" the direction vector
