### ISSUE TITLE
Deep Profiler Crashes Unity on Startup After Version 1.0.720

### ISSUE THREAD

**Issue by BrickRoadDX** [Demigiant/dotween#44]
Updated to the newest DOTween (1.0.810) and when you connect the unity Deep Profiler and start the project, it crashes on startup. (btw, awesome plugin, use it all the time for everything).

Tried in an empty project with DOMoveX on a simple transform.

**Comment by Demigiant** [comment]
Woah, just tested it and it happens here too. This issue is related to Unity 5.1.1 (I'm pretty sure I deep profiled with Unity 5.0, but **if someone could test this it would be great**) but not to Unity 4.6, so it must be a new Unity bug. Could you submit a bug report?

**Comment by BrickRoadDX** [comment]
To Unity? Not sure how I would phrase it as I don't know what in particular from DOTween is causing it.

**Comment by dredspace** [comment]
I find the same issue。Can it resolve?

**Comment by dredspace** [comment]
I test DOTween v1.0.800 can DeepProfile，DOTween v1.0.810 Crash。

**Comment by CanisLupus** [comment]
Hey everyone ;) We were also having this problem with Unity 5.2.1 and DOTween 1.1.005. I don't know if this has been somehow fixed or circumvented by Daniele (as it looked like a Unity bug), but updating DOTween to version 1.1.060 (two versions after 1.1.005) seems to have fixed the crashes for us! :)

**Comment by Demigiant** [comment]
That is great CanisLupus, thanks for mentioning it! I wrote Unity but had no idea how to pinpoint what was the reason of their bug. Must've changed something accidentally :)
