### ISSUE TITLE
Creating a tween and playing backwards not working? 

### ISSUE THREAD

**Issue by brunomikoski** [Demigiant/dotween#440]
I'm trying to create a tween, complete it and play it backwards right away, but it isn't working, any idea of why? 

```          
Tween tween = targetWindow.transform.DOScale(toScale, duration).SetEase(ease).SetAutoKill(false);
tween.Complete();
tween.PlayBackwards();
yield return tween.WaitForCompletion();
```

DOTween version: 1.2.335

**Comment by brunomikoski** [comment]
Okay, actually this was working properly what doesn't work properly is the `tween.WaitForCompletion()` so I had to do it like this:
```
Tween tween = targetWindow.transform.DOScale(toScale, duration).Pause().SetEase(ease).SetAutoKill(false);
tween.Complete();
tween.PlayBackwards();
yield return new WaitForSeconds(duration);
```

**Comment by Demigiant** [comment]
Hi, if you play the tween backwards the tween won't complete, but rewind. You should:

`yield return tween.WaitForRewind();`

:)

**Comment by brunomikoski** [comment]
> Hi, if you play the tween backwards the tween won't complete, but rewind. You should:
> 
> `yield return tween.WaitForRewind();`
> 
> :)

hahah that explains a lot! <3 Thanks a lot @Demigiant
