### ISSUE TITLE
Request - [PRO] Add RectTransform component to the list of supported components for visual editor

### ISSUE THREAD

**Issue by alekostsom** [Demigiant/dotween#445]
Please, can you add this so we can setup and trigger animations for UGUI elements (e.g. DoAnchorPos)?

Thanks for the awesome work, keep it up!

**Comment by Demigiant** [comment]
It's already there :) If you do a DOMove on a RectTransform it will actually do a DOAnchorPos in the background

**Comment by alekostsom** [comment]
Awesome! Thanks!
