### ISSUE TITLE
The type or namespace name 'DOTweenEditor' does not exist in the namespace 'DG'

### ISSUE THREAD

**Issue by sunflowr** [Demigiant/dotween#446]
Hi, I'm trying to create a preview in the editor and was going to use DOTweenEditorPreview but I get the following error:

The type or namespace name 'DOTweenEditor' does not exist in the namespace 'DG' (are you missing an assembly reference?)

I'm on latest dotween (not pro), Unity 2019.4.14f1, the code is inside a "#if UNITY_EDITOR" block.

Do I need to do anything  to make it work?

**Comment by Demigiant** [comment]
Ahoy! You can only access Unity's own editor API from a non-editor object. You need to write your code inside an editor-only class.

**Comment by sunflowr** [comment]
Hi and thanks for the quick answer, so you're saying it can't be used inside MonoBehaviour inside a block like this?

```
#if UNITY_EDITOR
[ContextMenu("Preview Show Animation")]
void PreviewShowAnimation_Editor()
{
// start playing the animation.
}
#endif
```

So only way of doing this is creating a custom editor to have a preview button for my monobehaviour?

**Comment by Demigiant** [comment]
No, sadly Unity has no way of dialoguing with editor DLLs/loose-scripts (other than its own) from runtime code/MonoBehaviours. You'll need to create a custom editor script, yes (and if you really want to communicate with it from a MonoBehaviour you can either use an event listened from the editor class, or direct Reflection from the MonoBehaviour itself).
