### ISSUE TITLE
DOTween.KillAll on scene unload

### ISSUE THREAD

**Issue by gayanW** [Demigiant/dotween#447]
I'm killing all the running tweens on scene unloads. This is to prevent DOTween from failing due to null references on scene loads. Just wanna make sure the approach I took to handle it is correct. 

BTW `autoKillOnCompletion` is set to TRUE.

```
    public class KillAllOnSceneUnload : MonoBehaviour
    {
        private void OnEnable()
        {
            SceneManager.sceneUnloaded += SceneManagerOnSceneUnloaded;
        }

        private static void SceneManagerOnSceneUnloaded(Scene scene)
        {
            DOTween.KillAll();
        }

        private void OnDisable()
        {
            SceneManager.sceneUnloaded -= SceneManagerOnSceneUnloaded;
        }
    }
```

**Comment by Demigiant** [comment]
Ahoy! Sorry if I saw this just now, but yes, it's definitely the correct approach :)

**Comment by Barina** [comment]
How does one kill all tweens in a specific scene before unloading it?

I see we can do something like this:
```
if (DOTween.TotalActiveTweens() > 0)
{
    var tweens = DOTween.PausedTweens();
    tweens.AddRange(DOTween.PlayingTweens());
    for (int i = 0; i < tweens.Count; i++)
        tweens[i]?.Kill();
}
```
But this will kill tweens resides in other scenes as well.
We can expand it to:
```
if (DOTween.TotalActiveTweens() > 0)
{
    var tweens = DOTween.PausedTweens();
    tweens.AddRange(DOTween.PlayingTweens());
    for (int i = 0; i < tweens.Count; i++)
    {
        var tween = tweens[i];
        if (tween != null && tween.target is GameObject target && target.scene == gameObject.scene) // <= this
            tween.Kill();
    }
}
```
But it doesn't work.. I'm still getting `Target or field is missing/null` afterwards.
What is the correct approach for this?
Plus, what guarantees we have that the target object is always of type `UnityEngine.GameObject`?
Is there a way to determine if a tween is part of some scene?

Maybe an override for methods `DOTween.PausedTweens()` and `DOTween.PlayingTweens()` that accept a scene as a filter?
Or a new method `DOTween.ActiveTweensForScene(UnityEngine.SceneManagement.Scene scene)`?


Edit:
I've noticed we can also use `DOTween.TweensById(gameObject.scene)` but this requires us to `.SetID(gameObject.scene)` on every tween we create.. (I'm using `DOTween.Sequence()` a lot) and we can't do this to tweens created using the `DOTweenAnimation` component.

**Comment by Chin-Su** [comment]
I have the same problem and I solved it by creating a list of Tween and killing Tween when it was done. Example in scene A I create List<Tween> tweens to stores all tween I handle in scene. In the last action or other point, I will check if the list has tween inactive, and I'll remove it. When I Load the next scene, I'll kill all tweens in the list.

`    private List<Tween> tweens = new();
     // Example to add tween
    tweens.Add(objectA.DoScale(Vector3.one, 0.25f).OnComplete(()=>{objectB.DoMoveX(10, 5).OnComplete(RemoveTween);});

private void RemoveTween()
    {
        foreach (var i in tweens.ToList())
        {
            if (!i.IsActive())
                tweens.Remove(i);
        }
    }


protected override void OnDestroy()
    {
        foreach (var i in tweens)
        {
            i.Kill();
        }
}

`

**Comment by Barina** [comment]
> I have the same problem and I solved it by creating a list of Tween and killing Tween when it was done. Example in scene A I create List tweens to stores all tween I handle in scene. In the last action or other point, I will check if the list has tween inactive, and I'll remove it. When I Load the next scene, I'll kill all tweens in the list.
> 
> ` private List tweens = new(); // Example to add tween tweens.Add(objectA.DoScale(Vector3.one, 0.25f).OnComplete(()=>{objectB.DoMoveX(10, 5).OnComplete(RemoveTween);});
> 
> private void RemoveTween() { foreach (var i in tweens.ToList()) { if (!i.IsActive()) tweens.Remove(i); } }
> 
> protected override void OnDestroy() { foreach (var i in tweens) { i.Kill(); } }
> 
> `
So your
Why not just use `tween.SetAutoKill().OnKill(() => { /* clean stuff here */ });`

**Comment by Barina** [comment]
> I have the same problem and I solved it by creating a list of Tween and killing Tween when it was done. Example in scene A I create List tweens to stores all tween I handle in scene. In the last action or other point, I will check if the list has tween inactive, and I'll remove it. When I Load the next scene, I'll kill all tweens in the list.
> 
> ` private List tweens = new(); // Example to add tween tweens.Add(objectA.DoScale(Vector3.one, 0.25f).OnComplete(()=>{objectB.DoMoveX(10, 5).OnComplete(RemoveTween);});
> 
> private void RemoveTween() { foreach (var i in tweens.ToList()) { if (!i.IsActive()) tweens.Remove(i); } }
> 
> protected override void OnDestroy() { foreach (var i in tweens) { i.Kill(); } }
> 
> `

So your `RemoveTweens()` only removes the tweens from a list, but on destroy you kill only those within that list, right? 
That means there could still be some active tweens.. 
Why don't you just use the following?
```
myTween
    .SetAutoKill() // <-- this
    .OnKill(() => { ... }) // optional. maybe for cleaning..
    .Play(); // rest of your instructions..
```
