### ISSUE TITLE
Does the license allow using modified versions?

### ISSUE THREAD

**Issue by Shayan-To** [Demigiant/dotween#449]
The license explicitly states that it is not permitted to distribute any modifications in source form. But is it allowed to use the modifications in a game and distribute the game in compiled form?

**Comment by Demigiant** [comment]
Yes, you can modify it as much as you want as long as it's only distributed inside a compiled game.

**Comment by johanhelsing** [comment]
Sorry, but if this is the case, you really shouldn't advertise the software as open-source (http://dotween.demigiant.com/).

i.e. you're violating the 3rd criteria here: https://opensource.org/osd

**Comment by Demigiant** [comment]
I'm using a modified version of the open source artistic license: it is considered valid open source. From the same website you linked: https://opensource.org/licenses/Artistic-2.0

EDIT: linked to v2 instead of v1

**Comment by johanhelsing** [comment]
I think you removed the section named "Distribution of Modified Versions of the Package as Source"? I think this makes your license no longer be an open source license.

I.e. it looks like in the artistic license I'm allowed to redistribute patches i write myself without your consent, but with your I'm not.

**Comment by Demigiant** [comment]
I'll investigate it better then (but in the new year), I was pretty sure it was conforming. Allowing the redistribution of modified sources is not really viable in this case (and in the case of most Unity assets): it's a clause I added after I saw my previous tween engine being partially copied and published with another name in the past, which wasn't very nice. Do you have any suggestions on what other terms I might be looking for?
