### ISSUE TITLE
DOKill not available for Materials

### ISSUE THREAD

**Issue by fakegood** [Demigiant/dotween#45]
I am currently killing tweens for material.DOColor() with DOTween.Kill(material). Is it intentional for not including DOKill() for materials?

**Comment by Demigiant** [comment]
Hi,

The DOKill extension method is based on Component types, and Material is not, but that's my bad: just added it and will be out with the next version. In the meantime you can download the update [here](http://dotween.demigiant.com/tmp/DOTween_1_0_820.zip).

Cheers

**Comment by fakegood** [comment]
Awesome! :+1:
