### ISSUE TITLE
DOTween Destroying Object

### ISSUE THREAD

**Issue by eraban24** [Demigiant/dotween#452]
I recently opened an issue but I believe this issue needs its own thread.

![giphy](https://user-images.githubusercontent.com/75085091/100409858-efb66a80-3092-11eb-91be-b010647ff2a8.gif)
As you can see in the fourth circle the player is getting destroyed. There are no collisions and no scripts is calling a `Destroy()` function. Now, once I stopped using dotween for all the circles (only) the player stopped being destroyed. The player is getting destroyed only when the circles are using dotween and the player is hitting that particular left part of the circles or else the player is not destroyed.

This has become a huge problem for the players. I have been trying to sole this for 1-2 months and cannot crack it.

Can anyone please help me?
Thanks in advance.

[NOTE]
since you closed this I am writing here that I am not using any DOTween call backs. The player is getting destroyed as it completely disappears from the hierarchy.

**Comment by Demigiant** [comment]
Ahoy, I can safely say that there is absolutely no way that DOTween is destroying an object (it contains no code for that) unless you manually told it to destroy it via a callback. Also, are you sure your object is being destroyed and not scaled down to zero? From this gif I can't really say what's happening, but if disabling DOTween prevents this then you either:
1) have added a tween callback that either destroys or scales down or teleports your object
2) have created a tween that scales down or teleports your object
