### ISSUE TITLE
DOTweenAnimation.DOPlay only work the first time

### ISSUE THREAD

**Issue by gayanW** [Demigiant/dotween#457]
DoTweenAnimation script is attached to a Button. And `DOTweenAnimation.DOPlay` is registered to the button's OnClick event in the inspector.

![Screenshot from 2020-12-24 13-46-26](https://user-images.githubusercontent.com/5927747/103074077-dd2a4500-45ee-11eb-93b5-f163916e1112.png)

However, punch/scale animation only plays the first time the button is being clicked. Please let me know how to make the animation play on every button click?

**Comment by Demigiant** [comment]
Play just plays the tween in the playing direction, so if it's complete it has nothing to play. You need to call `DORestart` instead, which does a rewind+play.
