### ISSUE TITLE
Two DOTween Animation components break behaviour

### ISSUE THREAD

**Issue by Noblauch** [Demigiant/dotween#458]
We are currently stuck in a situation that we can't resolve ourself, it must be fixed in the plugin.
What we want to achieve:
Objects in the scene can have two DOTween Animation components. One with the ID "entry" and one with "exit". Depending on what happens, the entry or exit animations are played via the ID.
But if you add two components with the same type, one FROM, the other TO, it destroys the behaviour of the tweens. It seems like both tweens are taken into account when played, which even reverses the original direction.

You can easily recreate this issue. Just add the following two tweens and observe its behaviour. If you start the scene, the image is located y: 100 (due the From tween component, waiting to tween in). But if you start the tween "entry" it will move to y: 200 instead to y:0, where its original origin was.
![DOTween Bug](https://user-images.githubusercontent.com/23262032/103681662-0e5c2b00-4f88-11eb-8e44-3edb90d15674.png)

Here you can see (green dot original height) and the white dot doesn't tween to this original position, but half the way. If I remove the second DOTween component (TO y: 100) it is able to tween to 0,0. Otherwise the tween would start from top and move half the way again.
https://user-images.githubusercontent.com/23262032/103681686-174cfc80-4f88-11eb-8449-b5614f742dfb.mov
**Remember:** The expected behaviour is, that when I play the entry animation, the white circle moves from y:100 to y:0 (the green original origin). Instead it moves **UP**! Ó.ò If I remove the second tween (which is never triggered), the behaviour is normal again and the tween does what it's supposed to.
Btw: In editor the tween works as expected too.

**Comment by Demigiant** [comment]
Ahoy! I'm going to be out tomorrow (it's holiday here, and a special one because I'll see my aunt and grandma for the first time in months) but the day after I'll check this out (or even tomorrow, if I don't get back too late).

**Comment by Noblauch** [comment]
Wow that would be awesome! Have a good time.
BTW: We are currently using:
DOTween v1.2.335 [Release build]
DOTweenPro v1.0.178

**Comment by Noblauch** [comment]
Okay, we resolved the issues now, and I can tell you all what happened:

I just recently came back to this problem and since we couldn't wait any longer I started to trace back the code to figure out what caused the problem, and actually it was quite simple.

I used this code to play a specific animation on a GameObject with multiple DOTwennAnimation components:
`void Play(string idToPlay)
    {
        var animations = GetComponentsInChildren<DOTweenAnimation>(true);
        foreach (var anim in animations)
        {
            if (anim.id != idToPlay) continue;
            anim.DOPlay();
        }
}`

well it turned out, that **DOTweenAnimation.DOPlay()** calls **DOTween.Play(this.gameObject)** internally which caused every animation on this GameObject to play. I didn't see in the documentation that this is the desired behaviour, indeed it is counterintuitive to how other systems in Unity function.

A workaround is pretty easy though, just call **anim.tween.Play()**.
I'd say this should be the default behaviour, since if I pick a very specific component, I'll probably just want to play this component. Otherwise I would have gotten reference to the GameObject and called DOTween.Play() instead..

I call it closed for now ;)
But hope you can utilise this feedback in any way, have a good one ;)

**Comment by santelelle** [comment]
This same unexpected default behavior just gave me a headache. I support the suggestion that the default behavior of DOTweenAnimation.DOPlay() should be to play only that specific animation.
