### ISSUE TITLE
Kill not working as expected?

### ISSUE THREAD

**Issue by nicmar** [Demigiant/dotween#461]
I have this code to fade in and out a light. Imagine a toilet light that turns itself on when motion, and off if no motion for 4 seconds.

```
private Sequence seq;

public void Enable() {
	light.enabled = true;

	seq.Kill();
	Debug.Log("<color=lime>ENABLE: Fade from " + light.intensity + " to " + maxIntensity + "</color>");
	seq.Append(DOTween.To(x => light.intensity = x, light.intensity, maxIntensity, durationOn)
		.SetEase(curveTweenOn)
		.OnComplete(() => {
			Debug.Log("<color=lime><b>ENABLE complete</b></color>");
			onLightOn?.Invoke();
		}));
	seq.Play();
}

public void Disable() {
	seq.Kill();
	Debug.Log("<color=red>DISABLE: Fade from " + light.intensity + " to " + minIntensity + "</color>");
	seq.Append(DOTween.To(x => light.intensity = x, light.intensity, minIntensity, durationOff)
		.SetEase(curveTweenOff)
		.OnComplete(() => {
			Debug.Log("<color=red><b>DISABLE complete</b></color>");
			light.enabled = false;
			onLightOff?.Invoke();
		}));
	seq.Play();
}
```

However if the Disable() function starts, but before it has finished, the Enable() method is called, i expect the Kill() to stop the disable method from executing, but it still calls it's OnComplete.

The console log of this looks like:
```
ENABLE: Fade from 0 to 0.8
ENABLE complete
DISABLE: Fade from 0.8 to 0 <-- Starting to fade out
ENABLE: Fade from 0.5363806 to 0.8 <-- This should kill the Disable sequence
DISABLE complete <-- Yet it runs it's OnComplete
ENABLE complete
```

Am I doing something wrong?

Also I first tried this, but it was never called, so at least the OnComplete inline works. But I don't see why this doesn't work.
```
seq.OnComplete...
```

Thank you in advance!

**Comment by Demigiant** [comment]
Ahoy! There's a big problem there, which is that you're killing a Sequence AND ONLY THEN adding stuff to it. Once killed/destroyed, a Sequence needs to be recreated before you can Append stuff to it (via `seq = DOTween.Sequence()`). The newer version of DOTween I'm working on warns you of this via console logs, but older versions should still prevent this to happen. What version of DOTween are you on? And do you have recycling on by any chance?

**Comment by nicmar** [comment]
Ahh I remember now, I think i did this somewhere but forgot!
Just adding that right after kill worked perfectly. Thanks a lot! :)

EDIT: I have DOTween Pro Version 1.0.178 - January 31, 2020. Maybe time to upgrade? :) Also it says DOTween v1.2.335 [Release Build]
