### ISSUE TITLE
After using the `Application.Unload()` ,DoTween cannot run 

### ISSUE THREAD

**Issue by Mediary** [Demigiant/dotween#464]
After using the `Application.Unload()` method to suspend the program and reopen it, DoTween cannot run without error

**Comment by Mediary** [comment]
<img width="288" alt="截屏2021-01-26 下午7 09 39" src="https://user-images.githubusercontent.com/41142572/105837717-0da83900-600a-11eb-9b67-d5ac464d380f.png">
Is my version too old?

**Comment by Demigiant** [comment]
Hi, the version is ok, but can you tell me more? What happens when you reopen the app? Are you getting errors (in which case, what), or something else?

**Comment by Mediary** [comment]
When I run the program for the first time, everything is normal. When I use the unload () method, the program is suspended. After I open it again, the tweet animation will not be played. Without any error, it is suddenly stopped in the first tweet animation

It's like 'Tween tween'= transform.DoMove (XXX, XXX); ` 
the object will not move in any wa

**Comment by Demigiant** [comment]
Mhmm, are you sure that your application is being updated after you re-enter it? The only reason why a tween would stop running is either if the DOTween GameObject's Update method stops being called, if you killed them somehow, or if they were completed. If you create a new tween does it run?

**Comment by Mediary** [comment]
![image](https://user-images.githubusercontent.com/41142572/105932349-b9439e80-6087-11eb-9135-dd11b3955065.png)
My code is like this, I do a DoScale in Awake () after the program starts, and I don't do any active operation to kill tweens

**Comment by Mediary** [comment]
I just updated the store's latest version Pro v1.0244, and I found that this problem has been solved. However, until now, I still don't know how it caused this problem

**Comment by Demigiant** [comment]
Ahhhhh! I had made an update to fix some issues with the focusing/unfocusing of the app and apparently they also fixed your problem with unloading (maybe the real problem wasn't truly related to the unloading as much as to the unfocusing), I didn't connect the dots, sorry, but glad it's solved :)

**Comment by Mediary** [comment]
Anyway, thank you!
