### ISSUE TITLE
Unable to set ease for sequence (sequence ease apparently stuck with quadOut or something else)

### ISSUE THREAD

**Issue by ExplodingPenguin** [Demigiant/dotween#466]
I was unable to change the easing curve of a sequence.
With a linear easing, the time should be 0.5f at 90 degree but i am not getting that i am assuming it is using some different easing curve.

Click function
 public void OnPointerClick(PointerEventData eventData)
{
        StartCoroutine(DebugTime());

        Sequence sequence = DOTween.Sequence();
        sequence.SetEase(Ease.Linear);
        sequence.Prepend(transform.DORotate(new Vector3(0, 180, 0), 1.0f));
        sequence.Play();
}

printing out rotation and time,
IEnumerator DebugTime()
{ 
        float timeTaken = 1.0f;

        float elapsedTime = 0;
        while (elapsedTime < timeTaken)
        {
            elapsedTime += Time.deltaTime;
            Debug.LogError("rotation y : " + transform.rotation.eulerAngles.y + "     time : " + elapsedTime);
            yield return null;
        }   
}

When i am not using the sequence and just do this. the time and rotation match up.
transform.DORotate(new Vector3(0, 180, 0), 1.0f).SetEase(Ease.Linear);

**Comment by Demigiant** [comment]
Ahoy

Sequences ease and Tweeners ease are a separate thing, that overlap each other. By default (unless you changed it in DOTween's Settings panel), a Tweener has an OutQuad ease while a Sequence has a Linear ease (meaning that any Tweener you insert/append inside a Sequence will not be multiplied by any other ease)

So in your case, to have a fully linear ease, you should chain the ease to the nested tween, not to the Sequence:

`sequence.Prepend(transform.DORotate(new Vector3(0, 180, 0), 1.0f).SetEase(Ease.Linear));`
