### ISSUE TITLE
Camera Shake Loop

### ISSUE THREAD

**Issue by Animtree** [Demigiant/dotween#472]
Hi, I produce a lot of looping GIFs, I'd love to get a version of the camera shake that is random but loops perfectly so I can have nice edits. There's no viable solution available atm apart from hand-animated cameras.
Thanks,
Richard.

**Comment by Demigiant** [comment]
Ahoy, if you set the last shake parameter (fadeOut) to FALSE the shake won't lose intensity and will end exactly where it began, making it perfect for looping GIFs

**Comment by Animtree** [comment]
Is that option only available via code? I'm using the DOTween Animation visual editor [edit: latest version]

**Comment by Animtree** [comment]
I turned off fadeout globally and I've got the effect I want now 👍
