### ISSUE TITLE
1.2.420: The type 'TweenerCore<,,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'DOTween, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. [Assembly-CSharp]

### ISSUE THREAD

**Issue by HugoCortell** [Demigiant/dotween#480]
On version 1.2.420 I get the following message whenever I try to use dotween with my IDE.

The type 'TweenerCore<,,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'DOTween, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. [Assembly-CSharp]
Not exactly sure what to do.

**Comment by HugoCortell** [comment]
I tried adding the following to my csproj file but to no avail.
```xml
<Reference Include="TweenerCore">
       <HintPath>D:/Unity/Projects/Machine Learning Experiments/Assets/Plugins/DOTween/DOTween.dll</HintPath>
     </Reference>
```

**Comment by Astrobinary** [comment]
Im not sure if it will work for you, but I just moved the Demigiant folder from plugins into the main asset directory then moved it back and restarted Unity.

**Comment by HugoCortell** [comment]
Finished my project so it does n

> 
> 
> Im not sure if it will work for you, but I just moved the Demigiant folder from plugins into the main asset directory then moved it back and restarted Unity.

Seems like that did the trick!
