### ISSUE TITLE
Couldn't load Modules system & DOTweenPath.Awake () Issue

### ISSUE THREAD

**Issue by cosmicmosmic** [Demigiant/dotween#492]
Current Unity Version : 2019.4.26f
Current Dotween Version : 1.2.420(Pro 1.0.244)

Old Dotween Version(Before Migrating) : https://github.com/Demigiant/dotween/tree/96065a6e653396f67dd4f2310e596938cade1ec5
(I don't know the exact version. I used "fixed dojump not working .NET 4.6" version)

We are currently migrating the game from Unity 2017 to 2019. Also upgrade Dotween.

We got error on Android build. (it works fine on unity editor)

**<color=#0099bc><b>DOTWEEN ► </b></color>Couldn't load Modules system
06-01 22:41:11.314  8127  8170 E Unity   : UnityEngine.Logger:Log(LogType, Object)
06-01 22:41:11.314  8127  8170 E Unity   : UnityEngine.GameObject:AddComponent()
06-01 22:41:11.314  8127  8170 E Unity   : DG.Tweening.Core.DOTweenComponent:Create()
06-01 22:41:11.314  8127  8170 E Unity   : DG.Tweening.DOTween:Init(DOTweenSettings, Nullable1, Nullable1, Nullable1)
06-01 22:41:11.314  8127  8170 E Unity   : DG.Tweening.DOTween:AutoInit()
06-01 22:41:11.314  8127  8170 E Unity   : DG.Tweening.DOTween:Sequence()
06-01 22:41:11.314  8127  8170 E Unity   : bkf:oxe(Int32)**

Most of the functions worked without any problems.
There is a problem with the DoPath function.
The function is not working.

Here is error callstack when instantiate object from asset bundle resource.

that object have dopath component.

**NullReferenceException: Object reference not set to an instance of an object., DG.Tweening.DOTweenPath.Awake () (at <00000000000000000000000000000000>:0)
UnityEngine.Object.Instantiate[T]  ..........**

Always Thank you.

**Comment by Demigiant** [comment]
Ahoy,

This is weird. In practice, [this method](https://github.com/Demigiant/dotween/blob/develop/_DOTween.Assembly/DOTween/Core/DOTweenUtils.cs#L73-L92) can't find DOTween's loose scripts (related to DOTweenPath I would assume) in your project on Android (it's a required initialization reflection call). Is it possible that you're also including DOTween's modules in an asset bundle and thus they're not ready at startup? Or that you're excluding Reflection from your mobile build?

**Comment by cosmicmosmic** [comment]
Hi.
We solved the problem.
The cause was method and class obfuscation.
The problem disappeared after releasing the obfuscation of the DG and DG.Tweening namespace.
Thank you.

**Comment by Zony-Zhao** [comment]
@Demigiant I encountered this when I decorated the MonoBehavior class with [ExecuteInEditMode]. (The class is using Dotween of course.)

**Comment by Demigiant** [comment]
Ahoy! There's a special editor API to run DOTween in editor-mode, but it can't run normally with ExecuteInEditMode.
