### ISSUE TITLE
Goto with full duration not working

### ISSUE THREAD

**Issue by appetizermonster** [Demigiant/dotween#5]
Hi
Thanks to you, I was interested in HOTween and have used it very well.
so also I now have an interest in DOTween.
anyway, I found a bug that give me unexpected result.
following is pseudo-code, and DOTween version is 1.0.346
Thank you.

```
var seq = DOTween.Sequence();

seq.Insert(0, blahblah);
seq.SetAutoKill(false);

seq.Goto(seq.Duration());        // not working, nothing happens. i think it should be work
seq.Goto(seq.Duration()-0.001f); // working (workaround)
```

**Comment by Demigiant** [comment]
Hi,

I think this might've been caused by the same issue that was causing issue #4, which I just fixed. Can you download this [update v1.0.350](http://dotween.demigiant.com/tmp/DOTween_1_0_350.zip) and let me know? Everything seems to work here.

**Comment by appetizermonster** [comment]
yeah, i updated to v1.0.350 and now it seems everything is ok. thank you.

**Comment by Demigiant** [comment]
Great :)
