### ISSUE TITLE
Amplitude parametr does not work in the function SetEase for Ease.OutBounce

### ISSUE THREAD

**Issue by ShadowTM** [Demigiant/dotween#50]
Please use amplitude parametr for Ease.OutBounce

**Comment by Demigiant** [comment]
Hi!

The OutBounce ease is the default algorithm by Robert Penner, and doesn't use amplitude. As an alternative, you could either make the tween slower (which will make the bounce more soft), use a Punch tween, or create a custom AnimationCurve and use that as an ease.

**Comment by thygrrr** [comment]
Hmm, an amplitude-based bounce does sound like a sensible request, though. 

Penner's functions are very much antiquated design in terms of being mostly magic numbers.
