### ISSUE TITLE
DOTween.Kill(intId) doesn't work

### ISSUE THREAD

**Issue by osience** [Demigiant/dotween#504]
I use DOTween in my lua code, I create tweens in a for loop and assign them a same intId. In another function I use DOTween.Kill with the intId to kill the tweens , but the tweens played as Normal after the kill function.
`for i = 1,10 then
    local tTweener = tNodeContent:DOLocalMove(Static.endPos,Static.speed)
    tTweener:SetId(1000)
    tTweener:SetEase(CSEase.OutCubic)
end`
the kill function:
`CSDOTween.Kill(1000,true)`

**Comment by qiudeqian** [comment]
I use DOTween in my lua code, I create tweens in a for loop and assign them a same intId. In another function I use DOTween.Kill with the intId to kill the tweens , but the tweens played as Normal after the kill function.
`
for i = 1,10 then 
        local tTweener = tNodeContent:DOLocalMove(Static.endPos,Static.speed)
        tTweener:SetId(1000)
        tTweener:SetEase(CSEase.OutCubic)
end
---------------------
CSDOTween.Kill(1000,true)
`
