### ISSUE TITLE
DOPath slows down as it reaches final point in path list.

### ISSUE THREAD

**Issue by ChrisJHullEPM** [Demigiant/dotween#506]
Is there any customisation to DOPath speed settings besides assigning an overall time to execute the path? 

What if you want linear animation that is consistently moving? At the moment there is a random slow down curve that changes the speed towards the last point.

**Comment by Demigiant** [comment]
The path tween uses the default ease which is OutQuad. Set the ease to Linear (via the SetEase tween method) to have a fully linear speed

**Comment by FunCrafter1234** [comment]
Version 1.0.335, Unity 2022.1.23f1. I cant get it to work. Either I am doing something very wrong or its broken.
![grafik](https://user-images.githubusercontent.com/20505406/221017026-fb091b83-f77a-4254-80dc-e5a87f792a94.png)

This SetEase() does not work. I am still seeing slowdowns over time as if the standard ease would still be taken, any help?

**Comment by WuchiOnline** [comment]
@FunCrafter1234 I was having the same issue, until I realized that PathType and SetEase both need to be linear for it to work as expected. The CatmullRom pathtype is probably conflicting with your Tween's easePath.

**Comment by FunCrafter1234** [comment]
I tried it and for some reason that still didnt change much visually. Its fine though I worked arround it and now I am almost at the result I was aiming for and it still looks good enough. But thanks for the info!

**Comment by Demigiant** [comment]
Ahoy! Aside for the ease, which is usually the main reason, also check that your path doesn't have some waypoints that have different Zs than the others (or Ys, depending on the orientation), which would make segments appear short in 2D but being actually longer in 3D because of the invisible depth, and thus take more time

**Comment by FunCrafter1234** [comment]
That would make senese, I will check later on. I actually generate a random point between two others that has a random x and y coordinate to generate a random curve. Thanks for the info!
