### ISSUE TITLE
Preview doesn't update in SceneView

### ISSUE THREAD

**Issue by NibbleByte** [Demigiant/dotween#512]
Hi,

We've noticed that when previewing tween animations with DOTweenAnimation it doesn't update in the SceneView, (only in the GameView). It happens only when you move the mouse over the SceneView, forcing it to redraw.
We need this because we have a lot of prefabs that will be tweened and want to preview them in the prefab edit mode (prefab stage) which is only visible in the SceneView, never the GameView.

We fixed the issue by inserting one line to the `DOTweenAnimationInspector.cs` after line 292:
```C#
bool isPreviewing = _settings.showPreviewPanel ? DOTweenPreviewManager.PreviewGUI(_src) : false;
if (isPreviewing) UnityEditorInternal.InternalEditorUtility.RepaintAllViews(); // Force redraw every frame if previewing.
```
It will redraw only when in preview mode so I don't consider this as a huge performance loss, but if you find a way to update only the SceneView**s** (there may be multiple), go for it!

DOTween v1.2..632
DOTweenPro v1.0.310

Cheers

**Comment by Demigiant** [comment]
Ahoy! Could you tell me on what version of Unity and OS are you? Because here the scene shows the animation correctly

**Comment by NibbleByte** [comment]
We're using Unity 2020.3.12f. 
Hmmm.... for some reason I can't reproduce this anymore after removing the fix.... I may have overlooked something.
Sorry to bother you, closing the ticket. Will reopen it if I reproduce the bug again.

**Comment by Demigiant** [comment]
No bother and glad it's solved. Sometimes Unity goes cray cray
