### ISSUE TITLE
DORotateQuaternion not always shortest path

### ISSUE THREAD

**Issue by koblongata** [Demigiant/dotween#52]
DORotateQuaternion does not always animate along the shortest path, in some cases it will go the other way round, the long way.

**Comment by Darelbi** [comment]
same issue here. found any workaround? (also with DORotate & DORotateLocal extension methods on transform). Just try  a rotation about Y from  270 degrees to 180. That happens also when tweening directly the angle value before feeding it to eulerAngles that makes me thinking that's an issue also with unity

**Comment by MattRix** [comment]
Yeah I've noticed this issue as well. I believe it's because DORotateQuaternion is easing all of the quaternion components (xyzw), which isn't the correct way to tween a quaternion rotation. It should use Quaternion.Slerp instead.

**Comment by slacker-jake** [comment]
I've noticed this too.  IS this likely to get fixed anytime soon?

**Comment by Xeoneid** [comment]
Same here, has anyone found a workaround?

**Comment by Xeoneid** [comment]
I've working on it. Seems that DORotate uses the shortest way

**Comment by DmitriyYukhanov** [comment]
@Demigiant we need this!! =D

I'm too dumb and made a such workaround:

```
DOVirtual.Float(0, 1, animationDuration, OnRotate);
private void OnRotate(float value)
{
	transform.localRotation = Quaternion.Slerp(sourceRotation, targetRotation, value);
}
```

**Comment by Demigiant** [comment]
Damn Quaternions! Sorry I skipped this for so long, but [here you go](http://dotween.demigiant.com/tmp/DOTween_1_2_230.zip) :P

P.S. *If you're using DOTween Pro DON'T GET THIS!* This new version also contains a new From overload that allows to directly set a From value, and the current Pro version doesn't have that implemented yet. If that's your case within the weekend I'll push the Pro on the Asset Store :P

**Comment by DmitriyYukhanov** [comment]
Thank you a lot Daniele! ^^
You rock, and do it fast, as always (I know it's your clones hehe)!

**Comment by Demigiant** [comment]
I wouldn't say "fast" in this case, I'll have to train my clones better :D

P.S. Dmitriy if you want a DOTween Pro build on the fly obviously you can just ping me via mail or on twitter ^_^

**Comment by DmitriyYukhanov** [comment]
Thanks, Daniele! No hurry here, I prefer to give you more time to better train your clones instead! =D
