### ISSUE TITLE
More detailed warning

### ISSUE THREAD

**Issue by djnjbjb** [Demigiant/dotween#521]
Occasionally I get this warning:

> DOTWEEN ► Target or field is missing/null () ► The object of type 'Transform' has been destroyed but you are still trying to access it.
> Your script should either check if it is null or you should not destroy the object.

I have several GameObjects running DOTween. So I don't know which one gives this warning.
It would be helpful if DOTween gives me the name of the GameObject or some similar info.
It would also be helpful if I can have my own warning.

Is there already any way to locate the GameObject which gives the warning?
I'm not very familiar with DOTween, so I may miss something.
I tried disable SafeMode. But I can't locate the GameObject from the error message either.

**Comment by Demigiant** [comment]
Ahoy!

If you enable Safe Mode and both Debug Mode toggle on the bottom of DOTween's preferences the report will include the name of the gameObject. Also if you select the DOTween gameObject at runtime you will get some extra info that might help.

**Comment by djnjbjb** [comment]
😄
Yes it is. Thank you.

**Comment by anelkadev** [comment]
> Ahoy!
> 
> If you enable Safe Mode and both Debug Mode toggle on the bottom of DOTween's preferences the report will include the name of the gameObject. Also if you select the DOTween gameObject at runtime you will get some extra info that might help.

Afternoon bro. Is there any way to turn it off? Thank you

**Comment by wiwii** [comment]
> > Ahoy!
> > If you enable Safe Mode and both Debug Mode toggle on the bottom of DOTween's preferences the report will include the name of the gameObject. Also if you select the DOTween gameObject at runtime you will get some extra info that might help.
> 
> Afternoon bro. Is there any way to turn it off? Thank you

1.In Editor top menu:"Tools"->"Demigiant"->"DoTween Utility Panel";
2.in the popup,choose"Preferences"->unchecked "Debug Mode"->"Log Behaviour" change to "Default"
and then,the gameobject name will not be show.
also you may only print errors not warning with "Log Behaviour" change to "Errors Only"

**Comment by anelkadev** [comment]
> > > Ahoy!
> > > If you enable Safe Mode and both Debug Mode toggle on the bottom of DOTween's preferences the report will include the name of the gameObject. Also if you select the DOTween gameObject at runtime you will get some extra info that might help.
> > 
> > 
> > Afternoon bro. Is there any way to turn it off? Thank you
> 
> 1.In Editor top menu:"Tools"->"Demigiant"->"DoTween Utility Panel"; 2.in the popup,choose"Preferences"->unchecked "Debug Mode"->"Log Behaviour" change to "Default" and then,the gameobject name will not be show. also you may only print errors not warning with "Log Behaviour" change to "Errors Only"

Sorry for the late response. But can you tell me why when I LoadScene, Dotween shows this message. And does this Dotween bug affect the game? Thank you very much

**Comment by Demigiant** [comment]
It's not a bug in DOTween, but in the target of a tween becoming null (aka destroyed) while the tween is still running. Ideally you should kill a tween before destroying its target, but otherwise safe mode will capture that error and deal with it automatically (without affecting the game)

**Comment by zeyangl** [comment]
Maybe it's more ideal to make this warning a normal log, instead of a warning? I find it not it not very useful and I get a bunch fo those when unloading a scene. It's usually the only bunch of warnings I get from dotween.
