### ISSUE TITLE
Changing DOTween Path speed in coroutine

### ISSUE THREAD

**Issue by vvp3** [Demigiant/dotween#540]
ontriggerenter, I would like to have this 

			if (_pathMove.duration > 0.15f)
				StartCoroutine(WaitABit());

the problem is that I cannot setup the Couroutine properly in order to have this working gradually: _pathMove.duration -= 0.001f;

it only gets called in the same frame - why ?

What i want to achieve is this: on triggerenter to have a gradually decaying speed and on trigger exit  to set a big speed (the later one i did allready).
Do i need to manipulate the speed between the current point and the next one as the duration icannot be affected at runtime ?

**Comment by Demigiant** [comment]
Ahoy!

You can't correctly change the speed of a tween by changing its duration. Instead you should change the tween's internal timeScale, for example:
`myTween.timeScale = 0.5f; // make it half-speed`
Consider that you can also tween a tween's timeScale ([myTween.DOTimeScale](http://dotween.demigiant.com/documentation.php#tweenShortcuts))

**Comment by vvp3** [comment]
ill try on the path ty ;)

**Comment by vvp3** [comment]
there is no timescale on path

![image](https://user-images.githubusercontent.com/40170139/146170441-e80018ea-57bb-4b21-9d70-45adc3ef1272.png)

**Comment by Demigiant** [comment]
Ah you need to act on the tween, not the DOTweenPath component. So after
you create the path you should get it's tween via the GetTween() method and
then you have access to more advanced functions.
