### ISSUE TITLE
int id not working through TweenParams Object

### ISSUE THREAD

**Issue by Ibrahim-Rashwan** [Demigiant/dotween#542]
When Assigning an id using TweenParams and check for that id later using the DOTween static functions it's not returning the tween maybe the because the refrence of the object changed at some point when copying data from the params to the tween using the SetAs() function

defParams = TweenParams.Params;  //Assign the parameters from start
defParams.SetId(1);

transform.DOScale(1, 1).SetAs(defParams);  //When calling the tween making sure to copy the parameters

DOTween.TweensById(1);  // always returning 0 means didn't find the tween

Notes: 
SetAutoKill -> false
Tried this with int id's only
When i used SetId(1) as the tween directly it worked normally

**Comment by Demigiant** [comment]
Ouch, you're right, both string IDs and int IDs are not set correctly via TweenParams, sorry. [Here's an update](http://dotween.demigiant.com/tmp/DOTween_1_2_655_unity567.zip) that fixes it.

**Comment by Ibrahim-Rashwan** [comment]
> Ouch, you're right, both string IDs and int IDs are not set correctly via TweenParams, sorry. [Here's an update](http://dotween.demigiant.com/tmp/DOTween_1_2_655_unity567.zip) that fixes it.

Thanks for the quick reply will check the update...
