### ISSUE TITLE
JoinCallback on Sequences

### ISSUE THREAD

**Issue by EricBatlle** [Demigiant/dotween#545]
Hi, there's a way to mimic `Join()` method on `Sequences` but with custom callbacks? 

I know `AppendCallback()` exists, but it won't work on parallel, it will be triggered at the end of the sequence (or where you've done the append).

There's a posibility of something like JoinCallback? If not, why, which are the limitation?

Thanks and keep the good work! :D

**Comment by Demigiant** [comment]
Ahoy! You can use `InsertCallback`. It's not as intuitive since you'll have to pass the right time position, but I'll add this to my TODO list.

**Comment by santelelle** [comment]
Hi, I would also really like this feature :)
