### ISSUE TITLE
PlayBackwards WaitForCompletion bug

### ISSUE THREAD

**Issue by ghost** [Demigiant/dotween#55]
I have simple code:

`// _tweener is field on class
_tweener = Square.transform.DOLocalPath(Path.Select(p => p.transform.position).ToArray(), Path.Count \* _oneCellDuration).SetAutoKill(false);

// This is ok (function wait for completion)
yield return tweener.WaitForCompletion();

// In my class I have undo function with this code
_tweener.PlayBackwards();

// This not wait because _tweener has isComplete == true
// PlayBackwards not reseting isComplete 
yield return _tweener.WaitForCompletion();`

**Comment by Demigiant** [comment]
Hi,

I think the issue there is that the tween is actually complete (since it's not updated) until the next frame. Can you try adding a 

yield return null;

before the last WaitForCompletion and see if it works?

**Comment by ghost** [comment]
No this not help because I dont call this in one function. Like I said I have PlayBackwards in separate function that I call when user tap on undo button.
But when I change WaitForComplete to WaitForRewind it's ok :)

**Comment by Demigiant** [comment]
Great. And yes, WaitForRewind is the better choice there ;)
