### ISSUE TITLE
DotweenAnimation won't restart

### ISSUE THREAD

**Issue by equizo** [Demigiant/dotween#553]
I tried DotweenVisualManager with all combinations of OnEnable, OnDisable callbacks, but if the animation is completed and I toggle the gameobject with the component - animation won't restart when the object is setActive to true;
1.2.420
Pro 1.0.244

**Comment by Demigiant** [comment]
Ahoy,

By default a tween will auto-kill when complete (you can change default behavior in DOTween's preferences, but I recommend keeping that on), so you have to disable autoKill on the Animation (toggle on the top of its Inspector) if you want to reuse it
