### ISSUE TITLE
When I get a tween, how can I know that how much time it last / left ?

### ISSUE THREAD

**Issue by atkdefender** [Demigiant/dotween#554]
I want to kill a running tween, then create a new one.
But the totally running time must keep the same.

**Comment by Demigiant** [comment]
Ahoy,

You can get a tween's duration via
`myTween.Duration()`
and subtract from it
`myTween.Elapsed()`

More here: http://dotween.demigiant.com/documentation.php#gettingData

Cheers,
Daniele

**Comment by atkdefender** [comment]
> Ahoy,
> 
> You can get a tween's duration via `myTween.Duration()` and subtract from it `myTween.Elapsed()`
> 
> More here: http://dotween.demigiant.com/documentation.php#gettingData
> 
> Cheers, Daniele

Thx! I thought that will be a value so I miss it.
