### ISSUE TITLE
How to scale an image 7×, then 1 second late scale it 0×?

### ISSUE THREAD

**Issue by atkdefender** [Demigiant/dotween#557]
I write:
>         transform.DOScale(7f, 0.3f);
>         transform.DOScale(0f, 0.2f).SetDelay(1f);
But only the first line works.

**Comment by j-schoch** [comment]
use a Sequence my dude

```
Sequence scaleSequence = DOTween.Sequence();
scaleSequence.Append(transform.DOScale(7f, 0.3f));
scaleSequence.AppendInterval(1f);
scaleSequence.Append(transform.DOScale(0f, 0.2f));
```

**Comment by atkdefender** [comment]
> use a Sequence my dude
> 
> ```
> Sequence scaleSequence = DOTween.Sequence();
> scaleSequence.Append(transform.DOScale(7f, 0.3f));
> scaleSequence.AppendInterval(1f);
> scaleSequence.Append(transform.DOScale(0f, 0.2f));
> ```
Delight by your code, I write:
```
        scaleSequence.Insert(0f, transform.DOScale(7f, 0.3f));
        scaleSequence.Insert(1f, transform.DOScale(0f, 0.2f));
```
It works too! Thank you.
