### ISSUE TITLE
[Improvement][API consistency] Kill( ), KillAll( ), methods are missing complete with callbacks param

### ISSUE THREAD

**Issue by floky** [Demigiant/dotween#589]
At one point, Complete( ) methods on tweens/sequences received an extra super-useful param "withCallbacks". 🎉

Considering that Kill( ) and KillAll( ) methods have the option to also complete the tweens, I think it would be a great API consistency improvement to also have the "withCallbacks" param added to the killing methods.

What do you think? 🤔

**Comment by Demigiant** [comment]
Yoyooo!!! Very good point, adding it to my todo list :)

**Comment by floky** [comment]
> Yoyooo!!! Very good point, adding it to my todo list :)

😁 it's no big observation, but more of a quality of life improvement. 🤗
