### ISSUE TITLE
Tween doesn't occur; no errors

### ISSUE THREAD

**Issue by ayyobro** [Demigiant/dotween#594]
I have imported the right using statement:

`using DG.Tweening;`

I have applied a tween using an available method ( IDE is picking up on autocomplete as well ):

`transform.DOBlendableLocalMoveBy(transform.forward * _dodgeDistance, TweenSpeed);`

I have confirmed in debugging that the method is executed. 

However, the tween is not applied to the object. 

Strange! No errors in the console, either.

Edit: 
- I've uninstalled and re-installed modules through the utility but that didn't help.

**Comment by Demigiant** [comment]
Closing this since I answered via mail :)
