### ISSUE TITLE
Any plans to create a version without Physics usage?

### ISSUE THREAD

**Issue by Mythic-Studio** [Demigiant/dotween#597]
We are not using Unity physics engine in our project, but need to keep the package so that DoTween can compile. Are there any plans to remove all references to Physics in a future version? Or would you suggest to just modify the code on our end?

**Comment by Demigiant** [comment]
Ahoy! That's what modules are for. If you run DOTween's Setup from the Utility Panel and disable the Physics module, no tweens will refer to it :)

**Comment by Mythic-Studio** [comment]
Thank you, I must've have overlooked it. Cheers.
