### ISSUE TITLE
DOTweenModuleUI.cs is not working with Unity 2021.2.12f1

### ISSUE THREAD

**Issue by XynanXDB** [Demigiant/dotween#600]
![image](https://user-images.githubusercontent.com/32987787/193460960-d3089959-74c7-4ecd-96a9-84c718f8688d.png)

As the image above shows the script is been ignored by the preprocessors above. All scripts that have the similar preprocessors are ignored.

**Comment by Demigiant** [comment]
Ahoy! That seems like a specific bug with Unity 2021.2.12, where Unity forgot to include the "2017_OR_NEWER" define. I'm on 2021.3.11 and I can confirm it's fixed and working there (probably they already fixed it in 2021.2.13 but I can't find it in their release notes).

**Comment by XynanXDB** [comment]
@Demigiant I upgraded to 2021.3.11f1, the problem still persist though.

**Comment by Demigiant** [comment]
That is extremely weird :O I have it open here and correctly getting the defines:

![image](https://user-images.githubusercontent.com/8322877/193465290-d9776e57-d5e9-4d10-87e0-979c772bb1f1.png)

Could you try replacing line 4 with
`#if true && UNITY_2021_1_OR_NEWER // MODULE_MARKER`
to see if for some reason your Unity is not reading any defines?

**Comment by XynanXDB** [comment]
Just now I go far to use 2022.1.18f1, the problem still exist

**Comment by XynanXDB** [comment]
Hmmm, I see that you are using Rider, currently I'm using VS Community. I don't know if this will do anything though.

**Comment by XynanXDB** [comment]
> 

Using `#if true && UNITY_2021_1_OR_NEWER // MODULE_MARKER` doesn't work either.

**Comment by XynanXDB** [comment]
It's alright I have solved it, I realized my config is set to Release rather than Debug, I flipped it back to Debug then it works already. Thanks for your time.

**Comment by Demigiant** [comment]
Oh damn, I hadn't thought of it. Unity always builds in Debug mode, but I would've expected the defines to work in all modes
