### ISSUE TITLE
Typo in latest release date on website

### ISSUE THREAD

**Issue by rhys-vdw** [Demigiant/dotween#607]
Hey @Demigiant. Just a heads up, you've listed the latest release as:

> Download DOTween v1.2.705
> (OCtober 102, 2022)

Presumably was Oct 10 or 12?

![image](https://user-images.githubusercontent.com/822105/198912283-624d8bda-ea93-4984-9be8-17f4bd89c520.png)

**Comment by Demigiant** [comment]
Ouch, thank you. I just checked and the date is written correctly on my side, so my php script must've gone crazy for some mysterious reason. Checking it out
