### ISSUE TITLE
DOPath rotation bug for SetLookAt

### ISSUE THREAD

**Issue by dczlonka** [Demigiant/dotween#61]
Hi,
I love DOTween but unfortunately found a bug. I've made code for unit movement:

```
yield return unitView.transform.DOPath(path, Unit.MovementSpeed, PathType.CatmullRom, PathMode.Full3D)
            .SetLookAt(0.01f).SetEase(Ease.Linear).SetSpeedBased(true).WaitForCompletion();
```

Problem is that sometimes unit at the end of path changes rotation to state before tween.

**Reproduction**:
1) Unit is heading down.
2) Move unit right using DOPath (two waypoints - from current position to x+1).
3) Through whole path unit was heading right, but at the end it's heading down again.

**Important**
I found out that if I run gameplay scene, there's no bug.
If I launch menu scene and then launch gameplay scene from it - bug appears.

**Comment by dczlonka** [comment]
DOTween 1.1.200 [Release build].
Unity 5.3.4f1

**Comment by Demigiant** [comment]
This is very weird, especially the fact that it happens to you only if you launch the menu scene before. Can you reproduce it in a barebone test project and send it to me, so I can check it out?

**Comment by dczlonka** [comment]
Ok, I will try to reproduce it in clean project.

**Comment by dczlonka** [comment]
@Demigiant I was not able to reproduce this bug in clean project. Those are my observations:
1. When I use PathType.**Linear** instead of PathType.**CatmullRom**, everything works fine.
2. When I move more than 1 (distance in world), character rotates properly (check attached video).
3. Environment position somehow changes reproduction chance. I've modified environment position by (0.1f, 0, 0.1f) for test and it was more difficult to reproduce. Maybe values are snapping?

I know it's difficult to fix bug that can't be reproduced easily. Maybe you will have some tips how to reproduce it after reading my comment.

[DOTween bug.mp4.zip](https://github.com/Demigiant/dotween/files/202336/DOTween.bug.mp4.zip)

**Comment by justonia** [comment]
I am encountering this bug as well. When my path options are set to CatmullRom and a SetLookAt(0.01f) my object being tweened has it's forward direction reset when it reaches the endpoint of the path.

**Comment by felipe-torres** [comment]
I'm experiencing this weird bug too! For some weird reason, sometimes at the end of DOPath, the transform does a small rotation on it's own :/

**Comment by ghost** [comment]
EDIT:
@Demigiant - Any luck on this?
(https://github.com/Demigiant/dotween/files/832798/DoPath.Unity.551p4.zip)
When the object reaches the end of the path it rotates by a tiny but very noticable amount as if to fix the final rotation. A quick vid of it happening in the scene view is here: 

> https://drive.google.com/open?id=0B9rQSqS4lItaQ1FidHpBS1AxRkk

I am using the following
`transform.DOPath (new Vector3[]{ l.transform.position }, 5, PathType.CatmullRom, PathMode.Full3D)
.SetLookAt (targetSO.transform)
.SetEase(Ease.InOutCubic);`

Anybody found a solution to this?

UPDATE: Attaching a barebones test project [DoPath Unity 551p4.zip]

**Comment by Demigiant** [comment]
Ouch, sorry guys I thought I solved this but didn't come back to mention it. But apparently I didn't if it's still happening :B Gonna check your test project later today, thanks for reproducing it.

**Comment by ghost** [comment]
@Demigiant - Were you able to fix this?

**Comment by Demigiant** [comment]
[Fixed](http://dotween.demigiant.com/download.php)! And greatly sorry for taking so much time. This was actually easy to fix, once I realized what was causing it. But it was really complicated to determine the cause.
