### ISSUE TITLE
ChangeEndValue on DOAnchorPosX expects Vector2 instead of float

### ISSUE THREAD

**Issue by PeterDekkers** [Demigiant/dotween#62]
On a tween that uses DOAnchorPosX calling ChangeEndValue expects a Vector2 (X and Y) whereas the original tween setup takes a float (only X).

DOTween v1.1.260.

Error given:

```
DOTWEEN :: ChangeEndValue: incorrect newEndValue type (is System.Single, should be UnityEngine.Vector2)
UnityEngine.Debug:LogWarning(Object)
DG.Tweening.Core.Debugger:LogWarning(Object) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/Debugger.cs:26)
DG.Tweening.Core.TweenerCore`3:ChangeEndValue(Object, Single, Boolean) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenerCore.cs:83)
```

**Comment by Demigiant** [comment]
Hi,

That is normal, because ChangeEndValue wants an endValue that corresponds to the property to change. If the tween you're changing was a DOSomethingX/Y/Z/W though, it will only consider that specific coordinate.

**Comment by Demigiant** [comment]
P.S. to add to this answer... overloads for ChangeEndValue that accept a single float in case of a Vector2/3/4 property aren't really doable (I tried that), because they would not be efficient.
