### ISSUE TITLE
IL2CPP error when building Android app for armv7

### ISSUE THREAD

**Issue by leaptiger** [Demigiant/dotween#633]
Unity: 2021.3.16f1
DOTween: v1.2.705

I got the following error:

Building Library\Bee\artifacts\Android\fy9m9\libil2cpp.so failed with output:
C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld.gold.exe: internal error in arm_branch_common, at /buildbot/src/android/binutils/toolchain/binutils/binutils-2.27/gold/arm.cc:4063
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UnityEditor.GenericMenu:CatchMenu (object,string[],int)

If I built for armv64, everything is ok.

Can anyone help me out?

**Comment by Demigiant** [comment]
Ahoy,

I don't see it related to DOTween. It should be a Unity bug related to Android builds, and this post seems to have some helpers: https://forum.unity.com/threads/il2cpp-build-time-improvements-seeking-feedback.1064135/page-3#post-8411235
