### ISSUE TITLE
NullReferenceException Error when click the "Play" button in DOTween Animation component

### ISSUE THREAD

**Issue by LudoArt** [Demigiant/dotween#646]
In the example scene "DOTweenAnimation_Basics", when I click the play button in DOTween Animation component, then receive an error message.

> NullReferenceException: Object reference not set to an instance of an object
> DG.DOTweenEditor.EditorCompatibilityUtils.FindObjectsOfType (System.Type type, System.Boolean includeInactive) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/EditorCompatibilityUtils.cs:119)
> DG.DOTweenEditor.DOTweenEditorPreview.Start (System.Action onPreviewUpdated) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTweenEditor/DOTweenEditorPreview.cs:49)
> DG.DOTweenEditor.DOTweenPreviewManager.StartupGlobalPreview () (at Assets/ThirdPart/Demigiant/DOTweenPro/Editor/DOTweenPreviewManager.cs:146)
> DG.DOTweenEditor.DOTweenPreviewManager.PreviewGUI (DG.Tweening.DOTweenAnimation src) (at Assets/ThirdPart/Demigiant/DOTweenPro/Editor/DOTweenPreviewManager.cs:59)
> DG.DOTweenEditor.DOTweenAnimationInspector.OnInspectorGUI () (at Assets/ThirdPart/Demigiant/DOTweenPro/Editor/DOTweenAnimationInspector.cs:294)
> UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <a8712505b6e242ce9a8fa1ca2baf8910>:0)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
> 

Unity version: 2019.4.33f1
DOTween version: v1.2.740[Release build]
DOTweenPro version: v1.0.370

**Comment by Demigiant** [comment]
Ahoy,

Thank you for the report and sorry for this, I broke it during the last update that made the preview system compatible with Unity 2023 beta. I just published an update to the Asset Store that fixes it (v1.0.375)
