### ISSUE TITLE
Tweens with duration of 0 not working

### ISSUE THREAD

**Issue by wrymn** [Demigiant/dotween#650]
I want to set a tween end value instantly, but when I give it duration of 0, it just doesnt play or do anything.

This just breaks the tween, where it won't either scale to 0, nor play the second tween at all:

```
private void TweenScale(Transform transform, int index)
        {
            DOTween.Sequence(transform)
                .Append(transform.DOScaleX(0, 0))
                .Append(transform.DOScaleX(1, 0.3f).SetDelay(index * 0.1f));
        }
```

This is the same outcome, where second tween won't play at all as well, and transform scale will stay 1

```

        private void TweenScale(Transform transform, int index)
        {
            transform.DOScaleX(0, 0).Complete();
            transform.DOScaleX(1, 0.3f).SetDelay(index * 0.1f);
        }
```

or this won't do anything:

```
        private void TweenScale(Transform transform, int index)
        {
            transform.DOScaleX(0, 0);
            transform.DOScaleX(1, 0.3f).SetDelay(index * 0.1f);
        }
```

Only when I set the duration to 0.1f for scale 0, it works:

```
        private void TweenScale(Transform transform, int index)
        {
            DOTween.Sequence(transform)
                .Append(transform.DOScaleX(0, 0.1f))
                .Append(transform.DOScaleX(1, 0.3f).SetDelay(index * 0.1f));
        }
```

However, when I set duration to something smaller, to like 0.01, it again does not work at all :) 

```
        private void TweenScale(Transform transform, int index)
        {
            DOTween.Sequence(transform)
                .Append(transform.DOScaleX(0, 0.01f))
                .Append(transform.DOScaleX(1, 0.3f).SetDelay(index * 0.1f));
        }
```

Edit: documentation does not mention this how to do it

**Comment by Demigiant** [comment]
Ahoy!

I have tested your code and everything works, both with 0 duration and very low ones, so I'm puzzled. This used to be a problem in older versions of DOTween where 0-duration tweens were not allowed, but it should all be working now. On what version are you? From your other messages I assume the latest, but I'm asking just to confirm. Latest is DOTween 1.2.745 (and Pro 1.0.375).

On a side note, about other ways to do this, you can use the From method overload ([this one](http://dotween.demigiant.com/documentation.php?api=From__1)) to tell the tween to start "from a value", thus skipping the 0-duration tween completely.

Simpler Sequence version:

```
DOTween.Sequence(transform)
   .Append(transform.DOScaleX(1, 0.3f).From(0).SetDelay(0.5f));
```

No Sequence version:

```
transform.DOScaleX(1, 0.3f).From(0).SetDelay(0.5f);
```

Both will behave exactly the same

**Comment by wrymn** [comment]
Hello @Demigiant, thank you very much for the reply :)

I have tested your code, as well as upgraded from 1.2.735, and it works fine, thank you again! :)
