### ISSUE TITLE
No valid component was found for the selected animation

### ISSUE THREAD

**Issue by maxmason007** [Demigiant/dotween#654]
Hiya!

I'm running Unity 2021.3.11f1 with DOTween v1.2.745 and its giving me the error "No valid component was found for the selected animation" when using the fade animation type on a gameobject which has a canvas and a TMpro object as the child.

I added the TMPro module when importing the plug in...any help?
![Snip20230830_2](https://github.com/Demigiant/dotween/assets/105564077/6da13b5c-e082-4973-8526-7a913a189724)

**Comment by Demigiant** [comment]
Ahoy!
Is it possible that the TextMesh Pro component is not on the HelloWord gameObject but on one of his children? I don't see it in the Inspector and that would cause DOTweenAnimation to respond like that

**Comment by maxmason007** [comment]
Yes that worked, thank you!
