### ISSUE TITLE
ChangeStart/EndValue on DOMoveX/Y/Z takes a Vector3 rather than a float

### ISSUE THREAD

**Issue by mjholtzemWW** [Demigiant/dotween#67]
when using the DoMove[Axis] or DoLocalMove[Axis] shortcuts if you chain ChangeEndValue or ChangeStartValue it will have no effect unless you pass in a Vector3. This is confusing since the shortcut takes in a float for endValue.

I should be able to say...
`transform.DoLocalMoveY(10, 50).ChangeStartValue(0);`
but right now I need...
`transform.DoLocalMoveY(10, 50).ChangeStartValue(Vector3.zero);`

**Comment by PeterDekkers** [comment]
Duplicate of https://github.com/Demigiant/dotween/issues/62
