### ISSUE TITLE
DotTween Pro - Visual Path Editor - Add Plugin Support?

### ISSUE THREAD

**Issue by ReevMich** [Demigiant/dotween#69]
Is there a way to add some extra fields in the inspector of the Visual Path Editor Script??

**Comment by Demigiant** [comment]
Hi,

What extra fields do you have in mind?

**Comment by ReevMich** [comment]
A way of tagging specific waypoints on a path. I can do with with indices but that is kind of a pain to be efficient. So maybe  adding a enum or string field to each waypoint on a path somehow.

**Comment by Demigiant** [comment]
I'm afraid that isn't possible, because it would require to store more informations inside the tweens themselves, and that's something I try to avoid for lightweight reasons. Still, if you consider that enums can be converted to ints, you could already use enums as regular indexes :P

**Comment by ReevMich** [comment]
I will give that a try thank you!!! :)
