### ISSUE TITLE
sequence.Complete(); Completes a completely unrelated sequence

### ISSUE THREAD

**Issue by LazyEti** [Demigiant/dotween#694]
Hello, I'm a Dotween Pro user (unity 2022.3.19).
I noticed that a sequence in one of my script would unexpectedly complete without being done. 
After adding a debug log, I noticed that what caused my sequence to complete was triggered from a completely different and unrelated script.
The weird thing is that this is not consistent. It happens only 1 out of 10 times or so like if it was an execution timing bug.
Am I using .Complete() the wrong way or is this a reference bug in DoTween which sometime mix up sequences?
This makes me anxious this could happen elsewhere and completely break the game since many things rely on sequences...

### Script 1: Fading away a decal and then destroying it  (Getting completed unexpectedly)
```
        Sequence sequence = DOTween.Sequence ();
        sequence
            .Join (DOTween.To (() => decal.fadeFactor, x => decal.fadeFactor = x, alpha, appearTime).SetEase(Ease.OutCirc))
            .AppendInterval (timeBeforeDespawn + (Random.value * 3))
            .Append (DOTween.To (() => decal.fadeFactor, x => decal.fadeFactor = x, 0, disappearTime).SetEase (Ease.InOutSine))
            .OnComplete (()=>
            {
                Debug.Log ("WHY???");  //This sequence is somehow getting completed from another script.
                Destroy (gameObject, 1);
            } );
```

### Script 2: Unrelated ui feedback  (somehow triggers the completion of sequence from script 1)
```
if (moneySequence != null) moneySequence.Complete ();
 moneySequence = DOTween.Sequence ();

 if (barsize < currentSoulBar.localScale.y)
     moneySequence.Join (soulBar.DOShakePosition (.2f, 3, 17));
 else
     moneySequence.Join (soulBar.parent.DOShakeRotation (.2f, 20, 12));
```

### Trace log:
```
WHY???
UnityEngine.Debug:Log (object)
BloodDecal:<Start>b__6_4 () (at Assets/_Scripts/BloodDecal.cs:33)
DG.Tweening.Tween:OnTweenCallback (DG.Tweening.TweenCallback,DG.Tweening.Tween) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:298)
DG.Tweening.Tween:DoGoto (DG.Tweening.Tween,single,int,DG.Tweening.Core.Enums.UpdateMode) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:282)
DG.Tweening.Core.TweenManager:Complete (DG.Tweening.Tween,bool,DG.Tweening.Core.Enums.UpdateMode) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:730)
DG.Tweening.TweenExtensions:Complete (DG.Tweening.Tween,bool) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/TweenExtensions.cs:62)
DG.Tweening.TweenExtensions:Complete (DG.Tweening.Tween) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/TweenExtensions.cs:44)
Core.Player.Player_Ui:RefreshSoullBar () (at Assets/_Scripts/Player/Player_Ui.cs:90)
Core.Player.PlayerController:CollectSoul (UnityEngine.Vector3,int) (at Assets/_Scripts/Player/PlayerController.cs:216)
Core.Player.SoulPickup:OnTriggerStay (UnityEngine.Collider) (at Assets/_Scripts/SoulPickup.cs:59)
```

**Comment by Decavoid** [comment]
Is recycleAllByDefault=true in `DOTween.Init()`? If yes, then you must null completed tween references in `OnKill()`.

**Comment by LazyEti** [comment]
> Is recycleAllByDefault=true in `DOTween.Init()`? If yes, then you must null completed tween references in `OnKill()`.

@Decavoid  I never called DoTween.Init() so I think that "recycleAllByDefault" should be false by default. 

However, how do you "null completed tween references in OnKill()" ? 
Do you mean something like this?

```
sequence = DOTween.Sequence ();
sequence.Join ("do something");
sequence.OnKill (() => sequence = null);
```

**Comment by Decavoid** [comment]
Check DOTween settings window, something like "reuse tweens".
Example of nulling completed tweens:
```
moneySequence = DOTween.Sequence().OnKill(() => moneySequence = null);
moneySequence.Join(...);
moneySequence.Insert(...);
```

**Comment by LazyEti** [comment]
@Decavoid Thank you so much! I've been using Dotween for 2+ years and only now do I learn about this
Thank god I got really lucky with tween recycling so far and it didn't crash my projects!

**Comment by LazyEti** [comment]
This seems to fix the issue so I'll close this down!
