### ISSUE TITLE
tween is not working in windows universal 10

### ISSUE THREAD

**Issue by prabhii8089** [Demigiant/dotween#70]
hi,
Dot tween is working fine in both android and ios.But same project in windows universal 10  is not working.I mean basic tween one position to another.

**Comment by Demigiant** [comment]
Hi,

That is a Unity bug: they're working on it but have no date yet. Anyway, just download the [Hyper-Compatible version](http://dotween.demigiant.com/download.php) and it will work :) You just have to replace the DOTween folder with the ZIP's content and re-run the setup, no changes needed in your code.

**Comment by prabhii8089** [comment]
Hi,
K. thanks for the reply.pls let me try that version.
thank you.

**Comment by prabhii8089** [comment]
Hi,
I did in that way.I just replaced the folder with hyper compatible dot tween folder.But it is still not working.Please advise me if i missed anything or had so..
thank you

**Comment by Demigiant** [comment]
Damn, that is very weird. Did you run the setup again? If yes, and you still have issues, can you give me more  details and the error log (using the hyper-compatible version)?

**Comment by castorlighting** [comment]
Hi,
Same Issue here. I tried the hyper compatible version and ran the Setup again, but it does not work on Windows 10.
`
0x010E5325 (cubeDemo) 

[c:\buildslave\unity\build\platformdependent\winplayer\winmain.cpp:469] PlayerMainWndProc 

0x7763D273 (USER32) SetManipulationInputTarget

0x7761E84A (USER32) DispatchMessageW

0x77630108 (USER32) CallWindowProcA

  ERROR: SymGetSymFromAddr64, GetLastError: 'Das angegebene Modul wurde nicht gefunden.' (Address: 06B62C24)

  ERROR: SymGetModuleInfo64, GetLastError: 'Eine DLL-Initialisierungsroutine ist fehlgeschlagen.' (Address: 06B62C24)

0x06B62C24 ((<unknown>)) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Das angegebene Modul wurde nicht gefunden.' (Address: 06B62B74)

  ERROR: SymGetModuleInfo64, GetLastError: 'Eine DLL-Initialisierungsroutine ist fehlgeschlagen.' (Address: 06B62B74)

0x06B62B74 ((<unknown>)) 

  ERROR: SymGetSymFromAddr64, GetLastError: 'Das angegebene Modul wurde nicht gefunden.' (Address: 0561007C)

  ERROR: SymGetModuleInfo64, GetLastError: 'Eine DLL-Initialisierungsroutine ist fehlgeschlagen.' (Address: 0561007C)

0x0561007C ((<unknown>)) 

`
