### ISSUE TITLE
ChangeEndValue() stops OnComplete from firing

### ISSUE THREAD

**Issue by SavedByZero** [Demigiant/dotween#72]
I have an OnUpdate function like this:

`tweener.OnUpdate (() => tweener.ChangeEndValue (new Vector3 (destTarget.transform.position.x, destTarget.transform.position.y, -1), tweener.Duration () - tweener.Elapsed (), true));
`
And a separate OnComplete function that fires okay without the OnUpdate call above, but never fires when that is called.  

expected result: OnUpdate should not overwrite the OnComplete call, whether or not the end value is changed.

**Comment by Demigiant** [comment]
When you change the end value, the tween restarts from the current position it's at, so if you fire it at every update you're never allowing it to complete.
