### ISSUE TITLE
DOTween.Kill ("twId", true);  the callBack not excute

### ISSUE THREAD

**Issue by Fuatnow** [Demigiant/dotween#77]
`
var moveTo1 = curGird.transform.DOMoveX (toX-0.05f, moveTime).SetEase (Ease.OutQuad);

var moveTo2 = curGird.transform.DOMoveX(toX,0.05f).SetEase(Ease.InQuad);

var seq = DOTween.Sequence();

seq.Append(moveTo1).Append(moveTo2).AppendInterval(0.1f).AppendCallback(()=>{
                CanDropDown = true;
                isCurGirdMoving = false;
                testGameOver();
            });

seq.SetId ("twId");`

`
int killNum = DOTween.Kill ("twId", true);

the move tween is complete , but the callback not execute.
`

**Comment by Demigiant** [comment]
Completing a tween when killing it doesn't fire callbacks.
