### ISSUE TITLE
Killing running sequence not works as expected.

### ISSUE THREAD

**Issue by Xin-SHEN** [Demigiant/dotween#78]
Hello there, 

Thank you for your great DOTWEEN !
I created a sequence with several Append and Join on it. 
When it is running, I want kill all tweener in this sequence by using mySequence.Kill();
But it turns out only current tweener was killed, all the rest tweeners still get started one by one.

Thanks and Regards,
Xin

**Comment by Demigiant** [comment]
Hi Xin,

You can only kill the full topmost Sequence, not nested tweens or sequences
inside it. Once a Sequence is created, it's like a fixed movieclip, in a
way.

Cheers,
Daniele

**Comment by Xin-SHEN** [comment]
Dear Demigiant,

Any way to force running sequence stop (complete) including all tweeners inside?
I test DOTween.KillAll() resluting the same thing : topmost tween stops, and the rest tweeners in sequence still start as planned at first.

Regards,
Xin

**Comment by Demigiant** [comment]
Hi Xin,

To kill and complete a Sequence you can call mySequence.Kill(true). About
DOTween.KillAll, I'm not sure what you mean. Once a Sequence is killed its
tweens won't work anymore.

Cheers,
Daniele
