### ISSUE TITLE
[Error] OnLevelWasLoaded was found on DOTweenComponent

### ISSUE THREAD

**Issue by RevoluPowered** [Demigiant/dotween#82]
I recieved this error when loading up my project in the new stable unity release, thought you should be made aware of the issue.

**OnLevelWasLoaded was found on DOTweenComponent**
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed

This occurs using  v1.1.135 **(non-pro).** 
Unity Version: 5.40f3 **(Current stable release)**

If you require any more information, please don't hesitate to contact me.

**Comment by Demigiant** [comment]
Hi,

Thank you for the report. The Asset Store version is behind right now. Grab the latest version [here](http://dotween.demigiant.com/download.php), which fixes this issue.

Cheers,
Daniele

**Comment by RevoluPowered** [comment]
That fixed it thank you; additionally thank you for releasing an awesome tool.
