### ISSUE TITLE
Cannot build my app using DOTween after upgrading to Unity5.4

### ISSUE THREAD

**Issue by hattori** [Demigiant/dotween#83]
When I play my app in Unity Editor, it works.
But I try to build my app, the following errors are shown in console and the build process was canceled. 
My Unity version is 5.4.0f3 and DOTween version is 1.1.135[Release Build].

---

Unhandled Exception: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at Mono.CSharp.RootNamespace.ComputeNamespaces (System.Reflection.Assembly assembly, System.Type extensionType) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.RootNamespace.ComputeNamespace (Mono.CSharp.CompilerContext ctx, System.Type extensionType) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.GlobalRootNamespace.ComputeNamespaces (Mono.CSharp.CompilerContext ctx) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.Driver.LoadReferences () [0x00000] in <filename unknown>:0 
  at Mono.CSharp.Driver.Compile () [0x00000] in <filename unknown>:0 
  at Mono.CSharp.Driver.Main (System.String[] args) [0x00000] in <filename unknown>:0 

The following assembly referenced from C:\MyGame\Assets\Demigiant\DOTween\DOTween46.dll could not be loaded:
     Assembly:   UnityEngine.UI    (assemblyref_index=4)
     Version:    1.0.0.0
     Public Key: (none)
The assembly was not found in the Global Assembly Cache, a path listed in the MONO_PATH environment variable, or in the location of the executing assembly (C:\MyGame\Assets\Demigiant\DOTween).

Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

Cheers

**Comment by hattori** [comment]
Oh I found this thread.
http://forum.unity3d.com/threads/dotween-hotween-v2-a-unity-tween-engine.260692/page-44

1.1.200 has been released !?

I've check Unity AssetStore but it's still 1.1.135... plz update.

Thanks !

**Comment by hattori** [comment]
Sorry again.

I've updated DOTween to 1.1.310 (found on the official site) but I'm still getting the exactly same errors as above.

Plz check it out...

Thanks.

**Comment by Demigiant** [comment]
Hi,

I assume you're building with Cloud Build? It appears that you're missing the DOTween46.dll. I assume you ran the setup, otherwise it wouldn't run in the editor, so it's probably CB. Could Build is sometimes pre-configured to not upload DLLs, you'll have to check the settings and allow them.

**Comment by hattori** [comment]
Hi, Demigiant.

Thanks for the quick reply.
Actually I'm building with Unity Editor (Unity5.4.0f3, came out a couple of days ago.), 
Not with Cloud Build...

I have the DOTween46.dll in Assets/Demigiant/DOTween directory in my Unity project and Of couser, I run the setup.
I did everything I can but no luck...

My app run in the editor but cannot be built.
When I build my app to create an Android apk, those errors come out in console and build process is canceled.

I have tried building with Unity5.4 on both machines and this problem occurred only on Windows but not on Mac.

Thanks.

**Comment by Demigiant** [comment]
Unless Unity reintroduced an old weird bug, this must be something else, I hope. Are you building for Android? Are you using MONO instead of IL2CPP? Can you try the latter and let me know?

I can't upgrade to check the new Unity 5.4 until Tuesday (I have an old 5.4 beta but there everything works), so I can't check if it's a Unity version issue or not right now :/

**Comment by hattori** [comment]
Hi, Demigiant.

I tried building today and I don't know why but it worked well....
I haven't changed any settings after I failed building last time.
(Maybe restarting Unity solved the problem ?? I don't know tho.)
FYI, I built with MONO.

Thanks a lot !

**Comment by Demigiant** [comment]
Ah! That is both cool and weird ___ Glad it's solved anyway!

Cheers!
