### ISSUE TITLE
Warning: OnLevelWasLoaded was found on DOTweenComponent

### ISSUE THREAD

**Issue by MaxStriebel** [Demigiant/dotween#85]
I hope this problem wasn't posted bevor, but i couldn't find it.

After upgrading to Unity 5.4 a message appeares telling that OnLevelWasLoaded is no longer supported.
"Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed"

**Comment by Demigiant** [comment]
Hi,

The asset store version is behind (should be updated within the week). Grab the latest version [here](http://dotween.demigiant.com/download.php), which solves it ;)

Cheers,
Daniele

**Comment by MaxStriebel** [comment]
Hi,
thanks for the fast reply

Cheers
Max
