### ISSUE TITLE
[Android Only] DOScale() on object with a collider component causes an internal error in unity.  Subsequent raycasts fail.

### ISSUE THREAD

**Issue by daveinnes** [Demigiant/dotween#88]
The following error occurs when calling DoScale() on an object with a collider component.

Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "<object_path>"

Furthermore, subsequent raycasts on objects with colliders instantiated after the error will not return any hits.

**Comment by Demigiant** [comment]
Hi,

DOScale just changes the localScale of your target to the value you set, everything else is unrelated to DOTween. I guess you set the scale to 0, which is something a transform, especially if with a collider, doesn't really support. ;)
