### ISSUE TITLE
Is there a way to determine the time/percentage that a particular point will be passed?

### ISSUE THREAD

**Issue by kruncher** [Demigiant/dotween#89]
For instance,

``` csharp
var path = new Vector3[] { targetPoint, exitPoint };
var pathTween = modelTransform
    .DOPath(path, 0.8f, PathType.CatmullRom).SetEase(Ease.Linear)
    .OnUpdate(() => {
        // pseudo-code:
        if (pathTween.GetCompletionPercentage() >= pathTween.GetPathNodeCompletionPercentage(0)) {
            // Currently at or past the first path node.
        }
    });
```

I would like to trigger a sound effect when the first point of the path has been reached.

Many thanks

**Comment by Demigiant** [comment]
Hi Lea,

You don't need OnUpdate for that, you can use the [OnWaypointChange](http://dotween.demigiant.com/documentation.php?api=OnWaypoint) callback to
know when the tween reaches a point, and behave accordingly.

Cheers,
Daniele

**Comment by kruncher** [comment]
Perfect; thanks for the super fast response!!

That definitely deserves an upgrade from standard to Pro :+1: 

Edit: Purchased!
