### ISSUE TITLE
Speedbased Sequence

### ISSUE THREAD

**Issue by Feldruebe** [Demigiant/dotween#9]
Hello,

I am using DOTween v1.0.470.

I tried to setup a speed based sequence as followed.
Sequence rotationSequenz = DOTween.Sequence();
            rotationSequenz.Append(TestToolbox.Instance.PositionMarker.transform.DOLocalRotate(new Vector3(0, 0, angle), 0.5f, RotateMode.LocalAxisAdd).SetSpeedBased(true));
            rotationSequenz.Append(TestToolbox.Instance.PositionMarker.transform.DOLocalRotate(new Vector3(-angleX, 0, 0), 0.5f, RotateMode.LocalAxisAdd).SetSpeedBased(true));
            rotationSequenz.SetSpeedBased(true);

But it still uses the duration based tweening.
Did i something wrong or is speedbased nog supporfed for sequences?

Thanks for your help
Michael.

**Comment by veboys** [comment]
Has no effect if the tween has already started or is inside a Sequence.

**Comment by Demigiant** [comment]
Hello,

veboys has the truth of DOTween's docs in his hands. Sequences need to know a tween's duration immediately and can't wait for it to be setup as SpeedBased, so that's why that won't work, sorry.

Cheers,
Daniele

**Comment by Feldruebe** [comment]
My bad, did not read that.
Thanks for the reply.
