### ISSUE TITLE
DOTween not importing on Unity 5.5.0a5 beta

### ISSUE THREAD

**Issue by shlapkoff** [Demigiant/dotween#90]
DOTween not importing on Unity 5.5.0a5 alpha
https://docs.google.com/document/d/1vGzfB3gIU4AEYOjseJxjYytisFkwOKRfEzI5Db6_1vQ/edit#heading=h.g8wzlk40k9y

Unity version:
http://beta.unity3d.com/download/fd625b0c0421/download.html?_ga=1.80669599.944652853.1472470484

**Comment by Demigiant** [comment]
Hi,

Could you give me more info on the error you have when importing DOTween? I can't install the 5.5 beta right now, and that document doesn't seem to have any breaking changes regarding DOTween.

Cheers

**Comment by shlapkoff** [comment]
In Unity 5.5.0b3 all good. You can close this issue.

**Comment by Demigiant** [comment]
Great, thanks for the update.
