### ISSUE TITLE
Adding DOTween pro to existing project, wont recognise ID's on existing image elements

### ISSUE THREAD

**Issue by DanielGriffiths** [Demigiant/dotween#93]
Adding DOTween pro to existing project, wont recognise ID's on existing image elements in the UI/Scene.
I have had to recreate the image game objects and then add the animation script for them to work.
This is is when you add the Animation Script to a GameObject.

Thanks

Daniel

**Comment by Demigiant** [comment]
Hi Daniel,

I'm not sure what you mean. What IDs should be recognized automatically from image elements?

Cheers,
Daniele

**Comment by DanielGriffiths** [comment]
Good Morning Daniele,

Thanks for coming back about the issue I have experienced.

I have attached a screen shot of the unity layout.

If you look at the image you will see I have a image element called ‘ CashDefault ‘. I initially had this project setup and working without DOTween. I then purchaced your pro version and imported the asset.

As you can see from the screen shot I have attached the ‘DOTween Animation’ script and set a ID of Default.

What happened is that Do tween would not play the animation when I called the aniomation from script like this: DOTween.Restart(“Default”);

I then tried all sorts trrying to find out why and eventually tried on a newly created image and it worked find.

It turned out that all images in the scene prior to importing your asset and applying ID’s would not get animated.

So the only way I could find around this bug is to recreate all the images/elements I wanted animated with DOTween.

I hope this helps.

Best Regards

Daniel

Daniel Griffiths| Software Developer
e: daniel.griffiths@ultrahaptics.commailto:daniel.griffiths@ultrahaptics.com
m: +44 (0)7949 759702
o: +44 (0)117 325 9002
w: www.ultrahaptics.comhttp://www.ultrahaptics.com/

Ultrahaptics Ltd.
The West Wing, Glass Wharf
Bristol, BS2 0EL, United Kingdom

**Comment by Demigiant** [comment]
Hi Daniel,

This seems all very weird, since there's no relation between existing content, IDs, and DOTween, nor anything like this was ever reported. Can you send me the screenshot again, which might help me see something? Consider that we're talking on github, not via mail, and there was no screenshot attached to your previous message.

Cheers,
Daniele
