### ISSUE TITLE
Is there a way to save all running tweens?

### ISSUE THREAD

**Issue by matej-zajacik** [Demigiant/dotween#94]
For games that have a full-state save system, where basically everything non-static is saved on user request, is there a way to also save all currently running tweens? Is this built into the lib or something we would need to implement ourselves? (We already have a full-state save system.)

Thank you!

**Comment by Demigiant** [comment]
Hi,

Nothing like that is implemented, so you'd need to implement it yourselves. Honestly, right now I can't think of a way to do that, other than saving all tweened elements by some kind of if plus their tween time position, and recreate the tweens with a Goto based on the loaded data.

Cheers!
Daniele
