### ISSUE TITLE
OnComplete() unexpected destroyed other instances of the same prefab

### ISSUE THREAD

**Issue by kevinkassimo** [Demigiant/dotween#95]
In a recent game I noticed a weird problem related to DOTween's OnComplete method.

The problematic code in my game looks like this

``` C#
float randX = Random.Range (-3.5f, 3.5f);  
GameObject one_shot = Instantiate(levelManager.lLibs.L1.Boss_00_P4_Shot, new Vector3(randX, 6f, 0f), Quaternion.identity) as GameObject;  
//...  
one_shot.transform.DOMoveY (-16f, 4f).OnComplete(() => Destroy(one_shot));  
```

As far as I noticed, it seems that this OnComplete would destroy the MOST RECENTLY created GameObject of the same prefab.

**Comment by Decavoid** [comment]
http://stackoverflow.com/questions/271440/captured-variable-in-a-loop-in-c-sharp
