### ISSUE TITLE
Same relative waypoint positions for prefab?

### ISSUE THREAD

**Issue by KaWzY** [Demigiant/dotween#96]
Hi I just started using DOTween pro. Is there a way to give a prefab the same animation, but instantiate the prefab in any location with the same relative waypoints to the instantiated position?

I'm not sure if im missing some thing obvious, but my prefabs all run the animation in the same global location.

Thanks,

Kawzy

**Comment by Demigiant** [comment]
Hi,

If you add a manager to your DOTweenAnimation ("Add Manager" button in the Inspector), you will find a small series of presets, among which "Pooling System", which will do what you want. In practice, it recreated the tween's values based on the position your target is instantiated (and thus becomes enabled).

Cheers,
Daniele
