### ISSUE TITLE
As a developer, I should be able to view the stacktrace whenever something wrongs occurs in a tween

### ISSUE THREAD

**Issue by Indiefreaks** [Demigiant/dotween#98]
Right now, whevener something wrong happens within a tween execution, we only get a stacktrace that leads us to where the tween has been instantiated.
It would be helpful to get us to see the stacktrace when the execution stopped because of an exception.

**Comment by Demigiant** [comment]
Hi!

Sorry I missed this issue. If you see something wrong happening but no full stack trace, it's because safe mode is on and whatever went wrong was disposed of. Disable safe mode to see full stack trace (but also get uncaught errors).
